-- Create "role_permissions" table
CREATE TABLE `role_permissions` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `role_id` bigint unsigned NOT NULL, `permission_code` varchar(100) NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `rolepermission_role_id_permission_code` (`role_id`, `permission_code`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "admin_users" table
CREATE TABLE `admin_users` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `username` varchar(60) NOT NULL, `password_hash` varchar(255) NOT NULL, `nickname` varchar(60) NULL, `avatar` varchar(255) NULL, `role_id` bigint unsigned NOT NULL, `totp_secret` blob NULL, `enabled` bool NOT NULL DEFAULT 1, `remark` varchar(255) NULL, `last_login_ip` varchar(64) NULL, `last_login_at` timestamp NULL, PRIMARY KEY (`id`), INDEX `adminuser_role_id` (`role_id`), UNIQUE INDEX `username` (`username`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "currencies" table
CREATE TABLE `currencies` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `code` varchar(3) NOT NULL, `symbol` varchar(10) NOT NULL, `position` enum('prefix','suffix') NOT NULL DEFAULT "prefix", `precision` int NOT NULL DEFAULT 2, `rate` decimal(20,8) NOT NULL DEFAULT 1.00000000, `enabled` bool NOT NULL DEFAULT 1, `sort` int NOT NULL DEFAULT 0, PRIMARY KEY (`id`), UNIQUE INDEX `code` (`code`), INDEX `currency_enabled` (`enabled`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "users" table
CREATE TABLE `users` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `username` varchar(60) NOT NULL, `email` varchar(255) NULL, `password_hash` varchar(255) NULL, `status` enum('active','banned','deleted') NOT NULL DEFAULT "active", `last_login_at` timestamp NULL, `invite_l1` bigint unsigned NULL, `invite_l2` bigint unsigned NULL, `invite_l3` bigint unsigned NULL, PRIMARY KEY (`id`), UNIQUE INDEX `email` (`email`), INDEX `user_invite_l1` (`invite_l1`), UNIQUE INDEX `username` (`username`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "settings" table
CREATE TABLE `settings` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `group` varchar(50) NOT NULL, `key` varchar(100) NOT NULL, `value` json NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `setting_group_key` (`group`, `key`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "products" table
CREATE TABLE `products` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `subsite_id` bigint unsigned NOT NULL DEFAULT 0, `category_id` bigint unsigned NULL, `name` varchar(150) NOT NULL, `slug` varchar(150) NOT NULL, `description` longtext NULL, `cover` varchar(255) NULL, `images` json NULL, `price` bigint NOT NULL DEFAULT 0, `factory_price` bigint NOT NULL DEFAULT 0, `draft_premium` bigint NOT NULL DEFAULT 0, `member_price` json NULL, `stock_type` enum('card','url','code') NOT NULL DEFAULT "card", `stock_visible` bool NOT NULL DEFAULT 1, `delivery_mode` enum('status','delete') NOT NULL DEFAULT "status", `control_config` json NULL, `dedup` bool NOT NULL DEFAULT 1, `sort` int NOT NULL DEFAULT 0, `status` tinyint NOT NULL DEFAULT 1, `upstream_source_id` bigint unsigned NULL, `upstream_product_code` varchar(128) NULL, `upstream_synced_at` timestamp NULL, PRIMARY KEY (`id`), INDEX `product_subsite_id_category_id` (`subsite_id`, `category_id`), UNIQUE INDEX `product_subsite_id_slug` (`subsite_id`, `slug`), INDEX `product_subsite_id_status` (`subsite_id`, `status`), INDEX `product_upstream_source_id` (`upstream_source_id`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "wallet_accounts" table
CREATE TABLE `wallet_accounts` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `user_id` bigint unsigned NOT NULL, `currency` varchar(3) NOT NULL DEFAULT "CNY", `available` bigint NOT NULL DEFAULT 0, `locked` bigint NOT NULL DEFAULT 0, `version` int NOT NULL DEFAULT 0, `updated_at` timestamp NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `user_id` (`user_id`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "wallet_transactions" table
CREATE TABLE `wallet_transactions` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `user_id` bigint unsigned NOT NULL, `direction` varchar(8) NOT NULL, `type` varchar(40) NOT NULL, `amount` bigint NOT NULL, `balance_before` bigint NOT NULL, `balance_after` bigint NOT NULL, `currency` varchar(3) NOT NULL DEFAULT "CNY", `reference` varchar(120) NOT NULL, `order_id` bigint unsigned NULL, `operator_id` bigint unsigned NULL, `remark` varchar(255) NULL, `created_at` timestamp NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `reference` (`reference`), INDEX `wallettransaction_type_created_at` (`type`, `created_at`), INDEX `wallettransaction_user_id_created_at` (`user_id`, `created_at`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "outbox_events" table
CREATE TABLE `outbox_events` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `module` varchar(32) NOT NULL, `type` varchar(64) NOT NULL, `aggregate_id` varchar(64) NOT NULL, `payload` json NULL, `dedupe_key` varchar(120) NOT NULL, `status` enum('publishing','published','failed') NOT NULL DEFAULT "publishing", `published_at` timestamp NULL, `created_at` timestamp NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `dedupe_key` (`dedupe_key`), INDEX `outboxevent_status_created_at` (`status`, `created_at`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "admin_roles" table
CREATE TABLE `admin_roles` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `name` varchar(60) NOT NULL, `code` varchar(60) NOT NULL, `description` varchar(255) NULL, `is_builtin` bool NOT NULL DEFAULT 0, PRIMARY KEY (`id`), UNIQUE INDEX `code` (`code`), UNIQUE INDEX `name` (`name`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "payment_channels" table
CREATE TABLE `payment_channels` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `subsite_id` bigint unsigned NOT NULL DEFAULT 0, `name` varchar(60) NOT NULL, `code` varchar(30) NOT NULL, `driver` varchar(100) NOT NULL, `config` blob NOT NULL, `fee` bigint NOT NULL DEFAULT 0, `fee_type` enum('percent','fixed') NOT NULL DEFAULT "fixed", `fee_bearer` enum('merchant','user') NOT NULL DEFAULT "merchant", `sort` int NOT NULL DEFAULT 0, `enabled` bool NOT NULL DEFAULT 1, PRIMARY KEY (`id`), UNIQUE INDEX `paymentchannel_subsite_id_code` (`subsite_id`, `code`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "processed_events" table
CREATE TABLE `processed_events` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `event_id` bigint unsigned NOT NULL, `consumer` varchar(64) NOT NULL, `processed_at` timestamp NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `processedevent_event_id_consumer` (`event_id`, `consumer`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "cards" table
CREATE TABLE `cards` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `subsite_id` bigint unsigned NOT NULL DEFAULT 0, `version` int NOT NULL DEFAULT 0, `content` blob NOT NULL, `content_hash` varchar(64) NOT NULL, `number_hash` varchar(64) NULL, `status` enum('available','reserved','used','disabled') NOT NULL DEFAULT "available", `order_id` bigint unsigned NULL, `sku_id` bigint unsigned NULL, `import_id` bigint unsigned NULL, `card_type` varchar(20) NULL, `note` varchar(255) NULL, `owner_id` bigint unsigned NOT NULL DEFAULT 0, `draft_premium` bigint NOT NULL DEFAULT 0, `draft_cost` bigint NOT NULL DEFAULT 0, `price` bigint NULL, `locked_at` timestamp NULL, `used_at` timestamp NULL, `product_id` bigint unsigned NOT NULL, PRIMARY KEY (`id`), INDEX `card_import_id` (`import_id`), INDEX `card_order_id` (`order_id`), INDEX `card_product_id_status` (`product_id`, `status`), UNIQUE INDEX `card_subsite_id_product_id_content_hash` (`subsite_id`, `product_id`, `content_hash`), INDEX `card_subsite_id_status` (`subsite_id`, `status`), CONSTRAINT `cards_products_cards` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "orders" table
CREATE TABLE `orders` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `subsite_id` bigint unsigned NOT NULL DEFAULT 0, `version` int NOT NULL DEFAULT 0, `order_no` varchar(40) NOT NULL, `subsite_domain` varchar(255) NULL, `subsite_profit` bigint NOT NULL DEFAULT 0, `profit_eligible` bool NOT NULL DEFAULT 1, `user_id` bigint unsigned NULL, `guest_contact` varchar(150) NULL, `query_password_hash` varchar(128) NULL, `status` enum('pending_payment','paid','fulfilling','partially_delivered','delivered','completed','canceled','expired','refund_pending','refunded') NOT NULL DEFAULT "pending_payment", `total_amount` bigint NOT NULL DEFAULT 0, `cost` bigint NOT NULL DEFAULT 0, `base_currency` varchar(3) NULL, `display_currency` varchar(3) NULL, `exchange_rate` decimal(20,8) NULL, `amount_display` bigint NULL, `payment_channel` varchar(30) NULL, `contact` varchar(150) NULL, `client_ip` varchar(64) NULL, `risk_ip` varchar(80) NULL, `risk_flags` json NULL, `parent_id` bigint unsigned NULL, `escrow_id` bigint unsigned NULL, `invite_l1` bigint unsigned NULL, `invite_l2` bigint unsigned NULL, `invite_l3` bigint unsigned NULL, `extra` json NULL, `paid_at` timestamp NULL, `closed_at` timestamp NULL, `expired_at` timestamp NULL, PRIMARY KEY (`id`), INDEX `order_escrow_id` (`escrow_id`), INDEX `order_invite_l1` (`invite_l1`), UNIQUE INDEX `order_no` (`order_no`), INDEX `order_parent_id` (`parent_id`), INDEX `order_risk_ip_user_id_status` (`risk_ip`, `user_id`, `status`), INDEX `order_status_expired_at` (`status`, `expired_at`), INDEX `order_subsite_id_created_at` (`subsite_id`, `created_at`), INDEX `order_user_id_status` (`user_id`, `status`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "order_amount_lines" table
CREATE TABLE `order_amount_lines` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `item_id` bigint unsigned NULL, `type` enum('base_price','sku_adjust','member_discount','group_discount','promo_discount','coupon_discount','points_discount','subsite_markup','fee','tax','rounding_adjust') NOT NULL, `amount` bigint NOT NULL, `source_type` varchar(32) NULL, `source_id` bigint unsigned NULL, `seq` int NOT NULL DEFAULT 0, `meta` json NULL, `created_at` timestamp NOT NULL, `order_id` bigint unsigned NOT NULL, PRIMARY KEY (`id`), INDEX `orderamountline_item_id` (`item_id`), INDEX `orderamountline_order_id` (`order_id`), CONSTRAINT `order_amount_lines_orders_amount_lines` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "order_deliveries" table
CREATE TABLE `order_deliveries` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `item_id` bigint unsigned NOT NULL, `card_id` bigint unsigned NOT NULL, `delivery_token_hash` varchar(64) NOT NULL, `delivered_mode` enum('status','delete') NOT NULL, `delivered_by` bigint unsigned NOT NULL DEFAULT 0, `logistics` json NULL, `fetch_count` int NOT NULL DEFAULT 0, `delivered_at` timestamp NULL, `fetched_ip` varchar(64) NULL, `order_id` bigint unsigned NOT NULL, PRIMARY KEY (`id`), INDEX `orderdelivery_card_id` (`card_id`), INDEX `orderdelivery_order_id` (`order_id`), CONSTRAINT `order_deliveries_orders_deliveries` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "order_items" table
CREATE TABLE `order_items` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `subsite_id` bigint unsigned NOT NULL DEFAULT 0, `product_id` bigint unsigned NOT NULL, `sku_id` bigint unsigned NULL, `sku_name` varchar(100) NULL, `unit_price` bigint NOT NULL, `quantity` int NOT NULL, `amount` bigint NOT NULL, `cost` bigint NOT NULL DEFAULT 0, `fulfillment_type` enum('auto','manual','upstream') NOT NULL, `fulfillment_status` varchar(20) NOT NULL DEFAULT "pending", `commission_snapshot` json NULL, `profit_snapshot` json NULL, `order_id` bigint unsigned NOT NULL, PRIMARY KEY (`id`), INDEX `orderitem_order_id` (`order_id`), INDEX `orderitem_product_id` (`product_id`), CONSTRAINT `order_items_orders_items` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "order_status_events" table
CREATE TABLE `order_status_events` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `from_status` varchar(20) NOT NULL, `to_status` varchar(20) NOT NULL, `event` varchar(32) NOT NULL, `operator` enum('system','user','admin','worker') NOT NULL, `operator_id` bigint unsigned NULL, `reason` varchar(255) NULL, `client_ip` varchar(64) NULL, `created_at` timestamp NOT NULL, `order_id` bigint unsigned NOT NULL, PRIMARY KEY (`id`), INDEX `orderstatusevent_event` (`event`), INDEX `orderstatusevent_order_id_created_at` (`order_id`, `created_at`), CONSTRAINT `order_status_events_orders_status_events` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "payments" table
CREATE TABLE `payments` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `subsite_id` bigint unsigned NOT NULL DEFAULT 0, `channel` varchar(50) NOT NULL, `channel_order_no` varchar(80) NULL, `amount` bigint NOT NULL, `charged_amount` bigint NOT NULL DEFAULT 0, `fee` bigint NOT NULL DEFAULT 0, `status` enum('pending','success','failed') NOT NULL DEFAULT "pending", `paid_at` timestamp NULL, `raw` json NULL, `idempotency_key` varchar(64) NULL, `order_id` bigint unsigned NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `payment_channel_channel_order_no` (`channel`, `channel_order_no`), INDEX `payment_order_id` (`order_id`), INDEX `payment_status_created_at` (`status`, `created_at`), CONSTRAINT `payments_orders_payments` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "product_skus" table
CREATE TABLE `product_skus` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `subsite_id` bigint unsigned NOT NULL DEFAULT 0, `name` varchar(100) NOT NULL, `spec_values` json NOT NULL, `price` bigint NULL, `cost` bigint NULL, `stock_offset` int NOT NULL DEFAULT 0, `upstream_sku_id` varchar(64) NULL, `product_id` bigint unsigned NOT NULL, PRIMARY KEY (`id`), INDEX `productsku_product_id` (`product_id`), UNIQUE INDEX `productsku_product_id_name` (`product_id`, `name`), CONSTRAINT `product_skus_products_skus` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "refund_orders" table
CREATE TABLE `refund_orders` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `amount` bigint NOT NULL, `channel` enum('gateway','wallet','upstream') NOT NULL, `status` enum('created','processing','succeeded','failed') NOT NULL DEFAULT "created", `reason` longtext NULL, `operator_id` bigint unsigned NULL, `upstream_refund_id` varchar(64) NULL, `order_id` bigint unsigned NOT NULL, PRIMARY KEY (`id`), INDEX `refundorder_order_id` (`order_id`), INDEX `refundorder_status` (`status`), CONSTRAINT `refund_orders_orders_refunds` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
