-- Modify "orders" table
ALTER TABLE `orders` ADD COLUMN `request_fingerprint` varchar(128) NULL, ADD COLUMN `plugin_decisions` json NULL;
-- Modify "products" table
ALTER TABLE `products` ADD COLUMN `plugin_rule_revision` bigint NOT NULL DEFAULT 0;
-- Create "installed_plugins" table
CREATE TABLE `installed_plugins` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `plugin_id` varchar(64) NOT NULL, `desired_enabled` bool NOT NULL DEFAULT 0, `desired_generation` bigint NOT NULL DEFAULT 0, `observed_generation` bigint NOT NULL DEFAULT 0, `desired_digest` varchar(64) NOT NULL DEFAULT "", `observed_digest` varchar(64) NOT NULL DEFAULT "", `approved_scopes` json NULL, `block_reasons` json NULL, `current_operation_id` varchar(36) NOT NULL DEFAULT "", `uninstalled` bool NOT NULL DEFAULT 0, PRIMARY KEY (`id`), UNIQUE INDEX `plugin_id` (`plugin_id`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "plugin_data" table
CREATE TABLE `plugin_data` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `plugin_id` varchar(64) NOT NULL, `subsite_id` bigint unsigned NOT NULL, `entity_type` varchar(24) NOT NULL, `entity_id` bigint unsigned NOT NULL, `key` varchar(32) NOT NULL, `payload` blob NOT NULL, `schema_version` bigint NOT NULL DEFAULT 1, `revision` bigint NOT NULL DEFAULT 0, PRIMARY KEY (`id`), UNIQUE INDEX `plugindata_plugin_id_subsite_id_entity_type_entity_id_key` (`plugin_id`, `subsite_id`, `entity_type`, `entity_id`, `key`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "plugin_operations" table
CREATE TABLE `plugin_operations` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `operation_id` varchar(36) NOT NULL, `plugin_id` varchar(64) NOT NULL, `action` varchar(16) NOT NULL, `request_sha256` varchar(64) NOT NULL, `actor_id` bigint unsigned NOT NULL, `subsite_id` bigint unsigned NOT NULL, `expected_generation` bigint NOT NULL, `target_generation` bigint NOT NULL DEFAULT 0, `target_digest` varchar(64) NOT NULL DEFAULT "", `approved_scopes` json NULL, `phase` varchar(24) NOT NULL, `failure_code` varchar(64) NOT NULL DEFAULT "", PRIMARY KEY (`id`), UNIQUE INDEX `operation_id` (`operation_id`), INDEX `pluginoperation_plugin_id_created_at` (`plugin_id`, `created_at`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "plugin_requirements" table
CREATE TABLE `plugin_requirements` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `plugin_id` varchar(64) NOT NULL, `subsite_id` bigint unsigned NOT NULL, `product_id` bigint unsigned NOT NULL, `required` bool NOT NULL DEFAULT 0, `revision` bigint NOT NULL DEFAULT 0, PRIMARY KEY (`id`), UNIQUE INDEX `pluginrequirement_plugin_id_subsite_id_product_id` (`plugin_id`, `subsite_id`, `product_id`), INDEX `pluginrequirement_subsite_id_product_id` (`subsite_id`, `product_id`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "plugin_rule_level_refs" table
CREATE TABLE `plugin_rule_level_refs` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `plugin_id` varchar(64) NOT NULL, `subsite_id` bigint unsigned NOT NULL, `product_id` bigint unsigned NOT NULL, `level_id` bigint unsigned NOT NULL, PRIMARY KEY (`id`), INDEX `pluginrulelevelref_level_id` (`level_id`), UNIQUE INDEX `pluginrulelevelref_plugin_id_subsite_id_product_id_level_id` (`plugin_id`, `subsite_id`, `product_id`, `level_id`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
