-- Create "affiliate_commissions" table
CREATE TABLE `affiliate_commissions` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `order_id` bigint unsigned NOT NULL, `buyer_id` bigint unsigned NOT NULL, `referrer_id` bigint unsigned NOT NULL, `tier` tinyint NOT NULL, `rate` decimal(20,8) NOT NULL, `base_amount` bigint NOT NULL, `amount` bigint NOT NULL, `status` enum('pending_confirm','available','withdrawn','reversed') NOT NULL DEFAULT "pending_confirm", `available_at` datetime(3) NULL, PRIMARY KEY (`id`), INDEX `affiliatecommission_available_at` (`available_at`), UNIQUE INDEX `affiliatecommission_order_id_tier` (`order_id`, `tier`), INDEX `affiliatecommission_referrer_id_status` (`referrer_id`, `status`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "audit_logs" table
CREATE TABLE `audit_logs` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `operator_type` enum('admin','user','system') NOT NULL, `operator_id` bigint unsigned NULL, `permission_point` varchar(100) NULL, `action` varchar(10) NOT NULL, `route` varchar(255) NOT NULL, `before` json NULL, `after` json NULL, `ip` varchar(64) NULL, `user_agent` varchar(255) NULL, `created_at` datetime(3) NOT NULL, PRIMARY KEY (`id`), INDEX `auditlog_created_at` (`created_at`), INDEX `auditlog_operator_type_operator_id_created_at` (`operator_type`, `operator_id`, `created_at`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "banners" table
CREATE TABLE `banners` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `subsite_id` bigint unsigned NOT NULL DEFAULT 0, `name` varchar(100) NOT NULL, `position` enum('top','middle','bottom') NOT NULL DEFAULT "top", `title_json` json NULL, `image` varchar(255) NOT NULL, `mobile_image` varchar(255) NULL, `link_type` enum('product','category','url','ad') NOT NULL DEFAULT "url", `link_value` varchar(500) NULL, `is_active` bool NOT NULL DEFAULT 1, `start_at` datetime(3) NULL, `end_at` datetime(3) NULL, `sort` int NOT NULL DEFAULT 0, PRIMARY KEY (`id`), INDEX `banner_subsite_id_position_is_active` (`subsite_id`, `position`, `is_active`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "card_imports" table
CREATE TABLE `card_imports` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `subsite_id` bigint unsigned NOT NULL DEFAULT 0, `product_id` bigint unsigned NOT NULL, `filename` varchar(255) NOT NULL, `total` int NOT NULL DEFAULT 0, `imported` int NOT NULL DEFAULT 0, `skipped` int NOT NULL DEFAULT 0, `failed` int NOT NULL DEFAULT 0, `status` enum('pending','processing','done','failed','canceled') NOT NULL DEFAULT "pending", `operator_id` bigint unsigned NULL, PRIMARY KEY (`id`), INDEX `cardimport_product_id_created_at` (`product_id`, `created_at`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "cart_items" table
CREATE TABLE `cart_items` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `user_id` bigint unsigned NOT NULL, `product_id` bigint unsigned NOT NULL, `sku_id` bigint unsigned NOT NULL DEFAULT 0, `quantity` int NOT NULL DEFAULT 1, `fulfillment_type` enum('auto','manual','upstream') NOT NULL DEFAULT "auto", PRIMARY KEY (`id`), UNIQUE INDEX `cartitem_user_id_product_id_sku_id` (`user_id`, `product_id`, `sku_id`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "categories" table
CREATE TABLE `categories` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `subsite_id` bigint unsigned NOT NULL DEFAULT 0, `parent_id` bigint unsigned NULL, `name` varchar(60) NOT NULL, `icon` varchar(255) NULL, `hide` bool NOT NULL DEFAULT 0, `sort` int NOT NULL DEFAULT 0, `visible_subsites` json NULL, PRIMARY KEY (`id`), INDEX `category_subsite_id_parent_id` (`subsite_id`, `parent_id`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "coupons" table
CREATE TABLE `coupons` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `batch_id` varchar(40) NOT NULL DEFAULT "", `name` varchar(100) NOT NULL, `type` enum('fixed','percent') NOT NULL, `value` bigint NOT NULL, `code` varchar(40) NOT NULL, `scope` json NULL, `expire_at` datetime(3) NULL, `per_user_limit` int NOT NULL DEFAULT 1, `status` enum('unused','used','disabled') NOT NULL DEFAULT "unused", `user_id` bigint unsigned NULL, `used_at` datetime(3) NULL, `used_order_id` bigint unsigned NULL, PRIMARY KEY (`id`), UNIQUE INDEX `code` (`code`), INDEX `coupon_batch_id` (`batch_id`), INDEX `coupon_user_id_status` (`user_id`, `status`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "daily_stats" table
CREATE TABLE `daily_stats` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `subsite_id` bigint unsigned NOT NULL DEFAULT 0, `stat_date` varchar(8) NOT NULL, `metric` varchar(64) NOT NULL, `dimension_key` varchar(128) NOT NULL DEFAULT "", `value` bigint NOT NULL DEFAULT 0, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `dailystat_subsite_id_stat_date_metric_dimension_key` (`subsite_id`, `stat_date`, `metric`, `dimension_key`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "downstream_callbacks" table
CREATE TABLE `downstream_callbacks` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `supply_order_id` bigint unsigned NOT NULL, `account_id` bigint unsigned NOT NULL, `downstream_order_no` varchar(64) NOT NULL, `callback_url` varchar(500) NOT NULL, `trace_id` varchar(64) NULL, `callback_status` enum('pending','success','failed') NOT NULL DEFAULT "pending", `retry_count` int NOT NULL DEFAULT 0, `last_callback_at` datetime(3) NULL, `last_error` longtext NULL, PRIMARY KEY (`id`), INDEX `downstreamcallback_callback_status_retry_count` (`callback_status`, `retry_count`), UNIQUE INDEX `supply_order_id` (`supply_order_id`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "email_verifications" table
CREATE TABLE `email_verifications` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `email` varchar(255) NOT NULL, `user_id` bigint unsigned NULL, `purpose` enum('register','reset') NOT NULL, `code_hash` varchar(128) NOT NULL, `expires_at` datetime(3) NOT NULL, `verified_at` datetime(3) NULL, `attempt_count` int NOT NULL DEFAULT 0, `created_at` datetime(3) NOT NULL, PRIMARY KEY (`id`), INDEX `emailverification_email_purpose_created_at` (`email`, `purpose`, `created_at`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "external_identities" table
CREATE TABLE `external_identities` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `user_id` bigint unsigned NOT NULL, `provider` varchar(32) NOT NULL, `provider_user_id` varchar(128) NOT NULL, `username` varchar(120) NULL, `avatar_url` varchar(255) NULL, `auth_at` datetime(3) NULL, PRIMARY KEY (`id`), UNIQUE INDEX `externalidentity_provider_provider_user_id` (`provider`, `provider_user_id`), INDEX `externalidentity_user_id` (`user_id`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "flash_sales" table
CREATE TABLE `flash_sales` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `subsite_id` bigint unsigned NOT NULL DEFAULT 0, `product_id` bigint unsigned NOT NULL, `sku_id` bigint unsigned NOT NULL DEFAULT 0, `flash_price` bigint NOT NULL, `start_at` datetime(3) NOT NULL, `end_at` datetime(3) NOT NULL, `limit_qty` int NOT NULL, `sold_qty` int NOT NULL DEFAULT 0, `per_user_limit` int NOT NULL DEFAULT 1, PRIMARY KEY (`id`), INDEX `flashsale_end_at` (`end_at`), INDEX `flashsale_product_id_sku_id` (`product_id`, `sku_id`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "giftcards" table
CREATE TABLE `giftcards` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `batch_id` bigint unsigned NOT NULL, `code` blob NOT NULL, `code_hash` varchar(64) NOT NULL, `amount` bigint NOT NULL, `currency` varchar(3) NOT NULL DEFAULT "CNY", `status` enum('unused','used','disabled') NOT NULL DEFAULT "unused", `used_by` bigint unsigned NULL, `used_at` datetime(3) NULL, `expires_at` datetime(3) NULL, PRIMARY KEY (`id`), UNIQUE INDEX `code_hash` (`code_hash`), INDEX `giftcard_batch_id` (`batch_id`), INDEX `giftcard_status` (`status`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "giftcard_batches" table
CREATE TABLE `giftcard_batches` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `batch_no` varchar(40) NOT NULL, `name` varchar(100) NOT NULL, `amount` bigint NOT NULL, `quantity` int NOT NULL, `operator_id` bigint unsigned NULL, PRIMARY KEY (`id`), UNIQUE INDEX `batch_no` (`batch_no`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "media" table
CREATE TABLE `media` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `category_id` bigint unsigned NULL, `path` varchar(500) NOT NULL, `name` varchar(255) NOT NULL, `mime` varchar(60) NOT NULL, `size` bigint NOT NULL, `width` int NULL, `height` int NULL, `sha256` varchar(64) NULL, `storage` enum('local','s3') NOT NULL DEFAULT "local", `ref_count` int NOT NULL DEFAULT 0, `uploader_id` bigint unsigned NULL, PRIMARY KEY (`id`), INDEX `media_category_id` (`category_id`), INDEX `media_sha256` (`sha256`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "media_categories" table
CREATE TABLE `media_categories` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `parent_id` bigint unsigned NULL, `name` varchar(60) NOT NULL, `sort` int NOT NULL DEFAULT 0, PRIMARY KEY (`id`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "member_levels" table
CREATE TABLE `member_levels` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `name` varchar(60) NOT NULL, `logo` varchar(255) NULL, `badge_color` varchar(20) NULL, `threshold_type` enum('recharge','consume','both_and','both_or') NOT NULL DEFAULT "recharge", `threshold_recharge` bigint NOT NULL DEFAULT 0, `threshold_consume` bigint NOT NULL DEFAULT 0, `discount` int NOT NULL DEFAULT 0, `points_rule` json NULL, `sort` int NOT NULL DEFAULT 0, `enabled` bool NOT NULL DEFAULT 1, PRIMARY KEY (`id`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "member_product_groups" table
CREATE TABLE `member_product_groups` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `subsite_id` bigint unsigned NOT NULL DEFAULT 0, `name` varchar(60) NOT NULL, `product_ids` json NOT NULL, `discount` int NOT NULL DEFAULT 0, `stack_member` bool NOT NULL DEFAULT 0, `stack_coupon` bool NOT NULL DEFAULT 0, `badge_style` varchar(60) NULL, PRIMARY KEY (`id`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "notifications" table
CREATE TABLE `notifications` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `user_id` bigint unsigned NOT NULL, `title` varchar(200) NOT NULL, `content` longtext NOT NULL, `read_at` datetime(3) NULL, `source_type` varchar(40) NULL, `source_id` bigint unsigned NULL, `created_at` datetime(3) NOT NULL, PRIMARY KEY (`id`), INDEX `notification_user_id_read_at_created_at` (`user_id`, `read_at`, `created_at`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "notification_logs" table
CREATE TABLE `notification_logs` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `event_type` varchar(64) NOT NULL, `biz_type` varchar(40) NULL, `biz_id` bigint unsigned NULL, `channel` enum('email','sms','inbox','telegram') NOT NULL, `recipient` varchar(255) NOT NULL, `locale` varchar(10) NOT NULL DEFAULT "zh_CN", `subject` varchar(255) NULL, `body` longtext NULL, `status` enum('pending','sent','failed','skipped') NOT NULL DEFAULT "pending", `error_message` longtext NULL, `variables` json NULL, `created_at` datetime(3) NOT NULL, PRIMARY KEY (`id`), INDEX `notificationlog_event_type_created_at` (`event_type`, `created_at`), INDEX `notificationlog_status_created_at` (`status`, `created_at`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "notify_templates" table
CREATE TABLE `notify_templates` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `event_type` varchar(64) NOT NULL, `channel` enum('email','sms','inbox','telegram') NOT NULL, `locale` varchar(10) NOT NULL DEFAULT "zh_CN", `subject_tpl` varchar(255) NOT NULL, `body_tpl` longtext NOT NULL, `enabled` bool NOT NULL DEFAULT 1, PRIMARY KEY (`id`), UNIQUE INDEX `notifytemplate_event_type_channel_locale` (`event_type`, `channel`, `locale`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "point_accounts" table
CREATE TABLE `point_accounts` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `user_id` bigint unsigned NOT NULL, `balance` bigint NOT NULL DEFAULT 0, `version` int NOT NULL DEFAULT 0, `updated_at` datetime(3) NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `user_id` (`user_id`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "point_transactions" table
CREATE TABLE `point_transactions` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `user_id` bigint unsigned NOT NULL, `direction` varchar(8) NOT NULL, `type` varchar(40) NOT NULL, `amount` bigint NOT NULL, `balance_before` bigint NOT NULL, `balance_after` bigint NOT NULL, `reference` varchar(120) NOT NULL, `order_id` bigint unsigned NULL, `remark` varchar(255) NULL, `created_at` datetime(3) NOT NULL, PRIMARY KEY (`id`), INDEX `pointtransaction_user_id_created_at` (`user_id`, `created_at`), UNIQUE INDEX `reference` (`reference`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "posts" table
CREATE TABLE `posts` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `subsite_id` bigint unsigned NOT NULL DEFAULT 0, `slug` varchar(120) NOT NULL, `type` enum('blog','notice') NOT NULL DEFAULT "blog", `title_json` json NOT NULL, `summary_json` json NULL, `content_json` longtext NOT NULL, `thumbnail` varchar(255) NULL, `category_id` bigint unsigned NULL, `is_published` bool NOT NULL DEFAULT 0, `published_at` datetime(3) NULL, PRIMARY KEY (`id`), UNIQUE INDEX `post_subsite_id_slug` (`subsite_id`, `slug`), INDEX `post_type_is_published` (`type`, `is_published`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "post_categories" table
CREATE TABLE `post_categories` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `name` varchar(60) NOT NULL, `slug` varchar(80) NOT NULL, `sort` int NOT NULL DEFAULT 0, PRIMARY KEY (`id`), UNIQUE INDEX `slug` (`slug`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "procurement_items" table
CREATE TABLE `procurement_items` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `procurement_id` bigint unsigned NOT NULL, `upstream_sku` varchar(64) NOT NULL DEFAULT "", `quantity` int NOT NULL, `unit_cost` bigint NOT NULL DEFAULT 0, `received_content` blob NULL, PRIMARY KEY (`id`), INDEX `procurementitem_procurement_id` (`procurement_id`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "procurement_orders" table
CREATE TABLE `procurement_orders` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `order_item_id` bigint unsigned NOT NULL, `connection_id` bigint unsigned NOT NULL, `upstream_order_id` varchar(80) NULL, `status` enum('pending','submitted','polling','fulfilled','rejected','refunding','refunded','manual','failed') NOT NULL DEFAULT "pending", `fail_strategy` enum('auto_refund','manual') NOT NULL DEFAULT "auto_refund", `retry_count` int NOT NULL DEFAULT 0, `next_retry_at` datetime(3) NULL, `last_poll_at` datetime(3) NULL, `dedupe_key` varchar(120) NOT NULL, `trace_id` varchar(64) NULL, PRIMARY KEY (`id`), UNIQUE INDEX `dedupe_key` (`dedupe_key`), INDEX `procurementorder_connection_id_upstream_order_id` (`connection_id`, `upstream_order_id`), INDEX `procurementorder_order_item_id` (`order_item_id`), INDEX `procurementorder_status_last_poll_at` (`status`, `last_poll_at`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "product_controls" table
CREATE TABLE `product_controls` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `subsite_id` bigint unsigned NOT NULL DEFAULT 0, `product_id` bigint unsigned NOT NULL, `name` varchar(60) NOT NULL, `type` enum('text','password','select','number','checkbox','radio') NOT NULL, `required` bool NOT NULL DEFAULT 0, `options` json NULL, `sort` int NOT NULL DEFAULT 0, PRIMARY KEY (`id`), INDEX `productcontrol_product_id` (`product_id`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "promotions" table
CREATE TABLE `promotions` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `subsite_id` bigint unsigned NOT NULL DEFAULT 0, `name` varchar(100) NOT NULL, `scope` json NOT NULL, `type` enum('fixed','percent','special_price') NOT NULL, `threshold` bigint NOT NULL DEFAULT 0, `discount` bigint NOT NULL DEFAULT 0, `special_price` bigint NOT NULL DEFAULT 0, `start_at` datetime(3) NOT NULL, `end_at` datetime(3) NOT NULL, `enabled` bool NOT NULL DEFAULT 1, PRIMARY KEY (`id`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "recharge_orders" table
CREATE TABLE `recharge_orders` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `user_id` bigint unsigned NOT NULL, `amount` bigint NOT NULL, `gift_amount` bigint NOT NULL DEFAULT 0, `gift_points` int NOT NULL DEFAULT 0, `target` enum('balance','supply') NOT NULL DEFAULT "balance", `status` enum('pending','success','failed','expired') NOT NULL DEFAULT "pending", `payment_id` bigint unsigned NULL, `paid_at` datetime(3) NULL, PRIMARY KEY (`id`), INDEX `rechargeorder_status` (`status`), INDEX `rechargeorder_user_id_created_at` (`user_id`, `created_at`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "reconciliation_items" table
CREATE TABLE `reconciliation_items` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `job_id` bigint unsigned NOT NULL, `procurement_order_id` bigint unsigned NULL, `local_order_no` varchar(64) NULL, `upstream_order_no` varchar(80) NULL, `status` enum('matched','mismatched','local_only','upstream_only') NOT NULL, `diff_json` json NULL, `created_at` datetime(3) NOT NULL, PRIMARY KEY (`id`), INDEX `reconciliationitem_job_id_status` (`job_id`, `status`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "reconciliation_jobs" table
CREATE TABLE `reconciliation_jobs` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `connection_id` bigint unsigned NOT NULL, `type` varchar(40) NOT NULL DEFAULT "orders", `status` enum('pending','processing','done','failed') NOT NULL DEFAULT "pending", `time_range_start` datetime(3) NOT NULL, `time_range_end` datetime(3) NOT NULL, `total_count` int NOT NULL DEFAULT 0, `matched_count` int NOT NULL DEFAULT 0, `mismatched_count` int NOT NULL DEFAULT 0, `result_json` json NULL, PRIMARY KEY (`id`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "reseller_balance_accounts" table
CREATE TABLE `reseller_balance_accounts` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `subsite_id` bigint unsigned NOT NULL, `currency` varchar(3) NOT NULL DEFAULT "CNY", `available` bigint NOT NULL DEFAULT 0, `locked` bigint NOT NULL DEFAULT 0, `negative` bigint NOT NULL DEFAULT 0, `last_entry_id` bigint unsigned NOT NULL DEFAULT 0, `updated_at` datetime(3) NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `subsite_id` (`subsite_id`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "reseller_ledger_entries" table
CREATE TABLE `reseller_ledger_entries` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `subsite_id` bigint unsigned NOT NULL, `order_id` bigint unsigned NULL, `type` enum('order_profit','refund_deduct','withdraw_lock','withdraw_paid','manual_adjust') NOT NULL, `amount` bigint NOT NULL, `currency` varchar(3) NOT NULL DEFAULT "CNY", `status` enum('pending','available','locked','withdrawn') NOT NULL DEFAULT "pending", `available_at` datetime(3) NULL, `idempotency_key` varchar(120) NOT NULL, `metadata_json` json NULL, `remark` varchar(255) NULL, `created_at` datetime(3) NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `idempotency_key` (`idempotency_key`), INDEX `resellerledgerentry_available_at` (`available_at`), INDEX `resellerledgerentry_subsite_id_status` (`subsite_id`, `status`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "reseller_pricings" table
CREATE TABLE `reseller_pricings` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `subsite_id` bigint unsigned NOT NULL, `product_id` bigint unsigned NOT NULL, `sku_id` bigint unsigned NOT NULL DEFAULT 0, `mode` enum('inherit','markup_percent','fixed_markup','fixed_price') NOT NULL DEFAULT "inherit", `value` bigint NOT NULL DEFAULT 0, PRIMARY KEY (`id`), UNIQUE INDEX `resellerpricing_subsite_id_product_id_sku_id` (`subsite_id`, `product_id`, `sku_id`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "reseller_profiles" table
CREATE TABLE `reseller_profiles` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `user_id` bigint unsigned NOT NULL, `status` enum('applying','approved','rejected') NOT NULL DEFAULT "applying", `apply_reason` longtext NULL, `reject_reason` varchar(255) NULL, `level` tinyint NOT NULL DEFAULT 1, `default_markup_percent` decimal(20,8) NOT NULL DEFAULT 0.00000000, `max_markup_percent` decimal(20,8) NOT NULL DEFAULT 100.00000000, `confirm_days` int NOT NULL DEFAULT 7, `reviewed_by` bigint unsigned NULL, `reviewed_at` datetime(3) NULL, PRIMARY KEY (`id`), UNIQUE INDEX `user_id` (`user_id`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "reseller_related_accounts" table
CREATE TABLE `reseller_related_accounts` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `reseller_id` bigint unsigned NOT NULL, `user_id` bigint unsigned NOT NULL, `relation_type` varchar(40) NOT NULL, `source` varchar(120) NULL, `status` enum('active','ignored') NOT NULL DEFAULT "active", PRIMARY KEY (`id`), UNIQUE INDEX `resellerrelatedaccount_reseller_id_user_id_relation_type` (`reseller_id`, `user_id`, `relation_type`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "reseller_sites" table
CREATE TABLE `reseller_sites` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `profile_id` bigint unsigned NOT NULL, `domain` varchar(255) NOT NULL, `type` enum('main','custom') NOT NULL DEFAULT "custom", `verification_token` varchar(64) NOT NULL, `verification_status` enum('pending','verified','failed') NOT NULL DEFAULT "pending", `is_primary` bool NOT NULL DEFAULT 0, `site_name` varchar(100) NULL, `logo` varchar(255) NULL, `favicon` varchar(255) NULL, `announcement_json` json NULL, `support_json` json NULL, `status` enum('active','disabled') NOT NULL DEFAULT "active", PRIMARY KEY (`id`), UNIQUE INDEX `domain` (`domain`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "reviews" table
CREATE TABLE `reviews` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `subsite_id` bigint unsigned NOT NULL DEFAULT 0, `product_id` bigint unsigned NOT NULL, `user_id` bigint unsigned NOT NULL, `order_id` bigint unsigned NOT NULL, `rating` tinyint NOT NULL, `content` longtext NOT NULL, `status` enum('pending','approved','rejected') NOT NULL DEFAULT "pending", PRIMARY KEY (`id`), UNIQUE INDEX `review_order_id` (`order_id`), INDEX `review_product_id_status` (`product_id`, `status`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "risk_lock_keys" table
CREATE TABLE `risk_lock_keys` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `key_hash` varchar(128) NOT NULL, `expires_at` datetime(3) NOT NULL, `created_at` datetime(3) NOT NULL, PRIMARY KEY (`id`), INDEX `risklockkey_expires_at` (`expires_at`), UNIQUE INDEX `risklockkey_key_hash` (`key_hash`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "security_audit_logs" table
CREATE TABLE `security_audit_logs` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `actor_type` enum('admin','user','guest','system') NOT NULL, `actor_id` bigint unsigned NULL, `action` varchar(255) NOT NULL, `ip` varchar(64) NULL, `metadata` json NULL, `created_at` datetime(3) NOT NULL, PRIMARY KEY (`id`), INDEX `securityauditlog_action_created_at` (`action`, `created_at`), INDEX `securityauditlog_actor_type_actor_id_created_at` (`actor_type`, `actor_id`, `created_at`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "sessions" table
CREATE TABLE `sessions` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `realm` enum('admin','user') NOT NULL, `user_id` bigint unsigned NOT NULL, `refresh_token_hash` varchar(128) NOT NULL, `device` varchar(120) NULL, `ip` varchar(64) NULL, `user_agent` varchar(255) NULL, `expires_at` datetime(3) NOT NULL, `revoked_at` datetime(3) NULL, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, PRIMARY KEY (`id`), INDEX `session_expires_at` (`expires_at`), INDEX `session_realm_user_id` (`realm`, `user_id`), UNIQUE INDEX `session_refresh_token_hash` (`refresh_token_hash`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "supplier_accounts" table
CREATE TABLE `supplier_accounts` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `name` varchar(100) NOT NULL, `api_key` varchar(64) NOT NULL, `api_secret` blob NOT NULL, `contact` varchar(255) NULL, `status` enum('applying','approved','disabled') NOT NULL DEFAULT "applying", `balance_cache` bigint NOT NULL DEFAULT 0, `notify_url` varchar(500) NULL, `reviewed_at` datetime(3) NULL, PRIMARY KEY (`id`), UNIQUE INDEX `api_key` (`api_key`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "supplier_ledger_entries" table
CREATE TABLE `supplier_ledger_entries` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `account_id` bigint unsigned NOT NULL, `supply_order_id` bigint unsigned NULL, `type` varchar(40) NOT NULL, `amount` bigint NOT NULL, `currency` varchar(3) NOT NULL DEFAULT "CNY", `reference` varchar(120) NOT NULL, `remark` varchar(255) NULL, `created_at` datetime(3) NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `reference` (`reference`), INDEX `supplierledgerentry_account_id_created_at` (`account_id`, `created_at`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "supplier_product_prices" table
CREATE TABLE `supplier_product_prices` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `supplier_account_id` bigint unsigned NOT NULL, `product_id` bigint unsigned NOT NULL, `sku_id` bigint unsigned NOT NULL DEFAULT 0, `price` bigint NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `supplierproductprice_supplier_account_id_product_id_sku_id` (`supplier_account_id`, `product_id`, `sku_id`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "supply_connections" table
CREATE TABLE `supply_connections` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `name` varchar(100) NOT NULL, `driver` varchar(30) NOT NULL, `base_url` varchar(255) NOT NULL, `credentials` blob NOT NULL, `status` enum('active','disabled') NOT NULL DEFAULT "active", `callback_url` varchar(500) NULL, `retry_max` int NOT NULL DEFAULT 5, `retry_intervals` varchar(200) NOT NULL DEFAULT "[30,60,300]", `exchange_rate` decimal(20,8) NOT NULL DEFAULT 1.00000000, `price_markup_percent` decimal(20,8) NOT NULL DEFAULT 0.00000000, `price_rounding_mode` enum('none','ceil_int','ceil_tenth') NOT NULL DEFAULT "none", `auto_sync_price` bool NOT NULL DEFAULT 1, `stock_mode` enum('real','plenty') NOT NULL DEFAULT "real", `settings` json NULL, `last_ping_at` datetime(3) NULL, `last_ping_ok` bool NOT NULL DEFAULT 0, `last_synced_at` datetime(3) NULL, `last_error` longtext NULL, `balance_cache` bigint NOT NULL DEFAULT 0, PRIMARY KEY (`id`), INDEX `supplyconnection_last_synced_at` (`last_synced_at`), INDEX `supplyconnection_status_driver` (`status`, `driver`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "supply_mappings" table
CREATE TABLE `supply_mappings` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `connection_id` bigint unsigned NOT NULL, `upstream_category` varchar(128) NULL, `local_category_id` bigint unsigned NULL, `upstream_product` varchar(128) NOT NULL, `local_product_id` bigint unsigned NULL, `upstream_sku` varchar(64) NOT NULL DEFAULT "", `local_sku_id` bigint unsigned NULL, `up_stock` int NOT NULL DEFAULT 0, `pricing_override` json NULL, PRIMARY KEY (`id`), UNIQUE INDEX `supplymapping_connection_id_upstream_product_upstream_sku` (`connection_id`, `upstream_product`, `upstream_sku`), INDEX `supplymapping_local_product_id` (`local_product_id`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "supply_nonces" table
CREATE TABLE `supply_nonces` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `key` varchar(64) NOT NULL, `nonce` varchar(64) NOT NULL, `expires_at` datetime(3) NOT NULL, `created_at` datetime(3) NOT NULL, PRIMARY KEY (`id`), INDEX `supplynonce_expires_at` (`expires_at`), UNIQUE INDEX `supplynonce_key_nonce` (`key`, `nonce`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "supply_orders" table
CREATE TABLE `supply_orders` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `account_id` bigint unsigned NOT NULL, `downstream_order_no` varchar(64) NOT NULL, `items` json NOT NULL, `amount` bigint NOT NULL, `status` enum('pending','paid','fulfilling','fulfilled','rejected','refunded') NOT NULL DEFAULT "pending", `local_order_id` bigint unsigned NULL, `paid_at` datetime(3) NULL, `fulfilled_at` datetime(3) NULL, PRIMARY KEY (`id`), UNIQUE INDEX `downstream_order_no` (`downstream_order_no`), INDEX `supplyorder_account_id_created_at` (`account_id`, `created_at`), INDEX `supplyorder_status` (`status`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "supply_sync_tasks" table
CREATE TABLE `supply_sync_tasks` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `connection_id` bigint unsigned NOT NULL, `mode` varchar(20) NOT NULL, `scope` varchar(60) NULL, `force_reprice` bool NOT NULL DEFAULT 0, `status` enum('pending','processing','done','failed','canceled') NOT NULL DEFAULT "pending", `total_count` int NOT NULL DEFAULT 0, `processed_count` int NOT NULL DEFAULT 0, `created_count` int NOT NULL DEFAULT 0, `updated_count` int NOT NULL DEFAULT 0, `price_updated_count` int NOT NULL DEFAULT 0, `manual_skipped_count` int NOT NULL DEFAULT 0, `hidden_count` int NOT NULL DEFAULT 0, `deleted_count` int NOT NULL DEFAULT 0, `error_code` varchar(64) NULL, `error_context` longtext NULL, `started_at` datetime(3) NULL, `heartbeat_at` datetime(3) NULL, `current_stage` varchar(60) NULL, `current_page` int NOT NULL DEFAULT 0, `cancel_requested_at` datetime(3) NULL, `worker_version` varchar(40) NULL, `finished_at` datetime(3) NULL, PRIMARY KEY (`id`), INDEX `supplysynctask_connection_id_created_at` (`connection_id`, `created_at`), INDEX `supplysynctask_status` (`status`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "tags" table
CREATE TABLE `tags` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `name` varchar(60) NOT NULL, `slug` varchar(80) NOT NULL, `icon` varchar(255) NULL, `color` varchar(20) NULL, `position` enum('top_right','before_title','bottom_right') NOT NULL DEFAULT "top_right", `hide` bool NOT NULL DEFAULT 0, PRIMARY KEY (`id`), UNIQUE INDEX `slug` (`slug`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "tickets" table
CREATE TABLE `tickets` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `ticket_no` varchar(40) NOT NULL, `user_id` bigint unsigned NULL, `guest_contact` varchar(150) NULL, `type` enum('presale','aftersale') NOT NULL, `priority` enum('low','normal','high','urgent_paid') NOT NULL DEFAULT "normal", `order_id` bigint unsigned NULL, `product_id` bigint unsigned NULL, `status` enum('open','processing','resolved','closed') NOT NULL DEFAULT "open", `first_reply_at` datetime(3) NULL, `sla_due_at` datetime(3) NULL, `satisfaction` tinyint NULL, PRIMARY KEY (`id`), UNIQUE INDEX `ticket_no` (`ticket_no`), INDEX `ticket_status_priority_created_at` (`status`, `priority`, `created_at`), INDEX `ticket_user_id_created_at` (`user_id`, `created_at`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "ticket_messages" table
CREATE TABLE `ticket_messages` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `ticket_id` bigint unsigned NOT NULL, `sender_type` enum('user','admin','system') NOT NULL, `sender_id` bigint unsigned NULL, `content` longtext NOT NULL, `attachments` json NULL, `is_internal` bool NOT NULL DEFAULT 0, `created_at` datetime(3) NOT NULL, PRIMARY KEY (`id`), INDEX `ticketmessage_ticket_id_created_at` (`ticket_id`, `created_at`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "user_groups" table
CREATE TABLE `user_groups` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `code` varchar(60) NOT NULL, `name` varchar(60) NOT NULL, `level_id` bigint unsigned NULL, PRIMARY KEY (`id`), UNIQUE INDEX `code` (`code`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "v1id_maps" table
CREATE TABLE `v1id_maps` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `table_name` varchar(64) NOT NULL, `old_id` bigint unsigned NOT NULL, `new_id` bigint unsigned NOT NULL, `created_at` datetime(3) NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `v1idmap_table_name_old_id` (`table_name`, `old_id`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "virtual_reviews" table
CREATE TABLE `virtual_reviews` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `product_id` bigint unsigned NOT NULL, `nickname` varchar(60) NOT NULL, `content` longtext NOT NULL, `rating` tinyint NOT NULL DEFAULT 5, `sort` int NOT NULL DEFAULT 0, `created_at` datetime(3) NOT NULL, PRIMARY KEY (`id`), INDEX `virtualreview_product_id` (`product_id`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "visit_logs" table
CREATE TABLE `visit_logs` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `subsite_id` bigint unsigned NOT NULL DEFAULT 0, `stat_date` varchar(8) NOT NULL, `stat_hour` tinyint NOT NULL, `path` varchar(255) NOT NULL, `pv` bigint NOT NULL DEFAULT 0, `uv` bigint NOT NULL DEFAULT 0, PRIMARY KEY (`id`), UNIQUE INDEX `visitlog_subsite_id_stat_date_stat_hour_path` (`subsite_id`, `stat_date`, `stat_hour`, `path`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "withdrawals" table
CREATE TABLE `withdrawals` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `user_id` bigint unsigned NOT NULL, `amount` bigint NOT NULL, `fee` bigint NOT NULL DEFAULT 0, `method` json NOT NULL, `status` enum('pending','approved','paid','rejected') NOT NULL DEFAULT "pending", `reviewed_by` bigint unsigned NULL, `reject_reason` varchar(255) NULL, `paid_at` datetime(3) NULL, `reviewed_at` datetime(3) NULL, PRIMARY KEY (`id`), INDEX `withdrawal_status_created_at` (`status`, `created_at`), INDEX `withdrawal_user_id_status` (`user_id`, `status`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
