-- Create "lottery_accounts" table
CREATE TABLE `lottery_accounts` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `subsite_id` bigint unsigned NOT NULL DEFAULT 0, `activity_id` bigint unsigned NOT NULL, `user_id` bigint unsigned NOT NULL, `period` varchar(16) NOT NULL, `balance` int NOT NULL DEFAULT 0, `auto_granted` bool NOT NULL DEFAULT 0, `version` int NOT NULL DEFAULT 0, PRIMARY KEY (`id`), UNIQUE INDEX `lotteryaccount_subsite_id_activity_id_user_id_period` (`subsite_id`, `activity_id`, `user_id`, `period`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "lottery_activities" table
CREATE TABLE `lottery_activities` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `subsite_id` bigint unsigned NOT NULL DEFAULT 0, `name` varchar(100) NOT NULL, `description` longtext NOT NULL, `image` varchar(2048) NOT NULL DEFAULT "", `status` varchar(20) NOT NULL DEFAULT "draft", `start_at` datetime(3) NOT NULL, `end_at` datetime(3) NOT NULL, `timezone` varchar(64) NOT NULL DEFAULT "Asia/Shanghai", `chance_mode` varchar(16) NOT NULL DEFAULT "once", `chance_count` int NOT NULL DEFAULT 3, `revision` int NOT NULL DEFAULT 1, `published` bool NOT NULL DEFAULT 0, PRIMARY KEY (`id`), INDEX `lotteryactivity_subsite_id_status` (`subsite_id`, `status`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "lottery_chance_logs" table
CREATE TABLE `lottery_chance_logs` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `subsite_id` bigint unsigned NOT NULL DEFAULT 0, `activity_id` bigint unsigned NOT NULL, `user_id` bigint unsigned NOT NULL, `period` varchar(16) NOT NULL, `amount` int NOT NULL, `kind` varchar(16) NOT NULL, `request_key` varchar(80) NOT NULL, `remark` varchar(500) NOT NULL DEFAULT "", `admin_id` bigint unsigned NOT NULL DEFAULT 0, PRIMARY KEY (`id`), UNIQUE INDEX `lotterychancelog_subsite_id_activity_id_user_id_request_key` (`subsite_id`, `activity_id`, `user_id`, `request_key`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "lottery_draws" table
CREATE TABLE `lottery_draws` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `subsite_id` bigint unsigned NOT NULL DEFAULT 0, `activity_id` bigint unsigned NOT NULL, `user_id` bigint unsigned NOT NULL, `draw_no` varchar(40) NOT NULL, `request_key` varchar(64) NOT NULL, `activity_name` varchar(100) NOT NULL, `prize_name` varchar(100) NOT NULL DEFAULT "", `mode` varchar(16) NOT NULL DEFAULT "", `status` varchar(20) NOT NULL, `prize_id` bigint unsigned NOT NULL DEFAULT 0, `product_id` bigint unsigned NOT NULL DEFAULT 0, `sku_id` bigint unsigned NOT NULL DEFAULT 0, `card_id` bigint unsigned NULL, `cost` bigint NOT NULL DEFAULT 0, `revision` int NOT NULL, `rule_snapshot` json NULL, `content` blob NULL, `delivered_at` datetime(3) NULL, `admin_id` bigint unsigned NOT NULL DEFAULT 0, `remark` varchar(500) NOT NULL DEFAULT "", PRIMARY KEY (`id`), UNIQUE INDEX `draw_no` (`draw_no`), UNIQUE INDEX `lotterydraw_card_id` (`card_id`), INDEX `lotterydraw_product_id_sku_id` (`product_id`, `sku_id`), INDEX `lotterydraw_subsite_id_activity_id_status` (`subsite_id`, `activity_id`, `status`), UNIQUE INDEX `lotterydraw_subsite_id_activity_id_user_id_request_key` (`subsite_id`, `activity_id`, `user_id`, `request_key`), INDEX `lotterydraw_subsite_id_user_id_id` (`subsite_id`, `user_id`, `id`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "lottery_prizes" table
CREATE TABLE `lottery_prizes` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `subsite_id` bigint unsigned NOT NULL DEFAULT 0, `activity_id` bigint unsigned NOT NULL, `name` varchar(100) NOT NULL, `image` varchar(2048) NOT NULL DEFAULT "", `mode` varchar(16) NOT NULL, `product_id` bigint unsigned NOT NULL DEFAULT 0, `sku_id` bigint unsigned NOT NULL DEFAULT 0, `probability` int NOT NULL DEFAULT 0, `quantity` int NOT NULL DEFAULT 1, `issued` int NOT NULL DEFAULT 0, `sort` int NOT NULL DEFAULT 0, `enabled` bool NOT NULL DEFAULT 1, `content` blob NULL, PRIMARY KEY (`id`), INDEX `lotteryprize_product_id_sku_id` (`product_id`, `sku_id`), INDEX `lotteryprize_subsite_id_activity_id_enabled` (`subsite_id`, `activity_id`, `enabled`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "lottery_revisions" table
CREATE TABLE `lottery_revisions` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL, `subsite_id` bigint unsigned NOT NULL DEFAULT 0, `activity_id` bigint unsigned NOT NULL, `revision` int NOT NULL, `admin_id` bigint unsigned NOT NULL, `snapshot` json NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `lotteryrevision_subsite_id_activity_id_revision` (`subsite_id`, `activity_id`, `revision`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
