// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: storefront/v1/config.proto

package storefrontv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PublicConfig 公开配置条目列表。
type PublicConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*PublicConfigEntry   `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicConfig) Reset() {
	*x = PublicConfig{}
	mi := &file_storefront_v1_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicConfig) ProtoMessage() {}

func (x *PublicConfig) ProtoReflect() protoreflect.Message {
	mi := &file_storefront_v1_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicConfig.ProtoReflect.Descriptor instead.
func (*PublicConfig) Descriptor() ([]byte, []int) {
	return file_storefront_v1_config_proto_rawDescGZIP(), []int{0}
}

func (x *PublicConfig) GetEntries() []*PublicConfigEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// PublicConfigEntry 单键（key 形如 "site.name"；value 为 JSON 文档字符串）。
type PublicConfigEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ValueJson     string                 `protobuf:"bytes,2,opt,name=value_json,json=valueJson,proto3" json:"value_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicConfigEntry) Reset() {
	*x = PublicConfigEntry{}
	mi := &file_storefront_v1_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicConfigEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicConfigEntry) ProtoMessage() {}

func (x *PublicConfigEntry) ProtoReflect() protoreflect.Message {
	mi := &file_storefront_v1_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicConfigEntry.ProtoReflect.Descriptor instead.
func (*PublicConfigEntry) Descriptor() ([]byte, []int) {
	return file_storefront_v1_config_proto_rawDescGZIP(), []int{1}
}

func (x *PublicConfigEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PublicConfigEntry) GetValueJson() string {
	if x != nil {
		return x.ValueJson
	}
	return ""
}

// Currencies 货币列表。
type Currencies struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currencies    []*Currency            `protobuf:"bytes,1,rep,name=currencies,proto3" json:"currencies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Currencies) Reset() {
	*x = Currencies{}
	mi := &file_storefront_v1_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Currencies) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Currencies) ProtoMessage() {}

func (x *Currencies) ProtoReflect() protoreflect.Message {
	mi := &file_storefront_v1_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Currencies.ProtoReflect.Descriptor instead.
func (*Currencies) Descriptor() ([]byte, []int) {
	return file_storefront_v1_config_proto_rawDescGZIP(), []int{2}
}

func (x *Currencies) GetCurrencies() []*Currency {
	if x != nil {
		return x.Currencies
	}
	return nil
}

// Currency 货币（rate 为 decimal 字符串——前端 decimal 换算，杜绝浮点误差入口）。
type Currency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Position      string                 `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Precision     int32                  `protobuf:"varint,4,opt,name=precision,proto3" json:"precision,omitempty"`
	RateJson      string                 `protobuf:"bytes,5,opt,name=rate_json,json=rateJson,proto3" json:"rate_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Currency) Reset() {
	*x = Currency{}
	mi := &file_storefront_v1_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Currency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Currency) ProtoMessage() {}

func (x *Currency) ProtoReflect() protoreflect.Message {
	mi := &file_storefront_v1_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Currency.ProtoReflect.Descriptor instead.
func (*Currency) Descriptor() ([]byte, []int) {
	return file_storefront_v1_config_proto_rawDescGZIP(), []int{3}
}

func (x *Currency) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Currency) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Currency) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *Currency) GetPrecision() int32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

func (x *Currency) GetRateJson() string {
	if x != nil {
		return x.RateJson
	}
	return ""
}

var File_storefront_v1_config_proto protoreflect.FileDescriptor

const file_storefront_v1_config_proto_rawDesc = "" +
	"\n" +
	"\x1astorefront/v1/config.proto\x12\x17zcard.api.storefront.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"T\n" +
	"\fPublicConfig\x12D\n" +
	"\aentries\x18\x01 \x03(\v2*.zcard.api.storefront.v1.PublicConfigEntryR\aentries\"D\n" +
	"\x11PublicConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1d\n" +
	"\n" +
	"value_json\x18\x02 \x01(\tR\tvalueJson\"O\n" +
	"\n" +
	"Currencies\x12A\n" +
	"\n" +
	"currencies\x18\x01 \x03(\v2!.zcard.api.storefront.v1.CurrencyR\n" +
	"currencies\"\x8d\x01\n" +
	"\bCurrency\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\tR\bposition\x12\x1c\n" +
	"\tprecision\x18\x04 \x01(\x05R\tprecision\x12\x1b\n" +
	"\trate_json\x18\x05 \x01(\tR\brateJson2\x84\x02\n" +
	"\x17StorefrontConfigService\x12s\n" +
	"\x0fGetPublicConfig\x12\x16.google.protobuf.Empty\x1a%.zcard.api.storefront.v1.PublicConfig\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/storefront/config\x12t\n" +
	"\x0eListCurrencies\x12\x16.google.protobuf.Empty\x1a#.zcard.api.storefront.v1.Currencies\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/api/v1/storefront/currenciesBGZEgithub.com/NovaWorks/zcard-next/server/api/storefront/v1;storefrontv1b\x06proto3"

var (
	file_storefront_v1_config_proto_rawDescOnce sync.Once
	file_storefront_v1_config_proto_rawDescData []byte
)

func file_storefront_v1_config_proto_rawDescGZIP() []byte {
	file_storefront_v1_config_proto_rawDescOnce.Do(func() {
		file_storefront_v1_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storefront_v1_config_proto_rawDesc), len(file_storefront_v1_config_proto_rawDesc)))
	})
	return file_storefront_v1_config_proto_rawDescData
}

var file_storefront_v1_config_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_storefront_v1_config_proto_goTypes = []any{
	(*PublicConfig)(nil),      // 0: zcard.api.storefront.v1.PublicConfig
	(*PublicConfigEntry)(nil), // 1: zcard.api.storefront.v1.PublicConfigEntry
	(*Currencies)(nil),        // 2: zcard.api.storefront.v1.Currencies
	(*Currency)(nil),          // 3: zcard.api.storefront.v1.Currency
	(*emptypb.Empty)(nil),     // 4: google.protobuf.Empty
}
var file_storefront_v1_config_proto_depIdxs = []int32{
	1, // 0: zcard.api.storefront.v1.PublicConfig.entries:type_name -> zcard.api.storefront.v1.PublicConfigEntry
	3, // 1: zcard.api.storefront.v1.Currencies.currencies:type_name -> zcard.api.storefront.v1.Currency
	4, // 2: zcard.api.storefront.v1.StorefrontConfigService.GetPublicConfig:input_type -> google.protobuf.Empty
	4, // 3: zcard.api.storefront.v1.StorefrontConfigService.ListCurrencies:input_type -> google.protobuf.Empty
	0, // 4: zcard.api.storefront.v1.StorefrontConfigService.GetPublicConfig:output_type -> zcard.api.storefront.v1.PublicConfig
	2, // 5: zcard.api.storefront.v1.StorefrontConfigService.ListCurrencies:output_type -> zcard.api.storefront.v1.Currencies
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_storefront_v1_config_proto_init() }
func file_storefront_v1_config_proto_init() {
	if File_storefront_v1_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storefront_v1_config_proto_rawDesc), len(file_storefront_v1_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storefront_v1_config_proto_goTypes,
		DependencyIndexes: file_storefront_v1_config_proto_depIdxs,
		MessageInfos:      file_storefront_v1_config_proto_msgTypes,
	}.Build()
	File_storefront_v1_config_proto = out.File
	file_storefront_v1_config_proto_goTypes = nil
	file_storefront_v1_config_proto_depIdxs = nil
}
