// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: storefront/v1/coupon.proto

package storefrontv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MyCoupon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`    // fixed | percent
	Value         int64                  `protobuf:"varint,4,opt,name=value,proto3" json:"value,omitempty"` // fixed=分；percent=万分比
	Code          string                 `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	ScopeJson     string                 `protobuf:"bytes,6,opt,name=scope_json,json=scopeJson,proto3" json:"scope_json,omitempty"`
	ExpireAt      int64                  `protobuf:"varint,7,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyCoupon) Reset() {
	*x = MyCoupon{}
	mi := &file_storefront_v1_coupon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyCoupon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyCoupon) ProtoMessage() {}

func (x *MyCoupon) ProtoReflect() protoreflect.Message {
	mi := &file_storefront_v1_coupon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyCoupon.ProtoReflect.Descriptor instead.
func (*MyCoupon) Descriptor() ([]byte, []int) {
	return file_storefront_v1_coupon_proto_rawDescGZIP(), []int{0}
}

func (x *MyCoupon) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MyCoupon) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MyCoupon) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MyCoupon) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MyCoupon) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *MyCoupon) GetScopeJson() string {
	if x != nil {
		return x.ScopeJson
	}
	return ""
}

func (x *MyCoupon) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

type ListMyCouponsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coupons       []*MyCoupon            `protobuf:"bytes,1,rep,name=coupons,proto3" json:"coupons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyCouponsReply) Reset() {
	*x = ListMyCouponsReply{}
	mi := &file_storefront_v1_coupon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyCouponsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyCouponsReply) ProtoMessage() {}

func (x *ListMyCouponsReply) ProtoReflect() protoreflect.Message {
	mi := &file_storefront_v1_coupon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyCouponsReply.ProtoReflect.Descriptor instead.
func (*ListMyCouponsReply) Descriptor() ([]byte, []int) {
	return file_storefront_v1_coupon_proto_rawDescGZIP(), []int{1}
}

func (x *ListMyCouponsReply) GetCoupons() []*MyCoupon {
	if x != nil {
		return x.Coupons
	}
	return nil
}

type RedeemCouponRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedeemCouponRequest) Reset() {
	*x = RedeemCouponRequest{}
	mi := &file_storefront_v1_coupon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedeemCouponRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedeemCouponRequest) ProtoMessage() {}

func (x *RedeemCouponRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storefront_v1_coupon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedeemCouponRequest.ProtoReflect.Descriptor instead.
func (*RedeemCouponRequest) Descriptor() ([]byte, []int) {
	return file_storefront_v1_coupon_proto_rawDescGZIP(), []int{2}
}

func (x *RedeemCouponRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ListFlashSalesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Upcoming      bool                   `protobuf:"varint,1,opt,name=upcoming,proto3" json:"upcoming,omitempty"` // true = 即将开始；false = 进行中
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFlashSalesRequest) Reset() {
	*x = ListFlashSalesRequest{}
	mi := &file_storefront_v1_coupon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFlashSalesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFlashSalesRequest) ProtoMessage() {}

func (x *ListFlashSalesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storefront_v1_coupon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFlashSalesRequest.ProtoReflect.Descriptor instead.
func (*ListFlashSalesRequest) Descriptor() ([]byte, []int) {
	return file_storefront_v1_coupon_proto_rawDescGZIP(), []int{3}
}

func (x *ListFlashSalesRequest) GetUpcoming() bool {
	if x != nil {
		return x.Upcoming
	}
	return false
}

type StoreFlashSale struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     uint64                 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	FlashPrice    int64                  `protobuf:"varint,3,opt,name=flash_price,json=flashPrice,proto3" json:"flash_price,omitempty"` // 分
	StartAt       int64                  `protobuf:"varint,4,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt         int64                  `protobuf:"varint,5,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	Remaining     int32                  `protobuf:"varint,6,opt,name=remaining,proto3" json:"remaining,omitempty"` // 剩余量（limit - sold；-1 未提供）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreFlashSale) Reset() {
	*x = StoreFlashSale{}
	mi := &file_storefront_v1_coupon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreFlashSale) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreFlashSale) ProtoMessage() {}

func (x *StoreFlashSale) ProtoReflect() protoreflect.Message {
	mi := &file_storefront_v1_coupon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreFlashSale.ProtoReflect.Descriptor instead.
func (*StoreFlashSale) Descriptor() ([]byte, []int) {
	return file_storefront_v1_coupon_proto_rawDescGZIP(), []int{4}
}

func (x *StoreFlashSale) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StoreFlashSale) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *StoreFlashSale) GetFlashPrice() int64 {
	if x != nil {
		return x.FlashPrice
	}
	return 0
}

func (x *StoreFlashSale) GetStartAt() int64 {
	if x != nil {
		return x.StartAt
	}
	return 0
}

func (x *StoreFlashSale) GetEndAt() int64 {
	if x != nil {
		return x.EndAt
	}
	return 0
}

func (x *StoreFlashSale) GetRemaining() int32 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

type ListFlashSalesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*StoreFlashSale      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFlashSalesReply) Reset() {
	*x = ListFlashSalesReply{}
	mi := &file_storefront_v1_coupon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFlashSalesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFlashSalesReply) ProtoMessage() {}

func (x *ListFlashSalesReply) ProtoReflect() protoreflect.Message {
	mi := &file_storefront_v1_coupon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFlashSalesReply.ProtoReflect.Descriptor instead.
func (*ListFlashSalesReply) Descriptor() ([]byte, []int) {
	return file_storefront_v1_coupon_proto_rawDescGZIP(), []int{5}
}

func (x *ListFlashSalesReply) GetItems() []*StoreFlashSale {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_storefront_v1_coupon_proto protoreflect.FileDescriptor

const file_storefront_v1_coupon_proto_rawDesc = "" +
	"\n" +
	"\x1astorefront/v1/coupon.proto\x12\x17zcard.api.storefront.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xa8\x01\n" +
	"\bMyCoupon\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x03R\x05value\x12\x12\n" +
	"\x04code\x18\x05 \x01(\tR\x04code\x12\x1d\n" +
	"\n" +
	"scope_json\x18\x06 \x01(\tR\tscopeJson\x12\x1b\n" +
	"\texpire_at\x18\a \x01(\x03R\bexpireAt\"Q\n" +
	"\x12ListMyCouponsReply\x12;\n" +
	"\acoupons\x18\x01 \x03(\v2!.zcard.api.storefront.v1.MyCouponR\acoupons\".\n" +
	"\x13RedeemCouponRequest\x12\x17\n" +
	"\x04code\x18\x01 \x01(\tB\x03\xe0A\x02R\x04code\"3\n" +
	"\x15ListFlashSalesRequest\x12\x1a\n" +
	"\bupcoming\x18\x01 \x01(\bR\bupcoming\"\xb0\x01\n" +
	"\x0eStoreFlashSale\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x04R\tproductId\x12\x1f\n" +
	"\vflash_price\x18\x03 \x01(\x03R\n" +
	"flashPrice\x12\x19\n" +
	"\bstart_at\x18\x04 \x01(\x03R\astartAt\x12\x15\n" +
	"\x06end_at\x18\x05 \x01(\x03R\x05endAt\x12\x1c\n" +
	"\tremaining\x18\x06 \x01(\x05R\tremaining\"T\n" +
	"\x13ListFlashSalesReply\x12=\n" +
	"\x05items\x18\x01 \x03(\v2'.zcard.api.storefront.v1.StoreFlashSaleR\x05items2\xb1\x03\n" +
	"\x12StoreCouponService\x12}\n" +
	"\rListMyCoupons\x12\x16.google.protobuf.Empty\x1a+.zcard.api.storefront.v1.ListMyCouponsReply\"'\x82\xd3\xe4\x93\x02!\x12\x1f/api/v1/storefront/coupons/mine\x12\x82\x01\n" +
	"\fRedeemCoupon\x12,.zcard.api.storefront.v1.RedeemCouponRequest\x1a\x16.google.protobuf.Empty\",\x82\xd3\xe4\x93\x02&:\x01*\"!/api/v1/storefront/coupons/redeem\x12\x96\x01\n" +
	"\x0eListFlashSales\x12..zcard.api.storefront.v1.ListFlashSalesRequest\x1a,.zcard.api.storefront.v1.ListFlashSalesReply\"&\x82\xd3\xe4\x93\x02 \x12\x1e/api/v1/storefront/flash-salesBGZEgithub.com/NovaWorks/zcard-next/server/api/storefront/v1;storefrontv1b\x06proto3"

var (
	file_storefront_v1_coupon_proto_rawDescOnce sync.Once
	file_storefront_v1_coupon_proto_rawDescData []byte
)

func file_storefront_v1_coupon_proto_rawDescGZIP() []byte {
	file_storefront_v1_coupon_proto_rawDescOnce.Do(func() {
		file_storefront_v1_coupon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storefront_v1_coupon_proto_rawDesc), len(file_storefront_v1_coupon_proto_rawDesc)))
	})
	return file_storefront_v1_coupon_proto_rawDescData
}

var file_storefront_v1_coupon_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_storefront_v1_coupon_proto_goTypes = []any{
	(*MyCoupon)(nil),              // 0: zcard.api.storefront.v1.MyCoupon
	(*ListMyCouponsReply)(nil),    // 1: zcard.api.storefront.v1.ListMyCouponsReply
	(*RedeemCouponRequest)(nil),   // 2: zcard.api.storefront.v1.RedeemCouponRequest
	(*ListFlashSalesRequest)(nil), // 3: zcard.api.storefront.v1.ListFlashSalesRequest
	(*StoreFlashSale)(nil),        // 4: zcard.api.storefront.v1.StoreFlashSale
	(*ListFlashSalesReply)(nil),   // 5: zcard.api.storefront.v1.ListFlashSalesReply
	(*emptypb.Empty)(nil),         // 6: google.protobuf.Empty
}
var file_storefront_v1_coupon_proto_depIdxs = []int32{
	0, // 0: zcard.api.storefront.v1.ListMyCouponsReply.coupons:type_name -> zcard.api.storefront.v1.MyCoupon
	4, // 1: zcard.api.storefront.v1.ListFlashSalesReply.items:type_name -> zcard.api.storefront.v1.StoreFlashSale
	6, // 2: zcard.api.storefront.v1.StoreCouponService.ListMyCoupons:input_type -> google.protobuf.Empty
	2, // 3: zcard.api.storefront.v1.StoreCouponService.RedeemCoupon:input_type -> zcard.api.storefront.v1.RedeemCouponRequest
	3, // 4: zcard.api.storefront.v1.StoreCouponService.ListFlashSales:input_type -> zcard.api.storefront.v1.ListFlashSalesRequest
	1, // 5: zcard.api.storefront.v1.StoreCouponService.ListMyCoupons:output_type -> zcard.api.storefront.v1.ListMyCouponsReply
	6, // 6: zcard.api.storefront.v1.StoreCouponService.RedeemCoupon:output_type -> google.protobuf.Empty
	5, // 7: zcard.api.storefront.v1.StoreCouponService.ListFlashSales:output_type -> zcard.api.storefront.v1.ListFlashSalesReply
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_storefront_v1_coupon_proto_init() }
func file_storefront_v1_coupon_proto_init() {
	if File_storefront_v1_coupon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storefront_v1_coupon_proto_rawDesc), len(file_storefront_v1_coupon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storefront_v1_coupon_proto_goTypes,
		DependencyIndexes: file_storefront_v1_coupon_proto_depIdxs,
		MessageInfos:      file_storefront_v1_coupon_proto_msgTypes,
	}.Build()
	File_storefront_v1_coupon_proto = out.File
	file_storefront_v1_coupon_proto_goTypes = nil
	file_storefront_v1_coupon_proto_depIdxs = nil
}
