// Code generated by ent, DO NOT EDIT.

package resellerpricing

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/NovaWorks/zcard-next/server/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uint64) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint64) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint64) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint64) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint64) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint64) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint64) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint64) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint64) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldEQ(FieldUpdatedAt, v))
}

// SubsiteID applies equality check predicate on the "subsite_id" field. It's identical to SubsiteIDEQ.
func SubsiteID(v uint64) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldEQ(FieldSubsiteID, v))
}

// ProductID applies equality check predicate on the "product_id" field. It's identical to ProductIDEQ.
func ProductID(v uint64) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldEQ(FieldProductID, v))
}

// SkuID applies equality check predicate on the "sku_id" field. It's identical to SkuIDEQ.
func SkuID(v uint64) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldEQ(FieldSkuID, v))
}

// Value applies equality check predicate on the "value" field. It's identical to ValueEQ.
func Value(v int64) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldEQ(FieldValue, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldLTE(FieldUpdatedAt, v))
}

// SubsiteIDEQ applies the EQ predicate on the "subsite_id" field.
func SubsiteIDEQ(v uint64) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldEQ(FieldSubsiteID, v))
}

// SubsiteIDNEQ applies the NEQ predicate on the "subsite_id" field.
func SubsiteIDNEQ(v uint64) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldNEQ(FieldSubsiteID, v))
}

// SubsiteIDIn applies the In predicate on the "subsite_id" field.
func SubsiteIDIn(vs ...uint64) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldIn(FieldSubsiteID, vs...))
}

// SubsiteIDNotIn applies the NotIn predicate on the "subsite_id" field.
func SubsiteIDNotIn(vs ...uint64) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldNotIn(FieldSubsiteID, vs...))
}

// SubsiteIDGT applies the GT predicate on the "subsite_id" field.
func SubsiteIDGT(v uint64) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldGT(FieldSubsiteID, v))
}

// SubsiteIDGTE applies the GTE predicate on the "subsite_id" field.
func SubsiteIDGTE(v uint64) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldGTE(FieldSubsiteID, v))
}

// SubsiteIDLT applies the LT predicate on the "subsite_id" field.
func SubsiteIDLT(v uint64) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldLT(FieldSubsiteID, v))
}

// SubsiteIDLTE applies the LTE predicate on the "subsite_id" field.
func SubsiteIDLTE(v uint64) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldLTE(FieldSubsiteID, v))
}

// ProductIDEQ applies the EQ predicate on the "product_id" field.
func ProductIDEQ(v uint64) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldEQ(FieldProductID, v))
}

// ProductIDNEQ applies the NEQ predicate on the "product_id" field.
func ProductIDNEQ(v uint64) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldNEQ(FieldProductID, v))
}

// ProductIDIn applies the In predicate on the "product_id" field.
func ProductIDIn(vs ...uint64) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldIn(FieldProductID, vs...))
}

// ProductIDNotIn applies the NotIn predicate on the "product_id" field.
func ProductIDNotIn(vs ...uint64) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldNotIn(FieldProductID, vs...))
}

// ProductIDGT applies the GT predicate on the "product_id" field.
func ProductIDGT(v uint64) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldGT(FieldProductID, v))
}

// ProductIDGTE applies the GTE predicate on the "product_id" field.
func ProductIDGTE(v uint64) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldGTE(FieldProductID, v))
}

// ProductIDLT applies the LT predicate on the "product_id" field.
func ProductIDLT(v uint64) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldLT(FieldProductID, v))
}

// ProductIDLTE applies the LTE predicate on the "product_id" field.
func ProductIDLTE(v uint64) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldLTE(FieldProductID, v))
}

// SkuIDEQ applies the EQ predicate on the "sku_id" field.
func SkuIDEQ(v uint64) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldEQ(FieldSkuID, v))
}

// SkuIDNEQ applies the NEQ predicate on the "sku_id" field.
func SkuIDNEQ(v uint64) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldNEQ(FieldSkuID, v))
}

// SkuIDIn applies the In predicate on the "sku_id" field.
func SkuIDIn(vs ...uint64) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldIn(FieldSkuID, vs...))
}

// SkuIDNotIn applies the NotIn predicate on the "sku_id" field.
func SkuIDNotIn(vs ...uint64) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldNotIn(FieldSkuID, vs...))
}

// SkuIDGT applies the GT predicate on the "sku_id" field.
func SkuIDGT(v uint64) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldGT(FieldSkuID, v))
}

// SkuIDGTE applies the GTE predicate on the "sku_id" field.
func SkuIDGTE(v uint64) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldGTE(FieldSkuID, v))
}

// SkuIDLT applies the LT predicate on the "sku_id" field.
func SkuIDLT(v uint64) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldLT(FieldSkuID, v))
}

// SkuIDLTE applies the LTE predicate on the "sku_id" field.
func SkuIDLTE(v uint64) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldLTE(FieldSkuID, v))
}

// ModeEQ applies the EQ predicate on the "mode" field.
func ModeEQ(v Mode) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldEQ(FieldMode, v))
}

// ModeNEQ applies the NEQ predicate on the "mode" field.
func ModeNEQ(v Mode) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldNEQ(FieldMode, v))
}

// ModeIn applies the In predicate on the "mode" field.
func ModeIn(vs ...Mode) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldIn(FieldMode, vs...))
}

// ModeNotIn applies the NotIn predicate on the "mode" field.
func ModeNotIn(vs ...Mode) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldNotIn(FieldMode, vs...))
}

// ValueEQ applies the EQ predicate on the "value" field.
func ValueEQ(v int64) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldEQ(FieldValue, v))
}

// ValueNEQ applies the NEQ predicate on the "value" field.
func ValueNEQ(v int64) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldNEQ(FieldValue, v))
}

// ValueIn applies the In predicate on the "value" field.
func ValueIn(vs ...int64) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldIn(FieldValue, vs...))
}

// ValueNotIn applies the NotIn predicate on the "value" field.
func ValueNotIn(vs ...int64) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldNotIn(FieldValue, vs...))
}

// ValueGT applies the GT predicate on the "value" field.
func ValueGT(v int64) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldGT(FieldValue, v))
}

// ValueGTE applies the GTE predicate on the "value" field.
func ValueGTE(v int64) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldGTE(FieldValue, v))
}

// ValueLT applies the LT predicate on the "value" field.
func ValueLT(v int64) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldLT(FieldValue, v))
}

// ValueLTE applies the LTE predicate on the "value" field.
func ValueLTE(v int64) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.FieldLTE(FieldValue, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ResellerPricing) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ResellerPricing) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ResellerPricing) predicate.ResellerPricing {
	return predicate.ResellerPricing(sql.NotPredicates(p))
}
