// Code generated by ent, DO NOT EDIT.

package card

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/NovaWorks/zcard-next/server/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uint64) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint64) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint64) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint64) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint64) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint64) predicate.Card {
	return predicate.Card(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint64) predicate.Card {
	return predicate.Card(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint64) predicate.Card {
	return predicate.Card(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint64) predicate.Card {
	return predicate.Card(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldUpdatedAt, v))
}

// SubsiteID applies equality check predicate on the "subsite_id" field. It's identical to SubsiteIDEQ.
func SubsiteID(v uint64) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldSubsiteID, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int32) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldVersion, v))
}

// ProductID applies equality check predicate on the "product_id" field. It's identical to ProductIDEQ.
func ProductID(v uint64) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldProductID, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v []byte) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldContent, v))
}

// ContentHash applies equality check predicate on the "content_hash" field. It's identical to ContentHashEQ.
func ContentHash(v string) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldContentHash, v))
}

// NumberHash applies equality check predicate on the "number_hash" field. It's identical to NumberHashEQ.
func NumberHash(v string) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldNumberHash, v))
}

// OrderID applies equality check predicate on the "order_id" field. It's identical to OrderIDEQ.
func OrderID(v uint64) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldOrderID, v))
}

// SkuID applies equality check predicate on the "sku_id" field. It's identical to SkuIDEQ.
func SkuID(v uint64) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldSkuID, v))
}

// ImportID applies equality check predicate on the "import_id" field. It's identical to ImportIDEQ.
func ImportID(v uint64) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldImportID, v))
}

// CardType applies equality check predicate on the "card_type" field. It's identical to CardTypeEQ.
func CardType(v string) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldCardType, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldNote, v))
}

// OwnerID applies equality check predicate on the "owner_id" field. It's identical to OwnerIDEQ.
func OwnerID(v uint64) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldOwnerID, v))
}

// DraftPremium applies equality check predicate on the "draft_premium" field. It's identical to DraftPremiumEQ.
func DraftPremium(v int64) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldDraftPremium, v))
}

// DraftCost applies equality check predicate on the "draft_cost" field. It's identical to DraftCostEQ.
func DraftCost(v int64) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldDraftCost, v))
}

// Price applies equality check predicate on the "price" field. It's identical to PriceEQ.
func Price(v int64) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldPrice, v))
}

// LockedAt applies equality check predicate on the "locked_at" field. It's identical to LockedAtEQ.
func LockedAt(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldLockedAt, v))
}

// UsedAt applies equality check predicate on the "used_at" field. It's identical to UsedAtEQ.
func UsedAt(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldUsedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldLTE(FieldUpdatedAt, v))
}

// SubsiteIDEQ applies the EQ predicate on the "subsite_id" field.
func SubsiteIDEQ(v uint64) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldSubsiteID, v))
}

// SubsiteIDNEQ applies the NEQ predicate on the "subsite_id" field.
func SubsiteIDNEQ(v uint64) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldSubsiteID, v))
}

// SubsiteIDIn applies the In predicate on the "subsite_id" field.
func SubsiteIDIn(vs ...uint64) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldSubsiteID, vs...))
}

// SubsiteIDNotIn applies the NotIn predicate on the "subsite_id" field.
func SubsiteIDNotIn(vs ...uint64) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldSubsiteID, vs...))
}

// SubsiteIDGT applies the GT predicate on the "subsite_id" field.
func SubsiteIDGT(v uint64) predicate.Card {
	return predicate.Card(sql.FieldGT(FieldSubsiteID, v))
}

// SubsiteIDGTE applies the GTE predicate on the "subsite_id" field.
func SubsiteIDGTE(v uint64) predicate.Card {
	return predicate.Card(sql.FieldGTE(FieldSubsiteID, v))
}

// SubsiteIDLT applies the LT predicate on the "subsite_id" field.
func SubsiteIDLT(v uint64) predicate.Card {
	return predicate.Card(sql.FieldLT(FieldSubsiteID, v))
}

// SubsiteIDLTE applies the LTE predicate on the "subsite_id" field.
func SubsiteIDLTE(v uint64) predicate.Card {
	return predicate.Card(sql.FieldLTE(FieldSubsiteID, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int32) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int32) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int32) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int32) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int32) predicate.Card {
	return predicate.Card(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int32) predicate.Card {
	return predicate.Card(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int32) predicate.Card {
	return predicate.Card(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int32) predicate.Card {
	return predicate.Card(sql.FieldLTE(FieldVersion, v))
}

// ProductIDEQ applies the EQ predicate on the "product_id" field.
func ProductIDEQ(v uint64) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldProductID, v))
}

// ProductIDNEQ applies the NEQ predicate on the "product_id" field.
func ProductIDNEQ(v uint64) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldProductID, v))
}

// ProductIDIn applies the In predicate on the "product_id" field.
func ProductIDIn(vs ...uint64) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldProductID, vs...))
}

// ProductIDNotIn applies the NotIn predicate on the "product_id" field.
func ProductIDNotIn(vs ...uint64) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldProductID, vs...))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v []byte) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v []byte) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...[]byte) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...[]byte) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v []byte) predicate.Card {
	return predicate.Card(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v []byte) predicate.Card {
	return predicate.Card(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v []byte) predicate.Card {
	return predicate.Card(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v []byte) predicate.Card {
	return predicate.Card(sql.FieldLTE(FieldContent, v))
}

// ContentHashEQ applies the EQ predicate on the "content_hash" field.
func ContentHashEQ(v string) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldContentHash, v))
}

// ContentHashNEQ applies the NEQ predicate on the "content_hash" field.
func ContentHashNEQ(v string) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldContentHash, v))
}

// ContentHashIn applies the In predicate on the "content_hash" field.
func ContentHashIn(vs ...string) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldContentHash, vs...))
}

// ContentHashNotIn applies the NotIn predicate on the "content_hash" field.
func ContentHashNotIn(vs ...string) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldContentHash, vs...))
}

// ContentHashGT applies the GT predicate on the "content_hash" field.
func ContentHashGT(v string) predicate.Card {
	return predicate.Card(sql.FieldGT(FieldContentHash, v))
}

// ContentHashGTE applies the GTE predicate on the "content_hash" field.
func ContentHashGTE(v string) predicate.Card {
	return predicate.Card(sql.FieldGTE(FieldContentHash, v))
}

// ContentHashLT applies the LT predicate on the "content_hash" field.
func ContentHashLT(v string) predicate.Card {
	return predicate.Card(sql.FieldLT(FieldContentHash, v))
}

// ContentHashLTE applies the LTE predicate on the "content_hash" field.
func ContentHashLTE(v string) predicate.Card {
	return predicate.Card(sql.FieldLTE(FieldContentHash, v))
}

// ContentHashContains applies the Contains predicate on the "content_hash" field.
func ContentHashContains(v string) predicate.Card {
	return predicate.Card(sql.FieldContains(FieldContentHash, v))
}

// ContentHashHasPrefix applies the HasPrefix predicate on the "content_hash" field.
func ContentHashHasPrefix(v string) predicate.Card {
	return predicate.Card(sql.FieldHasPrefix(FieldContentHash, v))
}

// ContentHashHasSuffix applies the HasSuffix predicate on the "content_hash" field.
func ContentHashHasSuffix(v string) predicate.Card {
	return predicate.Card(sql.FieldHasSuffix(FieldContentHash, v))
}

// ContentHashEqualFold applies the EqualFold predicate on the "content_hash" field.
func ContentHashEqualFold(v string) predicate.Card {
	return predicate.Card(sql.FieldEqualFold(FieldContentHash, v))
}

// ContentHashContainsFold applies the ContainsFold predicate on the "content_hash" field.
func ContentHashContainsFold(v string) predicate.Card {
	return predicate.Card(sql.FieldContainsFold(FieldContentHash, v))
}

// NumberHashEQ applies the EQ predicate on the "number_hash" field.
func NumberHashEQ(v string) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldNumberHash, v))
}

// NumberHashNEQ applies the NEQ predicate on the "number_hash" field.
func NumberHashNEQ(v string) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldNumberHash, v))
}

// NumberHashIn applies the In predicate on the "number_hash" field.
func NumberHashIn(vs ...string) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldNumberHash, vs...))
}

// NumberHashNotIn applies the NotIn predicate on the "number_hash" field.
func NumberHashNotIn(vs ...string) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldNumberHash, vs...))
}

// NumberHashGT applies the GT predicate on the "number_hash" field.
func NumberHashGT(v string) predicate.Card {
	return predicate.Card(sql.FieldGT(FieldNumberHash, v))
}

// NumberHashGTE applies the GTE predicate on the "number_hash" field.
func NumberHashGTE(v string) predicate.Card {
	return predicate.Card(sql.FieldGTE(FieldNumberHash, v))
}

// NumberHashLT applies the LT predicate on the "number_hash" field.
func NumberHashLT(v string) predicate.Card {
	return predicate.Card(sql.FieldLT(FieldNumberHash, v))
}

// NumberHashLTE applies the LTE predicate on the "number_hash" field.
func NumberHashLTE(v string) predicate.Card {
	return predicate.Card(sql.FieldLTE(FieldNumberHash, v))
}

// NumberHashContains applies the Contains predicate on the "number_hash" field.
func NumberHashContains(v string) predicate.Card {
	return predicate.Card(sql.FieldContains(FieldNumberHash, v))
}

// NumberHashHasPrefix applies the HasPrefix predicate on the "number_hash" field.
func NumberHashHasPrefix(v string) predicate.Card {
	return predicate.Card(sql.FieldHasPrefix(FieldNumberHash, v))
}

// NumberHashHasSuffix applies the HasSuffix predicate on the "number_hash" field.
func NumberHashHasSuffix(v string) predicate.Card {
	return predicate.Card(sql.FieldHasSuffix(FieldNumberHash, v))
}

// NumberHashIsNil applies the IsNil predicate on the "number_hash" field.
func NumberHashIsNil() predicate.Card {
	return predicate.Card(sql.FieldIsNull(FieldNumberHash))
}

// NumberHashNotNil applies the NotNil predicate on the "number_hash" field.
func NumberHashNotNil() predicate.Card {
	return predicate.Card(sql.FieldNotNull(FieldNumberHash))
}

// NumberHashEqualFold applies the EqualFold predicate on the "number_hash" field.
func NumberHashEqualFold(v string) predicate.Card {
	return predicate.Card(sql.FieldEqualFold(FieldNumberHash, v))
}

// NumberHashContainsFold applies the ContainsFold predicate on the "number_hash" field.
func NumberHashContainsFold(v string) predicate.Card {
	return predicate.Card(sql.FieldContainsFold(FieldNumberHash, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldStatus, vs...))
}

// OrderIDEQ applies the EQ predicate on the "order_id" field.
func OrderIDEQ(v uint64) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldOrderID, v))
}

// OrderIDNEQ applies the NEQ predicate on the "order_id" field.
func OrderIDNEQ(v uint64) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldOrderID, v))
}

// OrderIDIn applies the In predicate on the "order_id" field.
func OrderIDIn(vs ...uint64) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldOrderID, vs...))
}

// OrderIDNotIn applies the NotIn predicate on the "order_id" field.
func OrderIDNotIn(vs ...uint64) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldOrderID, vs...))
}

// OrderIDGT applies the GT predicate on the "order_id" field.
func OrderIDGT(v uint64) predicate.Card {
	return predicate.Card(sql.FieldGT(FieldOrderID, v))
}

// OrderIDGTE applies the GTE predicate on the "order_id" field.
func OrderIDGTE(v uint64) predicate.Card {
	return predicate.Card(sql.FieldGTE(FieldOrderID, v))
}

// OrderIDLT applies the LT predicate on the "order_id" field.
func OrderIDLT(v uint64) predicate.Card {
	return predicate.Card(sql.FieldLT(FieldOrderID, v))
}

// OrderIDLTE applies the LTE predicate on the "order_id" field.
func OrderIDLTE(v uint64) predicate.Card {
	return predicate.Card(sql.FieldLTE(FieldOrderID, v))
}

// OrderIDIsNil applies the IsNil predicate on the "order_id" field.
func OrderIDIsNil() predicate.Card {
	return predicate.Card(sql.FieldIsNull(FieldOrderID))
}

// OrderIDNotNil applies the NotNil predicate on the "order_id" field.
func OrderIDNotNil() predicate.Card {
	return predicate.Card(sql.FieldNotNull(FieldOrderID))
}

// SkuIDEQ applies the EQ predicate on the "sku_id" field.
func SkuIDEQ(v uint64) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldSkuID, v))
}

// SkuIDNEQ applies the NEQ predicate on the "sku_id" field.
func SkuIDNEQ(v uint64) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldSkuID, v))
}

// SkuIDIn applies the In predicate on the "sku_id" field.
func SkuIDIn(vs ...uint64) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldSkuID, vs...))
}

// SkuIDNotIn applies the NotIn predicate on the "sku_id" field.
func SkuIDNotIn(vs ...uint64) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldSkuID, vs...))
}

// SkuIDGT applies the GT predicate on the "sku_id" field.
func SkuIDGT(v uint64) predicate.Card {
	return predicate.Card(sql.FieldGT(FieldSkuID, v))
}

// SkuIDGTE applies the GTE predicate on the "sku_id" field.
func SkuIDGTE(v uint64) predicate.Card {
	return predicate.Card(sql.FieldGTE(FieldSkuID, v))
}

// SkuIDLT applies the LT predicate on the "sku_id" field.
func SkuIDLT(v uint64) predicate.Card {
	return predicate.Card(sql.FieldLT(FieldSkuID, v))
}

// SkuIDLTE applies the LTE predicate on the "sku_id" field.
func SkuIDLTE(v uint64) predicate.Card {
	return predicate.Card(sql.FieldLTE(FieldSkuID, v))
}

// SkuIDIsNil applies the IsNil predicate on the "sku_id" field.
func SkuIDIsNil() predicate.Card {
	return predicate.Card(sql.FieldIsNull(FieldSkuID))
}

// SkuIDNotNil applies the NotNil predicate on the "sku_id" field.
func SkuIDNotNil() predicate.Card {
	return predicate.Card(sql.FieldNotNull(FieldSkuID))
}

// ImportIDEQ applies the EQ predicate on the "import_id" field.
func ImportIDEQ(v uint64) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldImportID, v))
}

// ImportIDNEQ applies the NEQ predicate on the "import_id" field.
func ImportIDNEQ(v uint64) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldImportID, v))
}

// ImportIDIn applies the In predicate on the "import_id" field.
func ImportIDIn(vs ...uint64) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldImportID, vs...))
}

// ImportIDNotIn applies the NotIn predicate on the "import_id" field.
func ImportIDNotIn(vs ...uint64) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldImportID, vs...))
}

// ImportIDGT applies the GT predicate on the "import_id" field.
func ImportIDGT(v uint64) predicate.Card {
	return predicate.Card(sql.FieldGT(FieldImportID, v))
}

// ImportIDGTE applies the GTE predicate on the "import_id" field.
func ImportIDGTE(v uint64) predicate.Card {
	return predicate.Card(sql.FieldGTE(FieldImportID, v))
}

// ImportIDLT applies the LT predicate on the "import_id" field.
func ImportIDLT(v uint64) predicate.Card {
	return predicate.Card(sql.FieldLT(FieldImportID, v))
}

// ImportIDLTE applies the LTE predicate on the "import_id" field.
func ImportIDLTE(v uint64) predicate.Card {
	return predicate.Card(sql.FieldLTE(FieldImportID, v))
}

// ImportIDIsNil applies the IsNil predicate on the "import_id" field.
func ImportIDIsNil() predicate.Card {
	return predicate.Card(sql.FieldIsNull(FieldImportID))
}

// ImportIDNotNil applies the NotNil predicate on the "import_id" field.
func ImportIDNotNil() predicate.Card {
	return predicate.Card(sql.FieldNotNull(FieldImportID))
}

// CardTypeEQ applies the EQ predicate on the "card_type" field.
func CardTypeEQ(v string) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldCardType, v))
}

// CardTypeNEQ applies the NEQ predicate on the "card_type" field.
func CardTypeNEQ(v string) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldCardType, v))
}

// CardTypeIn applies the In predicate on the "card_type" field.
func CardTypeIn(vs ...string) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldCardType, vs...))
}

// CardTypeNotIn applies the NotIn predicate on the "card_type" field.
func CardTypeNotIn(vs ...string) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldCardType, vs...))
}

// CardTypeGT applies the GT predicate on the "card_type" field.
func CardTypeGT(v string) predicate.Card {
	return predicate.Card(sql.FieldGT(FieldCardType, v))
}

// CardTypeGTE applies the GTE predicate on the "card_type" field.
func CardTypeGTE(v string) predicate.Card {
	return predicate.Card(sql.FieldGTE(FieldCardType, v))
}

// CardTypeLT applies the LT predicate on the "card_type" field.
func CardTypeLT(v string) predicate.Card {
	return predicate.Card(sql.FieldLT(FieldCardType, v))
}

// CardTypeLTE applies the LTE predicate on the "card_type" field.
func CardTypeLTE(v string) predicate.Card {
	return predicate.Card(sql.FieldLTE(FieldCardType, v))
}

// CardTypeContains applies the Contains predicate on the "card_type" field.
func CardTypeContains(v string) predicate.Card {
	return predicate.Card(sql.FieldContains(FieldCardType, v))
}

// CardTypeHasPrefix applies the HasPrefix predicate on the "card_type" field.
func CardTypeHasPrefix(v string) predicate.Card {
	return predicate.Card(sql.FieldHasPrefix(FieldCardType, v))
}

// CardTypeHasSuffix applies the HasSuffix predicate on the "card_type" field.
func CardTypeHasSuffix(v string) predicate.Card {
	return predicate.Card(sql.FieldHasSuffix(FieldCardType, v))
}

// CardTypeIsNil applies the IsNil predicate on the "card_type" field.
func CardTypeIsNil() predicate.Card {
	return predicate.Card(sql.FieldIsNull(FieldCardType))
}

// CardTypeNotNil applies the NotNil predicate on the "card_type" field.
func CardTypeNotNil() predicate.Card {
	return predicate.Card(sql.FieldNotNull(FieldCardType))
}

// CardTypeEqualFold applies the EqualFold predicate on the "card_type" field.
func CardTypeEqualFold(v string) predicate.Card {
	return predicate.Card(sql.FieldEqualFold(FieldCardType, v))
}

// CardTypeContainsFold applies the ContainsFold predicate on the "card_type" field.
func CardTypeContainsFold(v string) predicate.Card {
	return predicate.Card(sql.FieldContainsFold(FieldCardType, v))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.Card {
	return predicate.Card(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.Card {
	return predicate.Card(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.Card {
	return predicate.Card(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.Card {
	return predicate.Card(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.Card {
	return predicate.Card(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.Card {
	return predicate.Card(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.Card {
	return predicate.Card(sql.FieldHasSuffix(FieldNote, v))
}

// NoteIsNil applies the IsNil predicate on the "note" field.
func NoteIsNil() predicate.Card {
	return predicate.Card(sql.FieldIsNull(FieldNote))
}

// NoteNotNil applies the NotNil predicate on the "note" field.
func NoteNotNil() predicate.Card {
	return predicate.Card(sql.FieldNotNull(FieldNote))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.Card {
	return predicate.Card(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.Card {
	return predicate.Card(sql.FieldContainsFold(FieldNote, v))
}

// OwnerIDEQ applies the EQ predicate on the "owner_id" field.
func OwnerIDEQ(v uint64) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldOwnerID, v))
}

// OwnerIDNEQ applies the NEQ predicate on the "owner_id" field.
func OwnerIDNEQ(v uint64) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldOwnerID, v))
}

// OwnerIDIn applies the In predicate on the "owner_id" field.
func OwnerIDIn(vs ...uint64) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldOwnerID, vs...))
}

// OwnerIDNotIn applies the NotIn predicate on the "owner_id" field.
func OwnerIDNotIn(vs ...uint64) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldOwnerID, vs...))
}

// OwnerIDGT applies the GT predicate on the "owner_id" field.
func OwnerIDGT(v uint64) predicate.Card {
	return predicate.Card(sql.FieldGT(FieldOwnerID, v))
}

// OwnerIDGTE applies the GTE predicate on the "owner_id" field.
func OwnerIDGTE(v uint64) predicate.Card {
	return predicate.Card(sql.FieldGTE(FieldOwnerID, v))
}

// OwnerIDLT applies the LT predicate on the "owner_id" field.
func OwnerIDLT(v uint64) predicate.Card {
	return predicate.Card(sql.FieldLT(FieldOwnerID, v))
}

// OwnerIDLTE applies the LTE predicate on the "owner_id" field.
func OwnerIDLTE(v uint64) predicate.Card {
	return predicate.Card(sql.FieldLTE(FieldOwnerID, v))
}

// DraftPremiumEQ applies the EQ predicate on the "draft_premium" field.
func DraftPremiumEQ(v int64) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldDraftPremium, v))
}

// DraftPremiumNEQ applies the NEQ predicate on the "draft_premium" field.
func DraftPremiumNEQ(v int64) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldDraftPremium, v))
}

// DraftPremiumIn applies the In predicate on the "draft_premium" field.
func DraftPremiumIn(vs ...int64) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldDraftPremium, vs...))
}

// DraftPremiumNotIn applies the NotIn predicate on the "draft_premium" field.
func DraftPremiumNotIn(vs ...int64) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldDraftPremium, vs...))
}

// DraftPremiumGT applies the GT predicate on the "draft_premium" field.
func DraftPremiumGT(v int64) predicate.Card {
	return predicate.Card(sql.FieldGT(FieldDraftPremium, v))
}

// DraftPremiumGTE applies the GTE predicate on the "draft_premium" field.
func DraftPremiumGTE(v int64) predicate.Card {
	return predicate.Card(sql.FieldGTE(FieldDraftPremium, v))
}

// DraftPremiumLT applies the LT predicate on the "draft_premium" field.
func DraftPremiumLT(v int64) predicate.Card {
	return predicate.Card(sql.FieldLT(FieldDraftPremium, v))
}

// DraftPremiumLTE applies the LTE predicate on the "draft_premium" field.
func DraftPremiumLTE(v int64) predicate.Card {
	return predicate.Card(sql.FieldLTE(FieldDraftPremium, v))
}

// DraftCostEQ applies the EQ predicate on the "draft_cost" field.
func DraftCostEQ(v int64) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldDraftCost, v))
}

// DraftCostNEQ applies the NEQ predicate on the "draft_cost" field.
func DraftCostNEQ(v int64) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldDraftCost, v))
}

// DraftCostIn applies the In predicate on the "draft_cost" field.
func DraftCostIn(vs ...int64) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldDraftCost, vs...))
}

// DraftCostNotIn applies the NotIn predicate on the "draft_cost" field.
func DraftCostNotIn(vs ...int64) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldDraftCost, vs...))
}

// DraftCostGT applies the GT predicate on the "draft_cost" field.
func DraftCostGT(v int64) predicate.Card {
	return predicate.Card(sql.FieldGT(FieldDraftCost, v))
}

// DraftCostGTE applies the GTE predicate on the "draft_cost" field.
func DraftCostGTE(v int64) predicate.Card {
	return predicate.Card(sql.FieldGTE(FieldDraftCost, v))
}

// DraftCostLT applies the LT predicate on the "draft_cost" field.
func DraftCostLT(v int64) predicate.Card {
	return predicate.Card(sql.FieldLT(FieldDraftCost, v))
}

// DraftCostLTE applies the LTE predicate on the "draft_cost" field.
func DraftCostLTE(v int64) predicate.Card {
	return predicate.Card(sql.FieldLTE(FieldDraftCost, v))
}

// PriceEQ applies the EQ predicate on the "price" field.
func PriceEQ(v int64) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldPrice, v))
}

// PriceNEQ applies the NEQ predicate on the "price" field.
func PriceNEQ(v int64) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldPrice, v))
}

// PriceIn applies the In predicate on the "price" field.
func PriceIn(vs ...int64) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldPrice, vs...))
}

// PriceNotIn applies the NotIn predicate on the "price" field.
func PriceNotIn(vs ...int64) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldPrice, vs...))
}

// PriceGT applies the GT predicate on the "price" field.
func PriceGT(v int64) predicate.Card {
	return predicate.Card(sql.FieldGT(FieldPrice, v))
}

// PriceGTE applies the GTE predicate on the "price" field.
func PriceGTE(v int64) predicate.Card {
	return predicate.Card(sql.FieldGTE(FieldPrice, v))
}

// PriceLT applies the LT predicate on the "price" field.
func PriceLT(v int64) predicate.Card {
	return predicate.Card(sql.FieldLT(FieldPrice, v))
}

// PriceLTE applies the LTE predicate on the "price" field.
func PriceLTE(v int64) predicate.Card {
	return predicate.Card(sql.FieldLTE(FieldPrice, v))
}

// PriceIsNil applies the IsNil predicate on the "price" field.
func PriceIsNil() predicate.Card {
	return predicate.Card(sql.FieldIsNull(FieldPrice))
}

// PriceNotNil applies the NotNil predicate on the "price" field.
func PriceNotNil() predicate.Card {
	return predicate.Card(sql.FieldNotNull(FieldPrice))
}

// LockedAtEQ applies the EQ predicate on the "locked_at" field.
func LockedAtEQ(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldLockedAt, v))
}

// LockedAtNEQ applies the NEQ predicate on the "locked_at" field.
func LockedAtNEQ(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldLockedAt, v))
}

// LockedAtIn applies the In predicate on the "locked_at" field.
func LockedAtIn(vs ...time.Time) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldLockedAt, vs...))
}

// LockedAtNotIn applies the NotIn predicate on the "locked_at" field.
func LockedAtNotIn(vs ...time.Time) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldLockedAt, vs...))
}

// LockedAtGT applies the GT predicate on the "locked_at" field.
func LockedAtGT(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldGT(FieldLockedAt, v))
}

// LockedAtGTE applies the GTE predicate on the "locked_at" field.
func LockedAtGTE(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldGTE(FieldLockedAt, v))
}

// LockedAtLT applies the LT predicate on the "locked_at" field.
func LockedAtLT(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldLT(FieldLockedAt, v))
}

// LockedAtLTE applies the LTE predicate on the "locked_at" field.
func LockedAtLTE(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldLTE(FieldLockedAt, v))
}

// LockedAtIsNil applies the IsNil predicate on the "locked_at" field.
func LockedAtIsNil() predicate.Card {
	return predicate.Card(sql.FieldIsNull(FieldLockedAt))
}

// LockedAtNotNil applies the NotNil predicate on the "locked_at" field.
func LockedAtNotNil() predicate.Card {
	return predicate.Card(sql.FieldNotNull(FieldLockedAt))
}

// UsedAtEQ applies the EQ predicate on the "used_at" field.
func UsedAtEQ(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldUsedAt, v))
}

// UsedAtNEQ applies the NEQ predicate on the "used_at" field.
func UsedAtNEQ(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldUsedAt, v))
}

// UsedAtIn applies the In predicate on the "used_at" field.
func UsedAtIn(vs ...time.Time) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldUsedAt, vs...))
}

// UsedAtNotIn applies the NotIn predicate on the "used_at" field.
func UsedAtNotIn(vs ...time.Time) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldUsedAt, vs...))
}

// UsedAtGT applies the GT predicate on the "used_at" field.
func UsedAtGT(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldGT(FieldUsedAt, v))
}

// UsedAtGTE applies the GTE predicate on the "used_at" field.
func UsedAtGTE(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldGTE(FieldUsedAt, v))
}

// UsedAtLT applies the LT predicate on the "used_at" field.
func UsedAtLT(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldLT(FieldUsedAt, v))
}

// UsedAtLTE applies the LTE predicate on the "used_at" field.
func UsedAtLTE(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldLTE(FieldUsedAt, v))
}

// UsedAtIsNil applies the IsNil predicate on the "used_at" field.
func UsedAtIsNil() predicate.Card {
	return predicate.Card(sql.FieldIsNull(FieldUsedAt))
}

// UsedAtNotNil applies the NotNil predicate on the "used_at" field.
func UsedAtNotNil() predicate.Card {
	return predicate.Card(sql.FieldNotNull(FieldUsedAt))
}

// HasProduct applies the HasEdge predicate on the "product" edge.
func HasProduct() predicate.Card {
	return predicate.Card(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProductTable, ProductColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProductWith applies the HasEdge predicate on the "product" edge with a given conditions (other predicates).
func HasProductWith(preds ...predicate.Product) predicate.Card {
	return predicate.Card(func(s *sql.Selector) {
		step := newProductStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Card) predicate.Card {
	return predicate.Card(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Card) predicate.Card {
	return predicate.Card(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Card) predicate.Card {
	return predicate.Card(sql.NotPredicates(p))
}
