// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NovaWorks/zcard-next/server/internal/data/ent/auditlog"
	"github.com/NovaWorks/zcard-next/server/internal/data/ent/predicate"
)

// AuditLogUpdate is the builder for updating AuditLog entities.
type AuditLogUpdate struct {
	config
	hooks    []Hook
	mutation *AuditLogMutation
}

// Where appends a list predicates to the AuditLogUpdate builder.
func (_u *AuditLogUpdate) Where(ps ...predicate.AuditLog) *AuditLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOperatorType sets the "operator_type" field.
func (_u *AuditLogUpdate) SetOperatorType(v auditlog.OperatorType) *AuditLogUpdate {
	_u.mutation.SetOperatorType(v)
	return _u
}

// SetNillableOperatorType sets the "operator_type" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableOperatorType(v *auditlog.OperatorType) *AuditLogUpdate {
	if v != nil {
		_u.SetOperatorType(*v)
	}
	return _u
}

// SetOperatorID sets the "operator_id" field.
func (_u *AuditLogUpdate) SetOperatorID(v uint64) *AuditLogUpdate {
	_u.mutation.ResetOperatorID()
	_u.mutation.SetOperatorID(v)
	return _u
}

// SetNillableOperatorID sets the "operator_id" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableOperatorID(v *uint64) *AuditLogUpdate {
	if v != nil {
		_u.SetOperatorID(*v)
	}
	return _u
}

// AddOperatorID adds value to the "operator_id" field.
func (_u *AuditLogUpdate) AddOperatorID(v int64) *AuditLogUpdate {
	_u.mutation.AddOperatorID(v)
	return _u
}

// ClearOperatorID clears the value of the "operator_id" field.
func (_u *AuditLogUpdate) ClearOperatorID() *AuditLogUpdate {
	_u.mutation.ClearOperatorID()
	return _u
}

// SetPermissionPoint sets the "permission_point" field.
func (_u *AuditLogUpdate) SetPermissionPoint(v string) *AuditLogUpdate {
	_u.mutation.SetPermissionPoint(v)
	return _u
}

// SetNillablePermissionPoint sets the "permission_point" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillablePermissionPoint(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetPermissionPoint(*v)
	}
	return _u
}

// ClearPermissionPoint clears the value of the "permission_point" field.
func (_u *AuditLogUpdate) ClearPermissionPoint() *AuditLogUpdate {
	_u.mutation.ClearPermissionPoint()
	return _u
}

// SetAction sets the "action" field.
func (_u *AuditLogUpdate) SetAction(v string) *AuditLogUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableAction(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetRoute sets the "route" field.
func (_u *AuditLogUpdate) SetRoute(v string) *AuditLogUpdate {
	_u.mutation.SetRoute(v)
	return _u
}

// SetNillableRoute sets the "route" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableRoute(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetRoute(*v)
	}
	return _u
}

// SetBefore sets the "before" field.
func (_u *AuditLogUpdate) SetBefore(v map[string]interface{}) *AuditLogUpdate {
	_u.mutation.SetBefore(v)
	return _u
}

// ClearBefore clears the value of the "before" field.
func (_u *AuditLogUpdate) ClearBefore() *AuditLogUpdate {
	_u.mutation.ClearBefore()
	return _u
}

// SetAfter sets the "after" field.
func (_u *AuditLogUpdate) SetAfter(v map[string]interface{}) *AuditLogUpdate {
	_u.mutation.SetAfter(v)
	return _u
}

// ClearAfter clears the value of the "after" field.
func (_u *AuditLogUpdate) ClearAfter() *AuditLogUpdate {
	_u.mutation.ClearAfter()
	return _u
}

// SetIP sets the "ip" field.
func (_u *AuditLogUpdate) SetIP(v string) *AuditLogUpdate {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableIP(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// ClearIP clears the value of the "ip" field.
func (_u *AuditLogUpdate) ClearIP() *AuditLogUpdate {
	_u.mutation.ClearIP()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *AuditLogUpdate) SetUserAgent(v string) *AuditLogUpdate {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableUserAgent(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *AuditLogUpdate) ClearUserAgent() *AuditLogUpdate {
	_u.mutation.ClearUserAgent()
	return _u
}

// Mutation returns the AuditLogMutation object of the builder.
func (_u *AuditLogUpdate) Mutation() *AuditLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuditLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuditLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuditLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuditLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuditLogUpdate) check() error {
	if v, ok := _u.mutation.OperatorType(); ok {
		if err := auditlog.OperatorTypeValidator(v); err != nil {
			return &ValidationError{Name: "operator_type", err: fmt.Errorf(`ent: validator failed for field "AuditLog.operator_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PermissionPoint(); ok {
		if err := auditlog.PermissionPointValidator(v); err != nil {
			return &ValidationError{Name: "permission_point", err: fmt.Errorf(`ent: validator failed for field "AuditLog.permission_point": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Action(); ok {
		if err := auditlog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "AuditLog.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Route(); ok {
		if err := auditlog.RouteValidator(v); err != nil {
			return &ValidationError{Name: "route", err: fmt.Errorf(`ent: validator failed for field "AuditLog.route": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IP(); ok {
		if err := auditlog.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "AuditLog.ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserAgent(); ok {
		if err := auditlog.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "AuditLog.user_agent": %w`, err)}
		}
	}
	return nil
}

func (_u *AuditLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(auditlog.Table, auditlog.Columns, sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OperatorType(); ok {
		_spec.SetField(auditlog.FieldOperatorType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.OperatorID(); ok {
		_spec.SetField(auditlog.FieldOperatorID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedOperatorID(); ok {
		_spec.AddField(auditlog.FieldOperatorID, field.TypeUint64, value)
	}
	if _u.mutation.OperatorIDCleared() {
		_spec.ClearField(auditlog.FieldOperatorID, field.TypeUint64)
	}
	if value, ok := _u.mutation.PermissionPoint(); ok {
		_spec.SetField(auditlog.FieldPermissionPoint, field.TypeString, value)
	}
	if _u.mutation.PermissionPointCleared() {
		_spec.ClearField(auditlog.FieldPermissionPoint, field.TypeString)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(auditlog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.Route(); ok {
		_spec.SetField(auditlog.FieldRoute, field.TypeString, value)
	}
	if value, ok := _u.mutation.Before(); ok {
		_spec.SetField(auditlog.FieldBefore, field.TypeJSON, value)
	}
	if _u.mutation.BeforeCleared() {
		_spec.ClearField(auditlog.FieldBefore, field.TypeJSON)
	}
	if value, ok := _u.mutation.After(); ok {
		_spec.SetField(auditlog.FieldAfter, field.TypeJSON, value)
	}
	if _u.mutation.AfterCleared() {
		_spec.ClearField(auditlog.FieldAfter, field.TypeJSON)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(auditlog.FieldIP, field.TypeString, value)
	}
	if _u.mutation.IPCleared() {
		_spec.ClearField(auditlog.FieldIP, field.TypeString)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(auditlog.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(auditlog.FieldUserAgent, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuditLogUpdateOne is the builder for updating a single AuditLog entity.
type AuditLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuditLogMutation
}

// SetOperatorType sets the "operator_type" field.
func (_u *AuditLogUpdateOne) SetOperatorType(v auditlog.OperatorType) *AuditLogUpdateOne {
	_u.mutation.SetOperatorType(v)
	return _u
}

// SetNillableOperatorType sets the "operator_type" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableOperatorType(v *auditlog.OperatorType) *AuditLogUpdateOne {
	if v != nil {
		_u.SetOperatorType(*v)
	}
	return _u
}

// SetOperatorID sets the "operator_id" field.
func (_u *AuditLogUpdateOne) SetOperatorID(v uint64) *AuditLogUpdateOne {
	_u.mutation.ResetOperatorID()
	_u.mutation.SetOperatorID(v)
	return _u
}

// SetNillableOperatorID sets the "operator_id" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableOperatorID(v *uint64) *AuditLogUpdateOne {
	if v != nil {
		_u.SetOperatorID(*v)
	}
	return _u
}

// AddOperatorID adds value to the "operator_id" field.
func (_u *AuditLogUpdateOne) AddOperatorID(v int64) *AuditLogUpdateOne {
	_u.mutation.AddOperatorID(v)
	return _u
}

// ClearOperatorID clears the value of the "operator_id" field.
func (_u *AuditLogUpdateOne) ClearOperatorID() *AuditLogUpdateOne {
	_u.mutation.ClearOperatorID()
	return _u
}

// SetPermissionPoint sets the "permission_point" field.
func (_u *AuditLogUpdateOne) SetPermissionPoint(v string) *AuditLogUpdateOne {
	_u.mutation.SetPermissionPoint(v)
	return _u
}

// SetNillablePermissionPoint sets the "permission_point" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillablePermissionPoint(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetPermissionPoint(*v)
	}
	return _u
}

// ClearPermissionPoint clears the value of the "permission_point" field.
func (_u *AuditLogUpdateOne) ClearPermissionPoint() *AuditLogUpdateOne {
	_u.mutation.ClearPermissionPoint()
	return _u
}

// SetAction sets the "action" field.
func (_u *AuditLogUpdateOne) SetAction(v string) *AuditLogUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableAction(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetRoute sets the "route" field.
func (_u *AuditLogUpdateOne) SetRoute(v string) *AuditLogUpdateOne {
	_u.mutation.SetRoute(v)
	return _u
}

// SetNillableRoute sets the "route" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableRoute(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetRoute(*v)
	}
	return _u
}

// SetBefore sets the "before" field.
func (_u *AuditLogUpdateOne) SetBefore(v map[string]interface{}) *AuditLogUpdateOne {
	_u.mutation.SetBefore(v)
	return _u
}

// ClearBefore clears the value of the "before" field.
func (_u *AuditLogUpdateOne) ClearBefore() *AuditLogUpdateOne {
	_u.mutation.ClearBefore()
	return _u
}

// SetAfter sets the "after" field.
func (_u *AuditLogUpdateOne) SetAfter(v map[string]interface{}) *AuditLogUpdateOne {
	_u.mutation.SetAfter(v)
	return _u
}

// ClearAfter clears the value of the "after" field.
func (_u *AuditLogUpdateOne) ClearAfter() *AuditLogUpdateOne {
	_u.mutation.ClearAfter()
	return _u
}

// SetIP sets the "ip" field.
func (_u *AuditLogUpdateOne) SetIP(v string) *AuditLogUpdateOne {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableIP(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// ClearIP clears the value of the "ip" field.
func (_u *AuditLogUpdateOne) ClearIP() *AuditLogUpdateOne {
	_u.mutation.ClearIP()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *AuditLogUpdateOne) SetUserAgent(v string) *AuditLogUpdateOne {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableUserAgent(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *AuditLogUpdateOne) ClearUserAgent() *AuditLogUpdateOne {
	_u.mutation.ClearUserAgent()
	return _u
}

// Mutation returns the AuditLogMutation object of the builder.
func (_u *AuditLogUpdateOne) Mutation() *AuditLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the AuditLogUpdate builder.
func (_u *AuditLogUpdateOne) Where(ps ...predicate.AuditLog) *AuditLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuditLogUpdateOne) Select(field string, fields ...string) *AuditLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AuditLog entity.
func (_u *AuditLogUpdateOne) Save(ctx context.Context) (*AuditLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuditLogUpdateOne) SaveX(ctx context.Context) *AuditLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuditLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuditLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuditLogUpdateOne) check() error {
	if v, ok := _u.mutation.OperatorType(); ok {
		if err := auditlog.OperatorTypeValidator(v); err != nil {
			return &ValidationError{Name: "operator_type", err: fmt.Errorf(`ent: validator failed for field "AuditLog.operator_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PermissionPoint(); ok {
		if err := auditlog.PermissionPointValidator(v); err != nil {
			return &ValidationError{Name: "permission_point", err: fmt.Errorf(`ent: validator failed for field "AuditLog.permission_point": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Action(); ok {
		if err := auditlog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "AuditLog.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Route(); ok {
		if err := auditlog.RouteValidator(v); err != nil {
			return &ValidationError{Name: "route", err: fmt.Errorf(`ent: validator failed for field "AuditLog.route": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IP(); ok {
		if err := auditlog.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "AuditLog.ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserAgent(); ok {
		if err := auditlog.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "AuditLog.user_agent": %w`, err)}
		}
	}
	return nil
}

func (_u *AuditLogUpdateOne) sqlSave(ctx context.Context) (_node *AuditLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(auditlog.Table, auditlog.Columns, sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuditLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, auditlog.FieldID)
		for _, f := range fields {
			if !auditlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != auditlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OperatorType(); ok {
		_spec.SetField(auditlog.FieldOperatorType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.OperatorID(); ok {
		_spec.SetField(auditlog.FieldOperatorID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedOperatorID(); ok {
		_spec.AddField(auditlog.FieldOperatorID, field.TypeUint64, value)
	}
	if _u.mutation.OperatorIDCleared() {
		_spec.ClearField(auditlog.FieldOperatorID, field.TypeUint64)
	}
	if value, ok := _u.mutation.PermissionPoint(); ok {
		_spec.SetField(auditlog.FieldPermissionPoint, field.TypeString, value)
	}
	if _u.mutation.PermissionPointCleared() {
		_spec.ClearField(auditlog.FieldPermissionPoint, field.TypeString)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(auditlog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.Route(); ok {
		_spec.SetField(auditlog.FieldRoute, field.TypeString, value)
	}
	if value, ok := _u.mutation.Before(); ok {
		_spec.SetField(auditlog.FieldBefore, field.TypeJSON, value)
	}
	if _u.mutation.BeforeCleared() {
		_spec.ClearField(auditlog.FieldBefore, field.TypeJSON)
	}
	if value, ok := _u.mutation.After(); ok {
		_spec.SetField(auditlog.FieldAfter, field.TypeJSON, value)
	}
	if _u.mutation.AfterCleared() {
		_spec.ClearField(auditlog.FieldAfter, field.TypeJSON)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(auditlog.FieldIP, field.TypeString, value)
	}
	if _u.mutation.IPCleared() {
		_spec.ClearField(auditlog.FieldIP, field.TypeString)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(auditlog.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(auditlog.FieldUserAgent, field.TypeString)
	}
	_node = &AuditLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
