// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NovaWorks/zcard-next/server/internal/data/ent/card"
	"github.com/NovaWorks/zcard-next/server/internal/data/ent/predicate"
	"github.com/NovaWorks/zcard-next/server/internal/data/ent/product"
)

// CardUpdate is the builder for updating Card entities.
type CardUpdate struct {
	config
	hooks    []Hook
	mutation *CardMutation
}

// Where appends a list predicates to the CardUpdate builder.
func (_u *CardUpdate) Where(ps ...predicate.Card) *CardUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CardUpdate) SetUpdatedAt(v time.Time) *CardUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSubsiteID sets the "subsite_id" field.
func (_u *CardUpdate) SetSubsiteID(v uint64) *CardUpdate {
	_u.mutation.ResetSubsiteID()
	_u.mutation.SetSubsiteID(v)
	return _u
}

// SetNillableSubsiteID sets the "subsite_id" field if the given value is not nil.
func (_u *CardUpdate) SetNillableSubsiteID(v *uint64) *CardUpdate {
	if v != nil {
		_u.SetSubsiteID(*v)
	}
	return _u
}

// AddSubsiteID adds value to the "subsite_id" field.
func (_u *CardUpdate) AddSubsiteID(v int64) *CardUpdate {
	_u.mutation.AddSubsiteID(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *CardUpdate) SetVersion(v int32) *CardUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *CardUpdate) SetNillableVersion(v *int32) *CardUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *CardUpdate) AddVersion(v int32) *CardUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *CardUpdate) SetProductID(v uint64) *CardUpdate {
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *CardUpdate) SetNillableProductID(v *uint64) *CardUpdate {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *CardUpdate) SetContent(v []byte) *CardUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetContentHash sets the "content_hash" field.
func (_u *CardUpdate) SetContentHash(v string) *CardUpdate {
	_u.mutation.SetContentHash(v)
	return _u
}

// SetNillableContentHash sets the "content_hash" field if the given value is not nil.
func (_u *CardUpdate) SetNillableContentHash(v *string) *CardUpdate {
	if v != nil {
		_u.SetContentHash(*v)
	}
	return _u
}

// SetNumberHash sets the "number_hash" field.
func (_u *CardUpdate) SetNumberHash(v string) *CardUpdate {
	_u.mutation.SetNumberHash(v)
	return _u
}

// SetNillableNumberHash sets the "number_hash" field if the given value is not nil.
func (_u *CardUpdate) SetNillableNumberHash(v *string) *CardUpdate {
	if v != nil {
		_u.SetNumberHash(*v)
	}
	return _u
}

// ClearNumberHash clears the value of the "number_hash" field.
func (_u *CardUpdate) ClearNumberHash() *CardUpdate {
	_u.mutation.ClearNumberHash()
	return _u
}

// SetStatus sets the "status" field.
func (_u *CardUpdate) SetStatus(v card.Status) *CardUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CardUpdate) SetNillableStatus(v *card.Status) *CardUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *CardUpdate) SetOrderID(v uint64) *CardUpdate {
	_u.mutation.ResetOrderID()
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *CardUpdate) SetNillableOrderID(v *uint64) *CardUpdate {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// AddOrderID adds value to the "order_id" field.
func (_u *CardUpdate) AddOrderID(v int64) *CardUpdate {
	_u.mutation.AddOrderID(v)
	return _u
}

// ClearOrderID clears the value of the "order_id" field.
func (_u *CardUpdate) ClearOrderID() *CardUpdate {
	_u.mutation.ClearOrderID()
	return _u
}

// SetSkuID sets the "sku_id" field.
func (_u *CardUpdate) SetSkuID(v uint64) *CardUpdate {
	_u.mutation.ResetSkuID()
	_u.mutation.SetSkuID(v)
	return _u
}

// SetNillableSkuID sets the "sku_id" field if the given value is not nil.
func (_u *CardUpdate) SetNillableSkuID(v *uint64) *CardUpdate {
	if v != nil {
		_u.SetSkuID(*v)
	}
	return _u
}

// AddSkuID adds value to the "sku_id" field.
func (_u *CardUpdate) AddSkuID(v int64) *CardUpdate {
	_u.mutation.AddSkuID(v)
	return _u
}

// ClearSkuID clears the value of the "sku_id" field.
func (_u *CardUpdate) ClearSkuID() *CardUpdate {
	_u.mutation.ClearSkuID()
	return _u
}

// SetImportID sets the "import_id" field.
func (_u *CardUpdate) SetImportID(v uint64) *CardUpdate {
	_u.mutation.ResetImportID()
	_u.mutation.SetImportID(v)
	return _u
}

// SetNillableImportID sets the "import_id" field if the given value is not nil.
func (_u *CardUpdate) SetNillableImportID(v *uint64) *CardUpdate {
	if v != nil {
		_u.SetImportID(*v)
	}
	return _u
}

// AddImportID adds value to the "import_id" field.
func (_u *CardUpdate) AddImportID(v int64) *CardUpdate {
	_u.mutation.AddImportID(v)
	return _u
}

// ClearImportID clears the value of the "import_id" field.
func (_u *CardUpdate) ClearImportID() *CardUpdate {
	_u.mutation.ClearImportID()
	return _u
}

// SetCardType sets the "card_type" field.
func (_u *CardUpdate) SetCardType(v string) *CardUpdate {
	_u.mutation.SetCardType(v)
	return _u
}

// SetNillableCardType sets the "card_type" field if the given value is not nil.
func (_u *CardUpdate) SetNillableCardType(v *string) *CardUpdate {
	if v != nil {
		_u.SetCardType(*v)
	}
	return _u
}

// ClearCardType clears the value of the "card_type" field.
func (_u *CardUpdate) ClearCardType() *CardUpdate {
	_u.mutation.ClearCardType()
	return _u
}

// SetNote sets the "note" field.
func (_u *CardUpdate) SetNote(v string) *CardUpdate {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *CardUpdate) SetNillableNote(v *string) *CardUpdate {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *CardUpdate) ClearNote() *CardUpdate {
	_u.mutation.ClearNote()
	return _u
}

// SetOwnerID sets the "owner_id" field.
func (_u *CardUpdate) SetOwnerID(v uint64) *CardUpdate {
	_u.mutation.ResetOwnerID()
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *CardUpdate) SetNillableOwnerID(v *uint64) *CardUpdate {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// AddOwnerID adds value to the "owner_id" field.
func (_u *CardUpdate) AddOwnerID(v int64) *CardUpdate {
	_u.mutation.AddOwnerID(v)
	return _u
}

// SetDraftPremium sets the "draft_premium" field.
func (_u *CardUpdate) SetDraftPremium(v int64) *CardUpdate {
	_u.mutation.ResetDraftPremium()
	_u.mutation.SetDraftPremium(v)
	return _u
}

// SetNillableDraftPremium sets the "draft_premium" field if the given value is not nil.
func (_u *CardUpdate) SetNillableDraftPremium(v *int64) *CardUpdate {
	if v != nil {
		_u.SetDraftPremium(*v)
	}
	return _u
}

// AddDraftPremium adds value to the "draft_premium" field.
func (_u *CardUpdate) AddDraftPremium(v int64) *CardUpdate {
	_u.mutation.AddDraftPremium(v)
	return _u
}

// SetDraftCost sets the "draft_cost" field.
func (_u *CardUpdate) SetDraftCost(v int64) *CardUpdate {
	_u.mutation.ResetDraftCost()
	_u.mutation.SetDraftCost(v)
	return _u
}

// SetNillableDraftCost sets the "draft_cost" field if the given value is not nil.
func (_u *CardUpdate) SetNillableDraftCost(v *int64) *CardUpdate {
	if v != nil {
		_u.SetDraftCost(*v)
	}
	return _u
}

// AddDraftCost adds value to the "draft_cost" field.
func (_u *CardUpdate) AddDraftCost(v int64) *CardUpdate {
	_u.mutation.AddDraftCost(v)
	return _u
}

// SetPrice sets the "price" field.
func (_u *CardUpdate) SetPrice(v int64) *CardUpdate {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *CardUpdate) SetNillablePrice(v *int64) *CardUpdate {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *CardUpdate) AddPrice(v int64) *CardUpdate {
	_u.mutation.AddPrice(v)
	return _u
}

// ClearPrice clears the value of the "price" field.
func (_u *CardUpdate) ClearPrice() *CardUpdate {
	_u.mutation.ClearPrice()
	return _u
}

// SetLockedAt sets the "locked_at" field.
func (_u *CardUpdate) SetLockedAt(v time.Time) *CardUpdate {
	_u.mutation.SetLockedAt(v)
	return _u
}

// SetNillableLockedAt sets the "locked_at" field if the given value is not nil.
func (_u *CardUpdate) SetNillableLockedAt(v *time.Time) *CardUpdate {
	if v != nil {
		_u.SetLockedAt(*v)
	}
	return _u
}

// ClearLockedAt clears the value of the "locked_at" field.
func (_u *CardUpdate) ClearLockedAt() *CardUpdate {
	_u.mutation.ClearLockedAt()
	return _u
}

// SetUsedAt sets the "used_at" field.
func (_u *CardUpdate) SetUsedAt(v time.Time) *CardUpdate {
	_u.mutation.SetUsedAt(v)
	return _u
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_u *CardUpdate) SetNillableUsedAt(v *time.Time) *CardUpdate {
	if v != nil {
		_u.SetUsedAt(*v)
	}
	return _u
}

// ClearUsedAt clears the value of the "used_at" field.
func (_u *CardUpdate) ClearUsedAt() *CardUpdate {
	_u.mutation.ClearUsedAt()
	return _u
}

// SetProduct sets the "product" edge to the Product entity.
func (_u *CardUpdate) SetProduct(v *Product) *CardUpdate {
	return _u.SetProductID(v.ID)
}

// Mutation returns the CardMutation object of the builder.
func (_u *CardUpdate) Mutation() *CardMutation {
	return _u.mutation
}

// ClearProduct clears the "product" edge to the Product entity.
func (_u *CardUpdate) ClearProduct() *CardUpdate {
	_u.mutation.ClearProduct()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CardUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CardUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CardUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CardUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CardUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := card.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CardUpdate) check() error {
	if v, ok := _u.mutation.ContentHash(); ok {
		if err := card.ContentHashValidator(v); err != nil {
			return &ValidationError{Name: "content_hash", err: fmt.Errorf(`ent: validator failed for field "Card.content_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NumberHash(); ok {
		if err := card.NumberHashValidator(v); err != nil {
			return &ValidationError{Name: "number_hash", err: fmt.Errorf(`ent: validator failed for field "Card.number_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := card.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Card.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CardType(); ok {
		if err := card.CardTypeValidator(v); err != nil {
			return &ValidationError{Name: "card_type", err: fmt.Errorf(`ent: validator failed for field "Card.card_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Note(); ok {
		if err := card.NoteValidator(v); err != nil {
			return &ValidationError{Name: "note", err: fmt.Errorf(`ent: validator failed for field "Card.note": %w`, err)}
		}
	}
	if _u.mutation.ProductCleared() && len(_u.mutation.ProductIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Card.product"`)
	}
	return nil
}

func (_u *CardUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(card.Table, card.Columns, sqlgraph.NewFieldSpec(card.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(card.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SubsiteID(); ok {
		_spec.SetField(card.FieldSubsiteID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedSubsiteID(); ok {
		_spec.AddField(card.FieldSubsiteID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(card.FieldVersion, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(card.FieldVersion, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(card.FieldContent, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.ContentHash(); ok {
		_spec.SetField(card.FieldContentHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.NumberHash(); ok {
		_spec.SetField(card.FieldNumberHash, field.TypeString, value)
	}
	if _u.mutation.NumberHashCleared() {
		_spec.ClearField(card.FieldNumberHash, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(card.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.OrderID(); ok {
		_spec.SetField(card.FieldOrderID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedOrderID(); ok {
		_spec.AddField(card.FieldOrderID, field.TypeUint64, value)
	}
	if _u.mutation.OrderIDCleared() {
		_spec.ClearField(card.FieldOrderID, field.TypeUint64)
	}
	if value, ok := _u.mutation.SkuID(); ok {
		_spec.SetField(card.FieldSkuID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedSkuID(); ok {
		_spec.AddField(card.FieldSkuID, field.TypeUint64, value)
	}
	if _u.mutation.SkuIDCleared() {
		_spec.ClearField(card.FieldSkuID, field.TypeUint64)
	}
	if value, ok := _u.mutation.ImportID(); ok {
		_spec.SetField(card.FieldImportID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedImportID(); ok {
		_spec.AddField(card.FieldImportID, field.TypeUint64, value)
	}
	if _u.mutation.ImportIDCleared() {
		_spec.ClearField(card.FieldImportID, field.TypeUint64)
	}
	if value, ok := _u.mutation.CardType(); ok {
		_spec.SetField(card.FieldCardType, field.TypeString, value)
	}
	if _u.mutation.CardTypeCleared() {
		_spec.ClearField(card.FieldCardType, field.TypeString)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(card.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(card.FieldNote, field.TypeString)
	}
	if value, ok := _u.mutation.OwnerID(); ok {
		_spec.SetField(card.FieldOwnerID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedOwnerID(); ok {
		_spec.AddField(card.FieldOwnerID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.DraftPremium(); ok {
		_spec.SetField(card.FieldDraftPremium, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDraftPremium(); ok {
		_spec.AddField(card.FieldDraftPremium, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DraftCost(); ok {
		_spec.SetField(card.FieldDraftCost, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDraftCost(); ok {
		_spec.AddField(card.FieldDraftCost, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(card.FieldPrice, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(card.FieldPrice, field.TypeInt64, value)
	}
	if _u.mutation.PriceCleared() {
		_spec.ClearField(card.FieldPrice, field.TypeInt64)
	}
	if value, ok := _u.mutation.LockedAt(); ok {
		_spec.SetField(card.FieldLockedAt, field.TypeTime, value)
	}
	if _u.mutation.LockedAtCleared() {
		_spec.ClearField(card.FieldLockedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UsedAt(); ok {
		_spec.SetField(card.FieldUsedAt, field.TypeTime, value)
	}
	if _u.mutation.UsedAtCleared() {
		_spec.ClearField(card.FieldUsedAt, field.TypeTime)
	}
	if _u.mutation.ProductCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   card.ProductTable,
			Columns: []string{card.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   card.ProductTable,
			Columns: []string{card.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{card.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CardUpdateOne is the builder for updating a single Card entity.
type CardUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CardMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CardUpdateOne) SetUpdatedAt(v time.Time) *CardUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSubsiteID sets the "subsite_id" field.
func (_u *CardUpdateOne) SetSubsiteID(v uint64) *CardUpdateOne {
	_u.mutation.ResetSubsiteID()
	_u.mutation.SetSubsiteID(v)
	return _u
}

// SetNillableSubsiteID sets the "subsite_id" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableSubsiteID(v *uint64) *CardUpdateOne {
	if v != nil {
		_u.SetSubsiteID(*v)
	}
	return _u
}

// AddSubsiteID adds value to the "subsite_id" field.
func (_u *CardUpdateOne) AddSubsiteID(v int64) *CardUpdateOne {
	_u.mutation.AddSubsiteID(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *CardUpdateOne) SetVersion(v int32) *CardUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableVersion(v *int32) *CardUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *CardUpdateOne) AddVersion(v int32) *CardUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *CardUpdateOne) SetProductID(v uint64) *CardUpdateOne {
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableProductID(v *uint64) *CardUpdateOne {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *CardUpdateOne) SetContent(v []byte) *CardUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetContentHash sets the "content_hash" field.
func (_u *CardUpdateOne) SetContentHash(v string) *CardUpdateOne {
	_u.mutation.SetContentHash(v)
	return _u
}

// SetNillableContentHash sets the "content_hash" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableContentHash(v *string) *CardUpdateOne {
	if v != nil {
		_u.SetContentHash(*v)
	}
	return _u
}

// SetNumberHash sets the "number_hash" field.
func (_u *CardUpdateOne) SetNumberHash(v string) *CardUpdateOne {
	_u.mutation.SetNumberHash(v)
	return _u
}

// SetNillableNumberHash sets the "number_hash" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableNumberHash(v *string) *CardUpdateOne {
	if v != nil {
		_u.SetNumberHash(*v)
	}
	return _u
}

// ClearNumberHash clears the value of the "number_hash" field.
func (_u *CardUpdateOne) ClearNumberHash() *CardUpdateOne {
	_u.mutation.ClearNumberHash()
	return _u
}

// SetStatus sets the "status" field.
func (_u *CardUpdateOne) SetStatus(v card.Status) *CardUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableStatus(v *card.Status) *CardUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *CardUpdateOne) SetOrderID(v uint64) *CardUpdateOne {
	_u.mutation.ResetOrderID()
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableOrderID(v *uint64) *CardUpdateOne {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// AddOrderID adds value to the "order_id" field.
func (_u *CardUpdateOne) AddOrderID(v int64) *CardUpdateOne {
	_u.mutation.AddOrderID(v)
	return _u
}

// ClearOrderID clears the value of the "order_id" field.
func (_u *CardUpdateOne) ClearOrderID() *CardUpdateOne {
	_u.mutation.ClearOrderID()
	return _u
}

// SetSkuID sets the "sku_id" field.
func (_u *CardUpdateOne) SetSkuID(v uint64) *CardUpdateOne {
	_u.mutation.ResetSkuID()
	_u.mutation.SetSkuID(v)
	return _u
}

// SetNillableSkuID sets the "sku_id" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableSkuID(v *uint64) *CardUpdateOne {
	if v != nil {
		_u.SetSkuID(*v)
	}
	return _u
}

// AddSkuID adds value to the "sku_id" field.
func (_u *CardUpdateOne) AddSkuID(v int64) *CardUpdateOne {
	_u.mutation.AddSkuID(v)
	return _u
}

// ClearSkuID clears the value of the "sku_id" field.
func (_u *CardUpdateOne) ClearSkuID() *CardUpdateOne {
	_u.mutation.ClearSkuID()
	return _u
}

// SetImportID sets the "import_id" field.
func (_u *CardUpdateOne) SetImportID(v uint64) *CardUpdateOne {
	_u.mutation.ResetImportID()
	_u.mutation.SetImportID(v)
	return _u
}

// SetNillableImportID sets the "import_id" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableImportID(v *uint64) *CardUpdateOne {
	if v != nil {
		_u.SetImportID(*v)
	}
	return _u
}

// AddImportID adds value to the "import_id" field.
func (_u *CardUpdateOne) AddImportID(v int64) *CardUpdateOne {
	_u.mutation.AddImportID(v)
	return _u
}

// ClearImportID clears the value of the "import_id" field.
func (_u *CardUpdateOne) ClearImportID() *CardUpdateOne {
	_u.mutation.ClearImportID()
	return _u
}

// SetCardType sets the "card_type" field.
func (_u *CardUpdateOne) SetCardType(v string) *CardUpdateOne {
	_u.mutation.SetCardType(v)
	return _u
}

// SetNillableCardType sets the "card_type" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableCardType(v *string) *CardUpdateOne {
	if v != nil {
		_u.SetCardType(*v)
	}
	return _u
}

// ClearCardType clears the value of the "card_type" field.
func (_u *CardUpdateOne) ClearCardType() *CardUpdateOne {
	_u.mutation.ClearCardType()
	return _u
}

// SetNote sets the "note" field.
func (_u *CardUpdateOne) SetNote(v string) *CardUpdateOne {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableNote(v *string) *CardUpdateOne {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *CardUpdateOne) ClearNote() *CardUpdateOne {
	_u.mutation.ClearNote()
	return _u
}

// SetOwnerID sets the "owner_id" field.
func (_u *CardUpdateOne) SetOwnerID(v uint64) *CardUpdateOne {
	_u.mutation.ResetOwnerID()
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableOwnerID(v *uint64) *CardUpdateOne {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// AddOwnerID adds value to the "owner_id" field.
func (_u *CardUpdateOne) AddOwnerID(v int64) *CardUpdateOne {
	_u.mutation.AddOwnerID(v)
	return _u
}

// SetDraftPremium sets the "draft_premium" field.
func (_u *CardUpdateOne) SetDraftPremium(v int64) *CardUpdateOne {
	_u.mutation.ResetDraftPremium()
	_u.mutation.SetDraftPremium(v)
	return _u
}

// SetNillableDraftPremium sets the "draft_premium" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableDraftPremium(v *int64) *CardUpdateOne {
	if v != nil {
		_u.SetDraftPremium(*v)
	}
	return _u
}

// AddDraftPremium adds value to the "draft_premium" field.
func (_u *CardUpdateOne) AddDraftPremium(v int64) *CardUpdateOne {
	_u.mutation.AddDraftPremium(v)
	return _u
}

// SetDraftCost sets the "draft_cost" field.
func (_u *CardUpdateOne) SetDraftCost(v int64) *CardUpdateOne {
	_u.mutation.ResetDraftCost()
	_u.mutation.SetDraftCost(v)
	return _u
}

// SetNillableDraftCost sets the "draft_cost" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableDraftCost(v *int64) *CardUpdateOne {
	if v != nil {
		_u.SetDraftCost(*v)
	}
	return _u
}

// AddDraftCost adds value to the "draft_cost" field.
func (_u *CardUpdateOne) AddDraftCost(v int64) *CardUpdateOne {
	_u.mutation.AddDraftCost(v)
	return _u
}

// SetPrice sets the "price" field.
func (_u *CardUpdateOne) SetPrice(v int64) *CardUpdateOne {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillablePrice(v *int64) *CardUpdateOne {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *CardUpdateOne) AddPrice(v int64) *CardUpdateOne {
	_u.mutation.AddPrice(v)
	return _u
}

// ClearPrice clears the value of the "price" field.
func (_u *CardUpdateOne) ClearPrice() *CardUpdateOne {
	_u.mutation.ClearPrice()
	return _u
}

// SetLockedAt sets the "locked_at" field.
func (_u *CardUpdateOne) SetLockedAt(v time.Time) *CardUpdateOne {
	_u.mutation.SetLockedAt(v)
	return _u
}

// SetNillableLockedAt sets the "locked_at" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableLockedAt(v *time.Time) *CardUpdateOne {
	if v != nil {
		_u.SetLockedAt(*v)
	}
	return _u
}

// ClearLockedAt clears the value of the "locked_at" field.
func (_u *CardUpdateOne) ClearLockedAt() *CardUpdateOne {
	_u.mutation.ClearLockedAt()
	return _u
}

// SetUsedAt sets the "used_at" field.
func (_u *CardUpdateOne) SetUsedAt(v time.Time) *CardUpdateOne {
	_u.mutation.SetUsedAt(v)
	return _u
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableUsedAt(v *time.Time) *CardUpdateOne {
	if v != nil {
		_u.SetUsedAt(*v)
	}
	return _u
}

// ClearUsedAt clears the value of the "used_at" field.
func (_u *CardUpdateOne) ClearUsedAt() *CardUpdateOne {
	_u.mutation.ClearUsedAt()
	return _u
}

// SetProduct sets the "product" edge to the Product entity.
func (_u *CardUpdateOne) SetProduct(v *Product) *CardUpdateOne {
	return _u.SetProductID(v.ID)
}

// Mutation returns the CardMutation object of the builder.
func (_u *CardUpdateOne) Mutation() *CardMutation {
	return _u.mutation
}

// ClearProduct clears the "product" edge to the Product entity.
func (_u *CardUpdateOne) ClearProduct() *CardUpdateOne {
	_u.mutation.ClearProduct()
	return _u
}

// Where appends a list predicates to the CardUpdate builder.
func (_u *CardUpdateOne) Where(ps ...predicate.Card) *CardUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CardUpdateOne) Select(field string, fields ...string) *CardUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Card entity.
func (_u *CardUpdateOne) Save(ctx context.Context) (*Card, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CardUpdateOne) SaveX(ctx context.Context) *Card {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CardUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CardUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CardUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := card.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CardUpdateOne) check() error {
	if v, ok := _u.mutation.ContentHash(); ok {
		if err := card.ContentHashValidator(v); err != nil {
			return &ValidationError{Name: "content_hash", err: fmt.Errorf(`ent: validator failed for field "Card.content_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NumberHash(); ok {
		if err := card.NumberHashValidator(v); err != nil {
			return &ValidationError{Name: "number_hash", err: fmt.Errorf(`ent: validator failed for field "Card.number_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := card.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Card.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CardType(); ok {
		if err := card.CardTypeValidator(v); err != nil {
			return &ValidationError{Name: "card_type", err: fmt.Errorf(`ent: validator failed for field "Card.card_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Note(); ok {
		if err := card.NoteValidator(v); err != nil {
			return &ValidationError{Name: "note", err: fmt.Errorf(`ent: validator failed for field "Card.note": %w`, err)}
		}
	}
	if _u.mutation.ProductCleared() && len(_u.mutation.ProductIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Card.product"`)
	}
	return nil
}

func (_u *CardUpdateOne) sqlSave(ctx context.Context) (_node *Card, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(card.Table, card.Columns, sqlgraph.NewFieldSpec(card.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Card.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, card.FieldID)
		for _, f := range fields {
			if !card.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != card.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(card.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SubsiteID(); ok {
		_spec.SetField(card.FieldSubsiteID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedSubsiteID(); ok {
		_spec.AddField(card.FieldSubsiteID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(card.FieldVersion, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(card.FieldVersion, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(card.FieldContent, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.ContentHash(); ok {
		_spec.SetField(card.FieldContentHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.NumberHash(); ok {
		_spec.SetField(card.FieldNumberHash, field.TypeString, value)
	}
	if _u.mutation.NumberHashCleared() {
		_spec.ClearField(card.FieldNumberHash, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(card.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.OrderID(); ok {
		_spec.SetField(card.FieldOrderID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedOrderID(); ok {
		_spec.AddField(card.FieldOrderID, field.TypeUint64, value)
	}
	if _u.mutation.OrderIDCleared() {
		_spec.ClearField(card.FieldOrderID, field.TypeUint64)
	}
	if value, ok := _u.mutation.SkuID(); ok {
		_spec.SetField(card.FieldSkuID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedSkuID(); ok {
		_spec.AddField(card.FieldSkuID, field.TypeUint64, value)
	}
	if _u.mutation.SkuIDCleared() {
		_spec.ClearField(card.FieldSkuID, field.TypeUint64)
	}
	if value, ok := _u.mutation.ImportID(); ok {
		_spec.SetField(card.FieldImportID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedImportID(); ok {
		_spec.AddField(card.FieldImportID, field.TypeUint64, value)
	}
	if _u.mutation.ImportIDCleared() {
		_spec.ClearField(card.FieldImportID, field.TypeUint64)
	}
	if value, ok := _u.mutation.CardType(); ok {
		_spec.SetField(card.FieldCardType, field.TypeString, value)
	}
	if _u.mutation.CardTypeCleared() {
		_spec.ClearField(card.FieldCardType, field.TypeString)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(card.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(card.FieldNote, field.TypeString)
	}
	if value, ok := _u.mutation.OwnerID(); ok {
		_spec.SetField(card.FieldOwnerID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedOwnerID(); ok {
		_spec.AddField(card.FieldOwnerID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.DraftPremium(); ok {
		_spec.SetField(card.FieldDraftPremium, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDraftPremium(); ok {
		_spec.AddField(card.FieldDraftPremium, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DraftCost(); ok {
		_spec.SetField(card.FieldDraftCost, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDraftCost(); ok {
		_spec.AddField(card.FieldDraftCost, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(card.FieldPrice, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(card.FieldPrice, field.TypeInt64, value)
	}
	if _u.mutation.PriceCleared() {
		_spec.ClearField(card.FieldPrice, field.TypeInt64)
	}
	if value, ok := _u.mutation.LockedAt(); ok {
		_spec.SetField(card.FieldLockedAt, field.TypeTime, value)
	}
	if _u.mutation.LockedAtCleared() {
		_spec.ClearField(card.FieldLockedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UsedAt(); ok {
		_spec.SetField(card.FieldUsedAt, field.TypeTime, value)
	}
	if _u.mutation.UsedAtCleared() {
		_spec.ClearField(card.FieldUsedAt, field.TypeTime)
	}
	if _u.mutation.ProductCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   card.ProductTable,
			Columns: []string{card.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   card.ProductTable,
			Columns: []string{card.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Card{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{card.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
