// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/NovaWorks/zcard-next/server/internal/data/ent/pluginoperation"
	"github.com/NovaWorks/zcard-next/server/internal/data/ent/predicate"
)

// PluginOperationUpdate is the builder for updating PluginOperation entities.
type PluginOperationUpdate struct {
	config
	hooks    []Hook
	mutation *PluginOperationMutation
}

// Where appends a list predicates to the PluginOperationUpdate builder.
func (_u *PluginOperationUpdate) Where(ps ...predicate.PluginOperation) *PluginOperationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PluginOperationUpdate) SetUpdatedAt(v time.Time) *PluginOperationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOperationID sets the "operation_id" field.
func (_u *PluginOperationUpdate) SetOperationID(v string) *PluginOperationUpdate {
	_u.mutation.SetOperationID(v)
	return _u
}

// SetNillableOperationID sets the "operation_id" field if the given value is not nil.
func (_u *PluginOperationUpdate) SetNillableOperationID(v *string) *PluginOperationUpdate {
	if v != nil {
		_u.SetOperationID(*v)
	}
	return _u
}

// SetPluginID sets the "plugin_id" field.
func (_u *PluginOperationUpdate) SetPluginID(v string) *PluginOperationUpdate {
	_u.mutation.SetPluginID(v)
	return _u
}

// SetNillablePluginID sets the "plugin_id" field if the given value is not nil.
func (_u *PluginOperationUpdate) SetNillablePluginID(v *string) *PluginOperationUpdate {
	if v != nil {
		_u.SetPluginID(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *PluginOperationUpdate) SetAction(v string) *PluginOperationUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *PluginOperationUpdate) SetNillableAction(v *string) *PluginOperationUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetRequestSha256 sets the "request_sha256" field.
func (_u *PluginOperationUpdate) SetRequestSha256(v string) *PluginOperationUpdate {
	_u.mutation.SetRequestSha256(v)
	return _u
}

// SetNillableRequestSha256 sets the "request_sha256" field if the given value is not nil.
func (_u *PluginOperationUpdate) SetNillableRequestSha256(v *string) *PluginOperationUpdate {
	if v != nil {
		_u.SetRequestSha256(*v)
	}
	return _u
}

// SetActorID sets the "actor_id" field.
func (_u *PluginOperationUpdate) SetActorID(v uint64) *PluginOperationUpdate {
	_u.mutation.ResetActorID()
	_u.mutation.SetActorID(v)
	return _u
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (_u *PluginOperationUpdate) SetNillableActorID(v *uint64) *PluginOperationUpdate {
	if v != nil {
		_u.SetActorID(*v)
	}
	return _u
}

// AddActorID adds value to the "actor_id" field.
func (_u *PluginOperationUpdate) AddActorID(v int64) *PluginOperationUpdate {
	_u.mutation.AddActorID(v)
	return _u
}

// SetSubsiteID sets the "subsite_id" field.
func (_u *PluginOperationUpdate) SetSubsiteID(v uint64) *PluginOperationUpdate {
	_u.mutation.ResetSubsiteID()
	_u.mutation.SetSubsiteID(v)
	return _u
}

// SetNillableSubsiteID sets the "subsite_id" field if the given value is not nil.
func (_u *PluginOperationUpdate) SetNillableSubsiteID(v *uint64) *PluginOperationUpdate {
	if v != nil {
		_u.SetSubsiteID(*v)
	}
	return _u
}

// AddSubsiteID adds value to the "subsite_id" field.
func (_u *PluginOperationUpdate) AddSubsiteID(v int64) *PluginOperationUpdate {
	_u.mutation.AddSubsiteID(v)
	return _u
}

// SetExpectedGeneration sets the "expected_generation" field.
func (_u *PluginOperationUpdate) SetExpectedGeneration(v int64) *PluginOperationUpdate {
	_u.mutation.ResetExpectedGeneration()
	_u.mutation.SetExpectedGeneration(v)
	return _u
}

// SetNillableExpectedGeneration sets the "expected_generation" field if the given value is not nil.
func (_u *PluginOperationUpdate) SetNillableExpectedGeneration(v *int64) *PluginOperationUpdate {
	if v != nil {
		_u.SetExpectedGeneration(*v)
	}
	return _u
}

// AddExpectedGeneration adds value to the "expected_generation" field.
func (_u *PluginOperationUpdate) AddExpectedGeneration(v int64) *PluginOperationUpdate {
	_u.mutation.AddExpectedGeneration(v)
	return _u
}

// SetTargetGeneration sets the "target_generation" field.
func (_u *PluginOperationUpdate) SetTargetGeneration(v int64) *PluginOperationUpdate {
	_u.mutation.ResetTargetGeneration()
	_u.mutation.SetTargetGeneration(v)
	return _u
}

// SetNillableTargetGeneration sets the "target_generation" field if the given value is not nil.
func (_u *PluginOperationUpdate) SetNillableTargetGeneration(v *int64) *PluginOperationUpdate {
	if v != nil {
		_u.SetTargetGeneration(*v)
	}
	return _u
}

// AddTargetGeneration adds value to the "target_generation" field.
func (_u *PluginOperationUpdate) AddTargetGeneration(v int64) *PluginOperationUpdate {
	_u.mutation.AddTargetGeneration(v)
	return _u
}

// SetTargetDigest sets the "target_digest" field.
func (_u *PluginOperationUpdate) SetTargetDigest(v string) *PluginOperationUpdate {
	_u.mutation.SetTargetDigest(v)
	return _u
}

// SetNillableTargetDigest sets the "target_digest" field if the given value is not nil.
func (_u *PluginOperationUpdate) SetNillableTargetDigest(v *string) *PluginOperationUpdate {
	if v != nil {
		_u.SetTargetDigest(*v)
	}
	return _u
}

// SetApprovedScopes sets the "approved_scopes" field.
func (_u *PluginOperationUpdate) SetApprovedScopes(v []string) *PluginOperationUpdate {
	_u.mutation.SetApprovedScopes(v)
	return _u
}

// AppendApprovedScopes appends value to the "approved_scopes" field.
func (_u *PluginOperationUpdate) AppendApprovedScopes(v []string) *PluginOperationUpdate {
	_u.mutation.AppendApprovedScopes(v)
	return _u
}

// ClearApprovedScopes clears the value of the "approved_scopes" field.
func (_u *PluginOperationUpdate) ClearApprovedScopes() *PluginOperationUpdate {
	_u.mutation.ClearApprovedScopes()
	return _u
}

// SetPhase sets the "phase" field.
func (_u *PluginOperationUpdate) SetPhase(v string) *PluginOperationUpdate {
	_u.mutation.SetPhase(v)
	return _u
}

// SetNillablePhase sets the "phase" field if the given value is not nil.
func (_u *PluginOperationUpdate) SetNillablePhase(v *string) *PluginOperationUpdate {
	if v != nil {
		_u.SetPhase(*v)
	}
	return _u
}

// SetFailureCode sets the "failure_code" field.
func (_u *PluginOperationUpdate) SetFailureCode(v string) *PluginOperationUpdate {
	_u.mutation.SetFailureCode(v)
	return _u
}

// SetNillableFailureCode sets the "failure_code" field if the given value is not nil.
func (_u *PluginOperationUpdate) SetNillableFailureCode(v *string) *PluginOperationUpdate {
	if v != nil {
		_u.SetFailureCode(*v)
	}
	return _u
}

// Mutation returns the PluginOperationMutation object of the builder.
func (_u *PluginOperationUpdate) Mutation() *PluginOperationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PluginOperationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PluginOperationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PluginOperationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PluginOperationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PluginOperationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := pluginoperation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PluginOperationUpdate) check() error {
	if v, ok := _u.mutation.OperationID(); ok {
		if err := pluginoperation.OperationIDValidator(v); err != nil {
			return &ValidationError{Name: "operation_id", err: fmt.Errorf(`ent: validator failed for field "PluginOperation.operation_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PluginID(); ok {
		if err := pluginoperation.PluginIDValidator(v); err != nil {
			return &ValidationError{Name: "plugin_id", err: fmt.Errorf(`ent: validator failed for field "PluginOperation.plugin_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Action(); ok {
		if err := pluginoperation.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "PluginOperation.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestSha256(); ok {
		if err := pluginoperation.RequestSha256Validator(v); err != nil {
			return &ValidationError{Name: "request_sha256", err: fmt.Errorf(`ent: validator failed for field "PluginOperation.request_sha256": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExpectedGeneration(); ok {
		if err := pluginoperation.ExpectedGenerationValidator(v); err != nil {
			return &ValidationError{Name: "expected_generation", err: fmt.Errorf(`ent: validator failed for field "PluginOperation.expected_generation": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetGeneration(); ok {
		if err := pluginoperation.TargetGenerationValidator(v); err != nil {
			return &ValidationError{Name: "target_generation", err: fmt.Errorf(`ent: validator failed for field "PluginOperation.target_generation": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetDigest(); ok {
		if err := pluginoperation.TargetDigestValidator(v); err != nil {
			return &ValidationError{Name: "target_digest", err: fmt.Errorf(`ent: validator failed for field "PluginOperation.target_digest": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Phase(); ok {
		if err := pluginoperation.PhaseValidator(v); err != nil {
			return &ValidationError{Name: "phase", err: fmt.Errorf(`ent: validator failed for field "PluginOperation.phase": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FailureCode(); ok {
		if err := pluginoperation.FailureCodeValidator(v); err != nil {
			return &ValidationError{Name: "failure_code", err: fmt.Errorf(`ent: validator failed for field "PluginOperation.failure_code": %w`, err)}
		}
	}
	return nil
}

func (_u *PluginOperationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pluginoperation.Table, pluginoperation.Columns, sqlgraph.NewFieldSpec(pluginoperation.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(pluginoperation.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OperationID(); ok {
		_spec.SetField(pluginoperation.FieldOperationID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PluginID(); ok {
		_spec.SetField(pluginoperation.FieldPluginID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(pluginoperation.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestSha256(); ok {
		_spec.SetField(pluginoperation.FieldRequestSha256, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActorID(); ok {
		_spec.SetField(pluginoperation.FieldActorID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedActorID(); ok {
		_spec.AddField(pluginoperation.FieldActorID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.SubsiteID(); ok {
		_spec.SetField(pluginoperation.FieldSubsiteID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedSubsiteID(); ok {
		_spec.AddField(pluginoperation.FieldSubsiteID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.ExpectedGeneration(); ok {
		_spec.SetField(pluginoperation.FieldExpectedGeneration, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedExpectedGeneration(); ok {
		_spec.AddField(pluginoperation.FieldExpectedGeneration, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TargetGeneration(); ok {
		_spec.SetField(pluginoperation.FieldTargetGeneration, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTargetGeneration(); ok {
		_spec.AddField(pluginoperation.FieldTargetGeneration, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TargetDigest(); ok {
		_spec.SetField(pluginoperation.FieldTargetDigest, field.TypeString, value)
	}
	if value, ok := _u.mutation.ApprovedScopes(); ok {
		_spec.SetField(pluginoperation.FieldApprovedScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedApprovedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, pluginoperation.FieldApprovedScopes, value)
		})
	}
	if _u.mutation.ApprovedScopesCleared() {
		_spec.ClearField(pluginoperation.FieldApprovedScopes, field.TypeJSON)
	}
	if value, ok := _u.mutation.Phase(); ok {
		_spec.SetField(pluginoperation.FieldPhase, field.TypeString, value)
	}
	if value, ok := _u.mutation.FailureCode(); ok {
		_spec.SetField(pluginoperation.FieldFailureCode, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pluginoperation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PluginOperationUpdateOne is the builder for updating a single PluginOperation entity.
type PluginOperationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PluginOperationMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PluginOperationUpdateOne) SetUpdatedAt(v time.Time) *PluginOperationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOperationID sets the "operation_id" field.
func (_u *PluginOperationUpdateOne) SetOperationID(v string) *PluginOperationUpdateOne {
	_u.mutation.SetOperationID(v)
	return _u
}

// SetNillableOperationID sets the "operation_id" field if the given value is not nil.
func (_u *PluginOperationUpdateOne) SetNillableOperationID(v *string) *PluginOperationUpdateOne {
	if v != nil {
		_u.SetOperationID(*v)
	}
	return _u
}

// SetPluginID sets the "plugin_id" field.
func (_u *PluginOperationUpdateOne) SetPluginID(v string) *PluginOperationUpdateOne {
	_u.mutation.SetPluginID(v)
	return _u
}

// SetNillablePluginID sets the "plugin_id" field if the given value is not nil.
func (_u *PluginOperationUpdateOne) SetNillablePluginID(v *string) *PluginOperationUpdateOne {
	if v != nil {
		_u.SetPluginID(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *PluginOperationUpdateOne) SetAction(v string) *PluginOperationUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *PluginOperationUpdateOne) SetNillableAction(v *string) *PluginOperationUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetRequestSha256 sets the "request_sha256" field.
func (_u *PluginOperationUpdateOne) SetRequestSha256(v string) *PluginOperationUpdateOne {
	_u.mutation.SetRequestSha256(v)
	return _u
}

// SetNillableRequestSha256 sets the "request_sha256" field if the given value is not nil.
func (_u *PluginOperationUpdateOne) SetNillableRequestSha256(v *string) *PluginOperationUpdateOne {
	if v != nil {
		_u.SetRequestSha256(*v)
	}
	return _u
}

// SetActorID sets the "actor_id" field.
func (_u *PluginOperationUpdateOne) SetActorID(v uint64) *PluginOperationUpdateOne {
	_u.mutation.ResetActorID()
	_u.mutation.SetActorID(v)
	return _u
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (_u *PluginOperationUpdateOne) SetNillableActorID(v *uint64) *PluginOperationUpdateOne {
	if v != nil {
		_u.SetActorID(*v)
	}
	return _u
}

// AddActorID adds value to the "actor_id" field.
func (_u *PluginOperationUpdateOne) AddActorID(v int64) *PluginOperationUpdateOne {
	_u.mutation.AddActorID(v)
	return _u
}

// SetSubsiteID sets the "subsite_id" field.
func (_u *PluginOperationUpdateOne) SetSubsiteID(v uint64) *PluginOperationUpdateOne {
	_u.mutation.ResetSubsiteID()
	_u.mutation.SetSubsiteID(v)
	return _u
}

// SetNillableSubsiteID sets the "subsite_id" field if the given value is not nil.
func (_u *PluginOperationUpdateOne) SetNillableSubsiteID(v *uint64) *PluginOperationUpdateOne {
	if v != nil {
		_u.SetSubsiteID(*v)
	}
	return _u
}

// AddSubsiteID adds value to the "subsite_id" field.
func (_u *PluginOperationUpdateOne) AddSubsiteID(v int64) *PluginOperationUpdateOne {
	_u.mutation.AddSubsiteID(v)
	return _u
}

// SetExpectedGeneration sets the "expected_generation" field.
func (_u *PluginOperationUpdateOne) SetExpectedGeneration(v int64) *PluginOperationUpdateOne {
	_u.mutation.ResetExpectedGeneration()
	_u.mutation.SetExpectedGeneration(v)
	return _u
}

// SetNillableExpectedGeneration sets the "expected_generation" field if the given value is not nil.
func (_u *PluginOperationUpdateOne) SetNillableExpectedGeneration(v *int64) *PluginOperationUpdateOne {
	if v != nil {
		_u.SetExpectedGeneration(*v)
	}
	return _u
}

// AddExpectedGeneration adds value to the "expected_generation" field.
func (_u *PluginOperationUpdateOne) AddExpectedGeneration(v int64) *PluginOperationUpdateOne {
	_u.mutation.AddExpectedGeneration(v)
	return _u
}

// SetTargetGeneration sets the "target_generation" field.
func (_u *PluginOperationUpdateOne) SetTargetGeneration(v int64) *PluginOperationUpdateOne {
	_u.mutation.ResetTargetGeneration()
	_u.mutation.SetTargetGeneration(v)
	return _u
}

// SetNillableTargetGeneration sets the "target_generation" field if the given value is not nil.
func (_u *PluginOperationUpdateOne) SetNillableTargetGeneration(v *int64) *PluginOperationUpdateOne {
	if v != nil {
		_u.SetTargetGeneration(*v)
	}
	return _u
}

// AddTargetGeneration adds value to the "target_generation" field.
func (_u *PluginOperationUpdateOne) AddTargetGeneration(v int64) *PluginOperationUpdateOne {
	_u.mutation.AddTargetGeneration(v)
	return _u
}

// SetTargetDigest sets the "target_digest" field.
func (_u *PluginOperationUpdateOne) SetTargetDigest(v string) *PluginOperationUpdateOne {
	_u.mutation.SetTargetDigest(v)
	return _u
}

// SetNillableTargetDigest sets the "target_digest" field if the given value is not nil.
func (_u *PluginOperationUpdateOne) SetNillableTargetDigest(v *string) *PluginOperationUpdateOne {
	if v != nil {
		_u.SetTargetDigest(*v)
	}
	return _u
}

// SetApprovedScopes sets the "approved_scopes" field.
func (_u *PluginOperationUpdateOne) SetApprovedScopes(v []string) *PluginOperationUpdateOne {
	_u.mutation.SetApprovedScopes(v)
	return _u
}

// AppendApprovedScopes appends value to the "approved_scopes" field.
func (_u *PluginOperationUpdateOne) AppendApprovedScopes(v []string) *PluginOperationUpdateOne {
	_u.mutation.AppendApprovedScopes(v)
	return _u
}

// ClearApprovedScopes clears the value of the "approved_scopes" field.
func (_u *PluginOperationUpdateOne) ClearApprovedScopes() *PluginOperationUpdateOne {
	_u.mutation.ClearApprovedScopes()
	return _u
}

// SetPhase sets the "phase" field.
func (_u *PluginOperationUpdateOne) SetPhase(v string) *PluginOperationUpdateOne {
	_u.mutation.SetPhase(v)
	return _u
}

// SetNillablePhase sets the "phase" field if the given value is not nil.
func (_u *PluginOperationUpdateOne) SetNillablePhase(v *string) *PluginOperationUpdateOne {
	if v != nil {
		_u.SetPhase(*v)
	}
	return _u
}

// SetFailureCode sets the "failure_code" field.
func (_u *PluginOperationUpdateOne) SetFailureCode(v string) *PluginOperationUpdateOne {
	_u.mutation.SetFailureCode(v)
	return _u
}

// SetNillableFailureCode sets the "failure_code" field if the given value is not nil.
func (_u *PluginOperationUpdateOne) SetNillableFailureCode(v *string) *PluginOperationUpdateOne {
	if v != nil {
		_u.SetFailureCode(*v)
	}
	return _u
}

// Mutation returns the PluginOperationMutation object of the builder.
func (_u *PluginOperationUpdateOne) Mutation() *PluginOperationMutation {
	return _u.mutation
}

// Where appends a list predicates to the PluginOperationUpdate builder.
func (_u *PluginOperationUpdateOne) Where(ps ...predicate.PluginOperation) *PluginOperationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PluginOperationUpdateOne) Select(field string, fields ...string) *PluginOperationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PluginOperation entity.
func (_u *PluginOperationUpdateOne) Save(ctx context.Context) (*PluginOperation, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PluginOperationUpdateOne) SaveX(ctx context.Context) *PluginOperation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PluginOperationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PluginOperationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PluginOperationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := pluginoperation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PluginOperationUpdateOne) check() error {
	if v, ok := _u.mutation.OperationID(); ok {
		if err := pluginoperation.OperationIDValidator(v); err != nil {
			return &ValidationError{Name: "operation_id", err: fmt.Errorf(`ent: validator failed for field "PluginOperation.operation_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PluginID(); ok {
		if err := pluginoperation.PluginIDValidator(v); err != nil {
			return &ValidationError{Name: "plugin_id", err: fmt.Errorf(`ent: validator failed for field "PluginOperation.plugin_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Action(); ok {
		if err := pluginoperation.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "PluginOperation.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestSha256(); ok {
		if err := pluginoperation.RequestSha256Validator(v); err != nil {
			return &ValidationError{Name: "request_sha256", err: fmt.Errorf(`ent: validator failed for field "PluginOperation.request_sha256": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExpectedGeneration(); ok {
		if err := pluginoperation.ExpectedGenerationValidator(v); err != nil {
			return &ValidationError{Name: "expected_generation", err: fmt.Errorf(`ent: validator failed for field "PluginOperation.expected_generation": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetGeneration(); ok {
		if err := pluginoperation.TargetGenerationValidator(v); err != nil {
			return &ValidationError{Name: "target_generation", err: fmt.Errorf(`ent: validator failed for field "PluginOperation.target_generation": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetDigest(); ok {
		if err := pluginoperation.TargetDigestValidator(v); err != nil {
			return &ValidationError{Name: "target_digest", err: fmt.Errorf(`ent: validator failed for field "PluginOperation.target_digest": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Phase(); ok {
		if err := pluginoperation.PhaseValidator(v); err != nil {
			return &ValidationError{Name: "phase", err: fmt.Errorf(`ent: validator failed for field "PluginOperation.phase": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FailureCode(); ok {
		if err := pluginoperation.FailureCodeValidator(v); err != nil {
			return &ValidationError{Name: "failure_code", err: fmt.Errorf(`ent: validator failed for field "PluginOperation.failure_code": %w`, err)}
		}
	}
	return nil
}

func (_u *PluginOperationUpdateOne) sqlSave(ctx context.Context) (_node *PluginOperation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pluginoperation.Table, pluginoperation.Columns, sqlgraph.NewFieldSpec(pluginoperation.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PluginOperation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pluginoperation.FieldID)
		for _, f := range fields {
			if !pluginoperation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pluginoperation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(pluginoperation.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OperationID(); ok {
		_spec.SetField(pluginoperation.FieldOperationID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PluginID(); ok {
		_spec.SetField(pluginoperation.FieldPluginID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(pluginoperation.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestSha256(); ok {
		_spec.SetField(pluginoperation.FieldRequestSha256, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActorID(); ok {
		_spec.SetField(pluginoperation.FieldActorID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedActorID(); ok {
		_spec.AddField(pluginoperation.FieldActorID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.SubsiteID(); ok {
		_spec.SetField(pluginoperation.FieldSubsiteID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedSubsiteID(); ok {
		_spec.AddField(pluginoperation.FieldSubsiteID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.ExpectedGeneration(); ok {
		_spec.SetField(pluginoperation.FieldExpectedGeneration, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedExpectedGeneration(); ok {
		_spec.AddField(pluginoperation.FieldExpectedGeneration, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TargetGeneration(); ok {
		_spec.SetField(pluginoperation.FieldTargetGeneration, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTargetGeneration(); ok {
		_spec.AddField(pluginoperation.FieldTargetGeneration, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TargetDigest(); ok {
		_spec.SetField(pluginoperation.FieldTargetDigest, field.TypeString, value)
	}
	if value, ok := _u.mutation.ApprovedScopes(); ok {
		_spec.SetField(pluginoperation.FieldApprovedScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedApprovedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, pluginoperation.FieldApprovedScopes, value)
		})
	}
	if _u.mutation.ApprovedScopesCleared() {
		_spec.ClearField(pluginoperation.FieldApprovedScopes, field.TypeJSON)
	}
	if value, ok := _u.mutation.Phase(); ok {
		_spec.SetField(pluginoperation.FieldPhase, field.TypeString, value)
	}
	if value, ok := _u.mutation.FailureCode(); ok {
		_spec.SetField(pluginoperation.FieldFailureCode, field.TypeString, value)
	}
	_node = &PluginOperation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pluginoperation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
