// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NovaWorks/zcard-next/server/internal/data/ent/procurementitem"
)

// ProcurementItemCreate is the builder for creating a ProcurementItem entity.
type ProcurementItemCreate struct {
	config
	mutation *ProcurementItemMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProcurementItemCreate) SetCreatedAt(v time.Time) *ProcurementItemCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProcurementItemCreate) SetNillableCreatedAt(v *time.Time) *ProcurementItemCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProcurementItemCreate) SetUpdatedAt(v time.Time) *ProcurementItemCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProcurementItemCreate) SetNillableUpdatedAt(v *time.Time) *ProcurementItemCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetProcurementID sets the "procurement_id" field.
func (_c *ProcurementItemCreate) SetProcurementID(v uint64) *ProcurementItemCreate {
	_c.mutation.SetProcurementID(v)
	return _c
}

// SetUpstreamSku sets the "upstream_sku" field.
func (_c *ProcurementItemCreate) SetUpstreamSku(v string) *ProcurementItemCreate {
	_c.mutation.SetUpstreamSku(v)
	return _c
}

// SetNillableUpstreamSku sets the "upstream_sku" field if the given value is not nil.
func (_c *ProcurementItemCreate) SetNillableUpstreamSku(v *string) *ProcurementItemCreate {
	if v != nil {
		_c.SetUpstreamSku(*v)
	}
	return _c
}

// SetQuantity sets the "quantity" field.
func (_c *ProcurementItemCreate) SetQuantity(v int32) *ProcurementItemCreate {
	_c.mutation.SetQuantity(v)
	return _c
}

// SetUnitCost sets the "unit_cost" field.
func (_c *ProcurementItemCreate) SetUnitCost(v int64) *ProcurementItemCreate {
	_c.mutation.SetUnitCost(v)
	return _c
}

// SetNillableUnitCost sets the "unit_cost" field if the given value is not nil.
func (_c *ProcurementItemCreate) SetNillableUnitCost(v *int64) *ProcurementItemCreate {
	if v != nil {
		_c.SetUnitCost(*v)
	}
	return _c
}

// SetReceivedContent sets the "received_content" field.
func (_c *ProcurementItemCreate) SetReceivedContent(v []byte) *ProcurementItemCreate {
	_c.mutation.SetReceivedContent(v)
	return _c
}

// SetID sets the "id" field.
func (_c *ProcurementItemCreate) SetID(v uint64) *ProcurementItemCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ProcurementItemMutation object of the builder.
func (_c *ProcurementItemCreate) Mutation() *ProcurementItemMutation {
	return _c.mutation
}

// Save creates the ProcurementItem in the database.
func (_c *ProcurementItemCreate) Save(ctx context.Context) (*ProcurementItem, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProcurementItemCreate) SaveX(ctx context.Context) *ProcurementItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProcurementItemCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProcurementItemCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProcurementItemCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := procurementitem.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := procurementitem.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.UpstreamSku(); !ok {
		v := procurementitem.DefaultUpstreamSku
		_c.mutation.SetUpstreamSku(v)
	}
	if _, ok := _c.mutation.UnitCost(); !ok {
		v := procurementitem.DefaultUnitCost
		_c.mutation.SetUnitCost(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProcurementItemCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProcurementItem.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ProcurementItem.updated_at"`)}
	}
	if _, ok := _c.mutation.ProcurementID(); !ok {
		return &ValidationError{Name: "procurement_id", err: errors.New(`ent: missing required field "ProcurementItem.procurement_id"`)}
	}
	if _, ok := _c.mutation.UpstreamSku(); !ok {
		return &ValidationError{Name: "upstream_sku", err: errors.New(`ent: missing required field "ProcurementItem.upstream_sku"`)}
	}
	if v, ok := _c.mutation.UpstreamSku(); ok {
		if err := procurementitem.UpstreamSkuValidator(v); err != nil {
			return &ValidationError{Name: "upstream_sku", err: fmt.Errorf(`ent: validator failed for field "ProcurementItem.upstream_sku": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Quantity(); !ok {
		return &ValidationError{Name: "quantity", err: errors.New(`ent: missing required field "ProcurementItem.quantity"`)}
	}
	if _, ok := _c.mutation.UnitCost(); !ok {
		return &ValidationError{Name: "unit_cost", err: errors.New(`ent: missing required field "ProcurementItem.unit_cost"`)}
	}
	return nil
}

func (_c *ProcurementItemCreate) sqlSave(ctx context.Context) (*ProcurementItem, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProcurementItemCreate) createSpec() (*ProcurementItem, *sqlgraph.CreateSpec) {
	var (
		_node = &ProcurementItem{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(procurementitem.Table, sqlgraph.NewFieldSpec(procurementitem.FieldID, field.TypeUint64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(procurementitem.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(procurementitem.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ProcurementID(); ok {
		_spec.SetField(procurementitem.FieldProcurementID, field.TypeUint64, value)
		_node.ProcurementID = value
	}
	if value, ok := _c.mutation.UpstreamSku(); ok {
		_spec.SetField(procurementitem.FieldUpstreamSku, field.TypeString, value)
		_node.UpstreamSku = value
	}
	if value, ok := _c.mutation.Quantity(); ok {
		_spec.SetField(procurementitem.FieldQuantity, field.TypeInt32, value)
		_node.Quantity = value
	}
	if value, ok := _c.mutation.UnitCost(); ok {
		_spec.SetField(procurementitem.FieldUnitCost, field.TypeInt64, value)
		_node.UnitCost = value
	}
	if value, ok := _c.mutation.ReceivedContent(); ok {
		_spec.SetField(procurementitem.FieldReceivedContent, field.TypeBytes, value)
		_node.ReceivedContent = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProcurementItem.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProcurementItemUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ProcurementItemCreate) OnConflict(opts ...sql.ConflictOption) *ProcurementItemUpsertOne {
	_c.conflict = opts
	return &ProcurementItemUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProcurementItem.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProcurementItemCreate) OnConflictColumns(columns ...string) *ProcurementItemUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProcurementItemUpsertOne{
		create: _c,
	}
}

type (
	// ProcurementItemUpsertOne is the builder for "upsert"-ing
	//  one ProcurementItem node.
	ProcurementItemUpsertOne struct {
		create *ProcurementItemCreate
	}

	// ProcurementItemUpsert is the "OnConflict" setter.
	ProcurementItemUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ProcurementItemUpsert) SetUpdatedAt(v time.Time) *ProcurementItemUpsert {
	u.Set(procurementitem.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProcurementItemUpsert) UpdateUpdatedAt() *ProcurementItemUpsert {
	u.SetExcluded(procurementitem.FieldUpdatedAt)
	return u
}

// SetProcurementID sets the "procurement_id" field.
func (u *ProcurementItemUpsert) SetProcurementID(v uint64) *ProcurementItemUpsert {
	u.Set(procurementitem.FieldProcurementID, v)
	return u
}

// UpdateProcurementID sets the "procurement_id" field to the value that was provided on create.
func (u *ProcurementItemUpsert) UpdateProcurementID() *ProcurementItemUpsert {
	u.SetExcluded(procurementitem.FieldProcurementID)
	return u
}

// AddProcurementID adds v to the "procurement_id" field.
func (u *ProcurementItemUpsert) AddProcurementID(v uint64) *ProcurementItemUpsert {
	u.Add(procurementitem.FieldProcurementID, v)
	return u
}

// SetUpstreamSku sets the "upstream_sku" field.
func (u *ProcurementItemUpsert) SetUpstreamSku(v string) *ProcurementItemUpsert {
	u.Set(procurementitem.FieldUpstreamSku, v)
	return u
}

// UpdateUpstreamSku sets the "upstream_sku" field to the value that was provided on create.
func (u *ProcurementItemUpsert) UpdateUpstreamSku() *ProcurementItemUpsert {
	u.SetExcluded(procurementitem.FieldUpstreamSku)
	return u
}

// SetQuantity sets the "quantity" field.
func (u *ProcurementItemUpsert) SetQuantity(v int32) *ProcurementItemUpsert {
	u.Set(procurementitem.FieldQuantity, v)
	return u
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *ProcurementItemUpsert) UpdateQuantity() *ProcurementItemUpsert {
	u.SetExcluded(procurementitem.FieldQuantity)
	return u
}

// AddQuantity adds v to the "quantity" field.
func (u *ProcurementItemUpsert) AddQuantity(v int32) *ProcurementItemUpsert {
	u.Add(procurementitem.FieldQuantity, v)
	return u
}

// SetUnitCost sets the "unit_cost" field.
func (u *ProcurementItemUpsert) SetUnitCost(v int64) *ProcurementItemUpsert {
	u.Set(procurementitem.FieldUnitCost, v)
	return u
}

// UpdateUnitCost sets the "unit_cost" field to the value that was provided on create.
func (u *ProcurementItemUpsert) UpdateUnitCost() *ProcurementItemUpsert {
	u.SetExcluded(procurementitem.FieldUnitCost)
	return u
}

// AddUnitCost adds v to the "unit_cost" field.
func (u *ProcurementItemUpsert) AddUnitCost(v int64) *ProcurementItemUpsert {
	u.Add(procurementitem.FieldUnitCost, v)
	return u
}

// SetReceivedContent sets the "received_content" field.
func (u *ProcurementItemUpsert) SetReceivedContent(v []byte) *ProcurementItemUpsert {
	u.Set(procurementitem.FieldReceivedContent, v)
	return u
}

// UpdateReceivedContent sets the "received_content" field to the value that was provided on create.
func (u *ProcurementItemUpsert) UpdateReceivedContent() *ProcurementItemUpsert {
	u.SetExcluded(procurementitem.FieldReceivedContent)
	return u
}

// ClearReceivedContent clears the value of the "received_content" field.
func (u *ProcurementItemUpsert) ClearReceivedContent() *ProcurementItemUpsert {
	u.SetNull(procurementitem.FieldReceivedContent)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ProcurementItem.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(procurementitem.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ProcurementItemUpsertOne) UpdateNewValues() *ProcurementItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(procurementitem.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(procurementitem.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProcurementItem.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ProcurementItemUpsertOne) Ignore() *ProcurementItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProcurementItemUpsertOne) DoNothing() *ProcurementItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProcurementItemCreate.OnConflict
// documentation for more info.
func (u *ProcurementItemUpsertOne) Update(set func(*ProcurementItemUpsert)) *ProcurementItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProcurementItemUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProcurementItemUpsertOne) SetUpdatedAt(v time.Time) *ProcurementItemUpsertOne {
	return u.Update(func(s *ProcurementItemUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProcurementItemUpsertOne) UpdateUpdatedAt() *ProcurementItemUpsertOne {
	return u.Update(func(s *ProcurementItemUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetProcurementID sets the "procurement_id" field.
func (u *ProcurementItemUpsertOne) SetProcurementID(v uint64) *ProcurementItemUpsertOne {
	return u.Update(func(s *ProcurementItemUpsert) {
		s.SetProcurementID(v)
	})
}

// AddProcurementID adds v to the "procurement_id" field.
func (u *ProcurementItemUpsertOne) AddProcurementID(v uint64) *ProcurementItemUpsertOne {
	return u.Update(func(s *ProcurementItemUpsert) {
		s.AddProcurementID(v)
	})
}

// UpdateProcurementID sets the "procurement_id" field to the value that was provided on create.
func (u *ProcurementItemUpsertOne) UpdateProcurementID() *ProcurementItemUpsertOne {
	return u.Update(func(s *ProcurementItemUpsert) {
		s.UpdateProcurementID()
	})
}

// SetUpstreamSku sets the "upstream_sku" field.
func (u *ProcurementItemUpsertOne) SetUpstreamSku(v string) *ProcurementItemUpsertOne {
	return u.Update(func(s *ProcurementItemUpsert) {
		s.SetUpstreamSku(v)
	})
}

// UpdateUpstreamSku sets the "upstream_sku" field to the value that was provided on create.
func (u *ProcurementItemUpsertOne) UpdateUpstreamSku() *ProcurementItemUpsertOne {
	return u.Update(func(s *ProcurementItemUpsert) {
		s.UpdateUpstreamSku()
	})
}

// SetQuantity sets the "quantity" field.
func (u *ProcurementItemUpsertOne) SetQuantity(v int32) *ProcurementItemUpsertOne {
	return u.Update(func(s *ProcurementItemUpsert) {
		s.SetQuantity(v)
	})
}

// AddQuantity adds v to the "quantity" field.
func (u *ProcurementItemUpsertOne) AddQuantity(v int32) *ProcurementItemUpsertOne {
	return u.Update(func(s *ProcurementItemUpsert) {
		s.AddQuantity(v)
	})
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *ProcurementItemUpsertOne) UpdateQuantity() *ProcurementItemUpsertOne {
	return u.Update(func(s *ProcurementItemUpsert) {
		s.UpdateQuantity()
	})
}

// SetUnitCost sets the "unit_cost" field.
func (u *ProcurementItemUpsertOne) SetUnitCost(v int64) *ProcurementItemUpsertOne {
	return u.Update(func(s *ProcurementItemUpsert) {
		s.SetUnitCost(v)
	})
}

// AddUnitCost adds v to the "unit_cost" field.
func (u *ProcurementItemUpsertOne) AddUnitCost(v int64) *ProcurementItemUpsertOne {
	return u.Update(func(s *ProcurementItemUpsert) {
		s.AddUnitCost(v)
	})
}

// UpdateUnitCost sets the "unit_cost" field to the value that was provided on create.
func (u *ProcurementItemUpsertOne) UpdateUnitCost() *ProcurementItemUpsertOne {
	return u.Update(func(s *ProcurementItemUpsert) {
		s.UpdateUnitCost()
	})
}

// SetReceivedContent sets the "received_content" field.
func (u *ProcurementItemUpsertOne) SetReceivedContent(v []byte) *ProcurementItemUpsertOne {
	return u.Update(func(s *ProcurementItemUpsert) {
		s.SetReceivedContent(v)
	})
}

// UpdateReceivedContent sets the "received_content" field to the value that was provided on create.
func (u *ProcurementItemUpsertOne) UpdateReceivedContent() *ProcurementItemUpsertOne {
	return u.Update(func(s *ProcurementItemUpsert) {
		s.UpdateReceivedContent()
	})
}

// ClearReceivedContent clears the value of the "received_content" field.
func (u *ProcurementItemUpsertOne) ClearReceivedContent() *ProcurementItemUpsertOne {
	return u.Update(func(s *ProcurementItemUpsert) {
		s.ClearReceivedContent()
	})
}

// Exec executes the query.
func (u *ProcurementItemUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProcurementItemCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProcurementItemUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ProcurementItemUpsertOne) ID(ctx context.Context) (id uint64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ProcurementItemUpsertOne) IDX(ctx context.Context) uint64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ProcurementItemCreateBulk is the builder for creating many ProcurementItem entities in bulk.
type ProcurementItemCreateBulk struct {
	config
	err      error
	builders []*ProcurementItemCreate
	conflict []sql.ConflictOption
}

// Save creates the ProcurementItem entities in the database.
func (_c *ProcurementItemCreateBulk) Save(ctx context.Context) ([]*ProcurementItem, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProcurementItem, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProcurementItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProcurementItemCreateBulk) SaveX(ctx context.Context) []*ProcurementItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProcurementItemCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProcurementItemCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProcurementItem.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProcurementItemUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ProcurementItemCreateBulk) OnConflict(opts ...sql.ConflictOption) *ProcurementItemUpsertBulk {
	_c.conflict = opts
	return &ProcurementItemUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProcurementItem.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProcurementItemCreateBulk) OnConflictColumns(columns ...string) *ProcurementItemUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProcurementItemUpsertBulk{
		create: _c,
	}
}

// ProcurementItemUpsertBulk is the builder for "upsert"-ing
// a bulk of ProcurementItem nodes.
type ProcurementItemUpsertBulk struct {
	create *ProcurementItemCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ProcurementItem.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(procurementitem.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ProcurementItemUpsertBulk) UpdateNewValues() *ProcurementItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(procurementitem.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(procurementitem.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProcurementItem.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ProcurementItemUpsertBulk) Ignore() *ProcurementItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProcurementItemUpsertBulk) DoNothing() *ProcurementItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProcurementItemCreateBulk.OnConflict
// documentation for more info.
func (u *ProcurementItemUpsertBulk) Update(set func(*ProcurementItemUpsert)) *ProcurementItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProcurementItemUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProcurementItemUpsertBulk) SetUpdatedAt(v time.Time) *ProcurementItemUpsertBulk {
	return u.Update(func(s *ProcurementItemUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProcurementItemUpsertBulk) UpdateUpdatedAt() *ProcurementItemUpsertBulk {
	return u.Update(func(s *ProcurementItemUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetProcurementID sets the "procurement_id" field.
func (u *ProcurementItemUpsertBulk) SetProcurementID(v uint64) *ProcurementItemUpsertBulk {
	return u.Update(func(s *ProcurementItemUpsert) {
		s.SetProcurementID(v)
	})
}

// AddProcurementID adds v to the "procurement_id" field.
func (u *ProcurementItemUpsertBulk) AddProcurementID(v uint64) *ProcurementItemUpsertBulk {
	return u.Update(func(s *ProcurementItemUpsert) {
		s.AddProcurementID(v)
	})
}

// UpdateProcurementID sets the "procurement_id" field to the value that was provided on create.
func (u *ProcurementItemUpsertBulk) UpdateProcurementID() *ProcurementItemUpsertBulk {
	return u.Update(func(s *ProcurementItemUpsert) {
		s.UpdateProcurementID()
	})
}

// SetUpstreamSku sets the "upstream_sku" field.
func (u *ProcurementItemUpsertBulk) SetUpstreamSku(v string) *ProcurementItemUpsertBulk {
	return u.Update(func(s *ProcurementItemUpsert) {
		s.SetUpstreamSku(v)
	})
}

// UpdateUpstreamSku sets the "upstream_sku" field to the value that was provided on create.
func (u *ProcurementItemUpsertBulk) UpdateUpstreamSku() *ProcurementItemUpsertBulk {
	return u.Update(func(s *ProcurementItemUpsert) {
		s.UpdateUpstreamSku()
	})
}

// SetQuantity sets the "quantity" field.
func (u *ProcurementItemUpsertBulk) SetQuantity(v int32) *ProcurementItemUpsertBulk {
	return u.Update(func(s *ProcurementItemUpsert) {
		s.SetQuantity(v)
	})
}

// AddQuantity adds v to the "quantity" field.
func (u *ProcurementItemUpsertBulk) AddQuantity(v int32) *ProcurementItemUpsertBulk {
	return u.Update(func(s *ProcurementItemUpsert) {
		s.AddQuantity(v)
	})
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *ProcurementItemUpsertBulk) UpdateQuantity() *ProcurementItemUpsertBulk {
	return u.Update(func(s *ProcurementItemUpsert) {
		s.UpdateQuantity()
	})
}

// SetUnitCost sets the "unit_cost" field.
func (u *ProcurementItemUpsertBulk) SetUnitCost(v int64) *ProcurementItemUpsertBulk {
	return u.Update(func(s *ProcurementItemUpsert) {
		s.SetUnitCost(v)
	})
}

// AddUnitCost adds v to the "unit_cost" field.
func (u *ProcurementItemUpsertBulk) AddUnitCost(v int64) *ProcurementItemUpsertBulk {
	return u.Update(func(s *ProcurementItemUpsert) {
		s.AddUnitCost(v)
	})
}

// UpdateUnitCost sets the "unit_cost" field to the value that was provided on create.
func (u *ProcurementItemUpsertBulk) UpdateUnitCost() *ProcurementItemUpsertBulk {
	return u.Update(func(s *ProcurementItemUpsert) {
		s.UpdateUnitCost()
	})
}

// SetReceivedContent sets the "received_content" field.
func (u *ProcurementItemUpsertBulk) SetReceivedContent(v []byte) *ProcurementItemUpsertBulk {
	return u.Update(func(s *ProcurementItemUpsert) {
		s.SetReceivedContent(v)
	})
}

// UpdateReceivedContent sets the "received_content" field to the value that was provided on create.
func (u *ProcurementItemUpsertBulk) UpdateReceivedContent() *ProcurementItemUpsertBulk {
	return u.Update(func(s *ProcurementItemUpsert) {
		s.UpdateReceivedContent()
	})
}

// ClearReceivedContent clears the value of the "received_content" field.
func (u *ProcurementItemUpsertBulk) ClearReceivedContent() *ProcurementItemUpsertBulk {
	return u.Update(func(s *ProcurementItemUpsert) {
		s.ClearReceivedContent()
	})
}

// Exec executes the query.
func (u *ProcurementItemUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ProcurementItemCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProcurementItemCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProcurementItemUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
