// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NovaWorks/zcard-next/server/internal/data/ent/predicate"
	"github.com/NovaWorks/zcard-next/server/internal/data/ent/resellerrelatedaccount"
)

// ResellerRelatedAccountDelete is the builder for deleting a ResellerRelatedAccount entity.
type ResellerRelatedAccountDelete struct {
	config
	hooks    []Hook
	mutation *ResellerRelatedAccountMutation
}

// Where appends a list predicates to the ResellerRelatedAccountDelete builder.
func (_d *ResellerRelatedAccountDelete) Where(ps ...predicate.ResellerRelatedAccount) *ResellerRelatedAccountDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ResellerRelatedAccountDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ResellerRelatedAccountDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ResellerRelatedAccountDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(resellerrelatedaccount.Table, sqlgraph.NewFieldSpec(resellerrelatedaccount.FieldID, field.TypeUint64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ResellerRelatedAccountDeleteOne is the builder for deleting a single ResellerRelatedAccount entity.
type ResellerRelatedAccountDeleteOne struct {
	_d *ResellerRelatedAccountDelete
}

// Where appends a list predicates to the ResellerRelatedAccountDelete builder.
func (_d *ResellerRelatedAccountDeleteOne) Where(ps ...predicate.ResellerRelatedAccount) *ResellerRelatedAccountDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ResellerRelatedAccountDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{resellerrelatedaccount.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ResellerRelatedAccountDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
