// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NovaWorks/zcard-next/server/internal/data/ent/resellerbalanceaccount"
)

// ResellerBalanceAccountCreate is the builder for creating a ResellerBalanceAccount entity.
type ResellerBalanceAccountCreate struct {
	config
	mutation *ResellerBalanceAccountMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetSubsiteID sets the "subsite_id" field.
func (_c *ResellerBalanceAccountCreate) SetSubsiteID(v uint64) *ResellerBalanceAccountCreate {
	_c.mutation.SetSubsiteID(v)
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *ResellerBalanceAccountCreate) SetCurrency(v string) *ResellerBalanceAccountCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *ResellerBalanceAccountCreate) SetNillableCurrency(v *string) *ResellerBalanceAccountCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetAvailable sets the "available" field.
func (_c *ResellerBalanceAccountCreate) SetAvailable(v int64) *ResellerBalanceAccountCreate {
	_c.mutation.SetAvailable(v)
	return _c
}

// SetNillableAvailable sets the "available" field if the given value is not nil.
func (_c *ResellerBalanceAccountCreate) SetNillableAvailable(v *int64) *ResellerBalanceAccountCreate {
	if v != nil {
		_c.SetAvailable(*v)
	}
	return _c
}

// SetLocked sets the "locked" field.
func (_c *ResellerBalanceAccountCreate) SetLocked(v int64) *ResellerBalanceAccountCreate {
	_c.mutation.SetLocked(v)
	return _c
}

// SetNillableLocked sets the "locked" field if the given value is not nil.
func (_c *ResellerBalanceAccountCreate) SetNillableLocked(v *int64) *ResellerBalanceAccountCreate {
	if v != nil {
		_c.SetLocked(*v)
	}
	return _c
}

// SetNegative sets the "negative" field.
func (_c *ResellerBalanceAccountCreate) SetNegative(v int64) *ResellerBalanceAccountCreate {
	_c.mutation.SetNegative(v)
	return _c
}

// SetNillableNegative sets the "negative" field if the given value is not nil.
func (_c *ResellerBalanceAccountCreate) SetNillableNegative(v *int64) *ResellerBalanceAccountCreate {
	if v != nil {
		_c.SetNegative(*v)
	}
	return _c
}

// SetLastEntryID sets the "last_entry_id" field.
func (_c *ResellerBalanceAccountCreate) SetLastEntryID(v uint64) *ResellerBalanceAccountCreate {
	_c.mutation.SetLastEntryID(v)
	return _c
}

// SetNillableLastEntryID sets the "last_entry_id" field if the given value is not nil.
func (_c *ResellerBalanceAccountCreate) SetNillableLastEntryID(v *uint64) *ResellerBalanceAccountCreate {
	if v != nil {
		_c.SetLastEntryID(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ResellerBalanceAccountCreate) SetUpdatedAt(v time.Time) *ResellerBalanceAccountCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ResellerBalanceAccountCreate) SetNillableUpdatedAt(v *time.Time) *ResellerBalanceAccountCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ResellerBalanceAccountCreate) SetID(v uint64) *ResellerBalanceAccountCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ResellerBalanceAccountMutation object of the builder.
func (_c *ResellerBalanceAccountCreate) Mutation() *ResellerBalanceAccountMutation {
	return _c.mutation
}

// Save creates the ResellerBalanceAccount in the database.
func (_c *ResellerBalanceAccountCreate) Save(ctx context.Context) (*ResellerBalanceAccount, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ResellerBalanceAccountCreate) SaveX(ctx context.Context) *ResellerBalanceAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResellerBalanceAccountCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResellerBalanceAccountCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ResellerBalanceAccountCreate) defaults() {
	if _, ok := _c.mutation.Currency(); !ok {
		v := resellerbalanceaccount.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.Available(); !ok {
		v := resellerbalanceaccount.DefaultAvailable
		_c.mutation.SetAvailable(v)
	}
	if _, ok := _c.mutation.Locked(); !ok {
		v := resellerbalanceaccount.DefaultLocked
		_c.mutation.SetLocked(v)
	}
	if _, ok := _c.mutation.Negative(); !ok {
		v := resellerbalanceaccount.DefaultNegative
		_c.mutation.SetNegative(v)
	}
	if _, ok := _c.mutation.LastEntryID(); !ok {
		v := resellerbalanceaccount.DefaultLastEntryID
		_c.mutation.SetLastEntryID(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := resellerbalanceaccount.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ResellerBalanceAccountCreate) check() error {
	if _, ok := _c.mutation.SubsiteID(); !ok {
		return &ValidationError{Name: "subsite_id", err: errors.New(`ent: missing required field "ResellerBalanceAccount.subsite_id"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "ResellerBalanceAccount.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := resellerbalanceaccount.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "ResellerBalanceAccount.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Available(); !ok {
		return &ValidationError{Name: "available", err: errors.New(`ent: missing required field "ResellerBalanceAccount.available"`)}
	}
	if _, ok := _c.mutation.Locked(); !ok {
		return &ValidationError{Name: "locked", err: errors.New(`ent: missing required field "ResellerBalanceAccount.locked"`)}
	}
	if _, ok := _c.mutation.Negative(); !ok {
		return &ValidationError{Name: "negative", err: errors.New(`ent: missing required field "ResellerBalanceAccount.negative"`)}
	}
	if _, ok := _c.mutation.LastEntryID(); !ok {
		return &ValidationError{Name: "last_entry_id", err: errors.New(`ent: missing required field "ResellerBalanceAccount.last_entry_id"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ResellerBalanceAccount.updated_at"`)}
	}
	return nil
}

func (_c *ResellerBalanceAccountCreate) sqlSave(ctx context.Context) (*ResellerBalanceAccount, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ResellerBalanceAccountCreate) createSpec() (*ResellerBalanceAccount, *sqlgraph.CreateSpec) {
	var (
		_node = &ResellerBalanceAccount{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(resellerbalanceaccount.Table, sqlgraph.NewFieldSpec(resellerbalanceaccount.FieldID, field.TypeUint64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.SubsiteID(); ok {
		_spec.SetField(resellerbalanceaccount.FieldSubsiteID, field.TypeUint64, value)
		_node.SubsiteID = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(resellerbalanceaccount.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.Available(); ok {
		_spec.SetField(resellerbalanceaccount.FieldAvailable, field.TypeInt64, value)
		_node.Available = value
	}
	if value, ok := _c.mutation.Locked(); ok {
		_spec.SetField(resellerbalanceaccount.FieldLocked, field.TypeInt64, value)
		_node.Locked = value
	}
	if value, ok := _c.mutation.Negative(); ok {
		_spec.SetField(resellerbalanceaccount.FieldNegative, field.TypeInt64, value)
		_node.Negative = value
	}
	if value, ok := _c.mutation.LastEntryID(); ok {
		_spec.SetField(resellerbalanceaccount.FieldLastEntryID, field.TypeUint64, value)
		_node.LastEntryID = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(resellerbalanceaccount.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ResellerBalanceAccount.Create().
//		SetSubsiteID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ResellerBalanceAccountUpsert) {
//			SetSubsiteID(v+v).
//		}).
//		Exec(ctx)
func (_c *ResellerBalanceAccountCreate) OnConflict(opts ...sql.ConflictOption) *ResellerBalanceAccountUpsertOne {
	_c.conflict = opts
	return &ResellerBalanceAccountUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ResellerBalanceAccount.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ResellerBalanceAccountCreate) OnConflictColumns(columns ...string) *ResellerBalanceAccountUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ResellerBalanceAccountUpsertOne{
		create: _c,
	}
}

type (
	// ResellerBalanceAccountUpsertOne is the builder for "upsert"-ing
	//  one ResellerBalanceAccount node.
	ResellerBalanceAccountUpsertOne struct {
		create *ResellerBalanceAccountCreate
	}

	// ResellerBalanceAccountUpsert is the "OnConflict" setter.
	ResellerBalanceAccountUpsert struct {
		*sql.UpdateSet
	}
)

// SetSubsiteID sets the "subsite_id" field.
func (u *ResellerBalanceAccountUpsert) SetSubsiteID(v uint64) *ResellerBalanceAccountUpsert {
	u.Set(resellerbalanceaccount.FieldSubsiteID, v)
	return u
}

// UpdateSubsiteID sets the "subsite_id" field to the value that was provided on create.
func (u *ResellerBalanceAccountUpsert) UpdateSubsiteID() *ResellerBalanceAccountUpsert {
	u.SetExcluded(resellerbalanceaccount.FieldSubsiteID)
	return u
}

// AddSubsiteID adds v to the "subsite_id" field.
func (u *ResellerBalanceAccountUpsert) AddSubsiteID(v uint64) *ResellerBalanceAccountUpsert {
	u.Add(resellerbalanceaccount.FieldSubsiteID, v)
	return u
}

// SetCurrency sets the "currency" field.
func (u *ResellerBalanceAccountUpsert) SetCurrency(v string) *ResellerBalanceAccountUpsert {
	u.Set(resellerbalanceaccount.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *ResellerBalanceAccountUpsert) UpdateCurrency() *ResellerBalanceAccountUpsert {
	u.SetExcluded(resellerbalanceaccount.FieldCurrency)
	return u
}

// SetAvailable sets the "available" field.
func (u *ResellerBalanceAccountUpsert) SetAvailable(v int64) *ResellerBalanceAccountUpsert {
	u.Set(resellerbalanceaccount.FieldAvailable, v)
	return u
}

// UpdateAvailable sets the "available" field to the value that was provided on create.
func (u *ResellerBalanceAccountUpsert) UpdateAvailable() *ResellerBalanceAccountUpsert {
	u.SetExcluded(resellerbalanceaccount.FieldAvailable)
	return u
}

// AddAvailable adds v to the "available" field.
func (u *ResellerBalanceAccountUpsert) AddAvailable(v int64) *ResellerBalanceAccountUpsert {
	u.Add(resellerbalanceaccount.FieldAvailable, v)
	return u
}

// SetLocked sets the "locked" field.
func (u *ResellerBalanceAccountUpsert) SetLocked(v int64) *ResellerBalanceAccountUpsert {
	u.Set(resellerbalanceaccount.FieldLocked, v)
	return u
}

// UpdateLocked sets the "locked" field to the value that was provided on create.
func (u *ResellerBalanceAccountUpsert) UpdateLocked() *ResellerBalanceAccountUpsert {
	u.SetExcluded(resellerbalanceaccount.FieldLocked)
	return u
}

// AddLocked adds v to the "locked" field.
func (u *ResellerBalanceAccountUpsert) AddLocked(v int64) *ResellerBalanceAccountUpsert {
	u.Add(resellerbalanceaccount.FieldLocked, v)
	return u
}

// SetNegative sets the "negative" field.
func (u *ResellerBalanceAccountUpsert) SetNegative(v int64) *ResellerBalanceAccountUpsert {
	u.Set(resellerbalanceaccount.FieldNegative, v)
	return u
}

// UpdateNegative sets the "negative" field to the value that was provided on create.
func (u *ResellerBalanceAccountUpsert) UpdateNegative() *ResellerBalanceAccountUpsert {
	u.SetExcluded(resellerbalanceaccount.FieldNegative)
	return u
}

// AddNegative adds v to the "negative" field.
func (u *ResellerBalanceAccountUpsert) AddNegative(v int64) *ResellerBalanceAccountUpsert {
	u.Add(resellerbalanceaccount.FieldNegative, v)
	return u
}

// SetLastEntryID sets the "last_entry_id" field.
func (u *ResellerBalanceAccountUpsert) SetLastEntryID(v uint64) *ResellerBalanceAccountUpsert {
	u.Set(resellerbalanceaccount.FieldLastEntryID, v)
	return u
}

// UpdateLastEntryID sets the "last_entry_id" field to the value that was provided on create.
func (u *ResellerBalanceAccountUpsert) UpdateLastEntryID() *ResellerBalanceAccountUpsert {
	u.SetExcluded(resellerbalanceaccount.FieldLastEntryID)
	return u
}

// AddLastEntryID adds v to the "last_entry_id" field.
func (u *ResellerBalanceAccountUpsert) AddLastEntryID(v uint64) *ResellerBalanceAccountUpsert {
	u.Add(resellerbalanceaccount.FieldLastEntryID, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ResellerBalanceAccountUpsert) SetUpdatedAt(v time.Time) *ResellerBalanceAccountUpsert {
	u.Set(resellerbalanceaccount.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ResellerBalanceAccountUpsert) UpdateUpdatedAt() *ResellerBalanceAccountUpsert {
	u.SetExcluded(resellerbalanceaccount.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ResellerBalanceAccount.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(resellerbalanceaccount.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ResellerBalanceAccountUpsertOne) UpdateNewValues() *ResellerBalanceAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(resellerbalanceaccount.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ResellerBalanceAccount.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ResellerBalanceAccountUpsertOne) Ignore() *ResellerBalanceAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ResellerBalanceAccountUpsertOne) DoNothing() *ResellerBalanceAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ResellerBalanceAccountCreate.OnConflict
// documentation for more info.
func (u *ResellerBalanceAccountUpsertOne) Update(set func(*ResellerBalanceAccountUpsert)) *ResellerBalanceAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ResellerBalanceAccountUpsert{UpdateSet: update})
	}))
	return u
}

// SetSubsiteID sets the "subsite_id" field.
func (u *ResellerBalanceAccountUpsertOne) SetSubsiteID(v uint64) *ResellerBalanceAccountUpsertOne {
	return u.Update(func(s *ResellerBalanceAccountUpsert) {
		s.SetSubsiteID(v)
	})
}

// AddSubsiteID adds v to the "subsite_id" field.
func (u *ResellerBalanceAccountUpsertOne) AddSubsiteID(v uint64) *ResellerBalanceAccountUpsertOne {
	return u.Update(func(s *ResellerBalanceAccountUpsert) {
		s.AddSubsiteID(v)
	})
}

// UpdateSubsiteID sets the "subsite_id" field to the value that was provided on create.
func (u *ResellerBalanceAccountUpsertOne) UpdateSubsiteID() *ResellerBalanceAccountUpsertOne {
	return u.Update(func(s *ResellerBalanceAccountUpsert) {
		s.UpdateSubsiteID()
	})
}

// SetCurrency sets the "currency" field.
func (u *ResellerBalanceAccountUpsertOne) SetCurrency(v string) *ResellerBalanceAccountUpsertOne {
	return u.Update(func(s *ResellerBalanceAccountUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *ResellerBalanceAccountUpsertOne) UpdateCurrency() *ResellerBalanceAccountUpsertOne {
	return u.Update(func(s *ResellerBalanceAccountUpsert) {
		s.UpdateCurrency()
	})
}

// SetAvailable sets the "available" field.
func (u *ResellerBalanceAccountUpsertOne) SetAvailable(v int64) *ResellerBalanceAccountUpsertOne {
	return u.Update(func(s *ResellerBalanceAccountUpsert) {
		s.SetAvailable(v)
	})
}

// AddAvailable adds v to the "available" field.
func (u *ResellerBalanceAccountUpsertOne) AddAvailable(v int64) *ResellerBalanceAccountUpsertOne {
	return u.Update(func(s *ResellerBalanceAccountUpsert) {
		s.AddAvailable(v)
	})
}

// UpdateAvailable sets the "available" field to the value that was provided on create.
func (u *ResellerBalanceAccountUpsertOne) UpdateAvailable() *ResellerBalanceAccountUpsertOne {
	return u.Update(func(s *ResellerBalanceAccountUpsert) {
		s.UpdateAvailable()
	})
}

// SetLocked sets the "locked" field.
func (u *ResellerBalanceAccountUpsertOne) SetLocked(v int64) *ResellerBalanceAccountUpsertOne {
	return u.Update(func(s *ResellerBalanceAccountUpsert) {
		s.SetLocked(v)
	})
}

// AddLocked adds v to the "locked" field.
func (u *ResellerBalanceAccountUpsertOne) AddLocked(v int64) *ResellerBalanceAccountUpsertOne {
	return u.Update(func(s *ResellerBalanceAccountUpsert) {
		s.AddLocked(v)
	})
}

// UpdateLocked sets the "locked" field to the value that was provided on create.
func (u *ResellerBalanceAccountUpsertOne) UpdateLocked() *ResellerBalanceAccountUpsertOne {
	return u.Update(func(s *ResellerBalanceAccountUpsert) {
		s.UpdateLocked()
	})
}

// SetNegative sets the "negative" field.
func (u *ResellerBalanceAccountUpsertOne) SetNegative(v int64) *ResellerBalanceAccountUpsertOne {
	return u.Update(func(s *ResellerBalanceAccountUpsert) {
		s.SetNegative(v)
	})
}

// AddNegative adds v to the "negative" field.
func (u *ResellerBalanceAccountUpsertOne) AddNegative(v int64) *ResellerBalanceAccountUpsertOne {
	return u.Update(func(s *ResellerBalanceAccountUpsert) {
		s.AddNegative(v)
	})
}

// UpdateNegative sets the "negative" field to the value that was provided on create.
func (u *ResellerBalanceAccountUpsertOne) UpdateNegative() *ResellerBalanceAccountUpsertOne {
	return u.Update(func(s *ResellerBalanceAccountUpsert) {
		s.UpdateNegative()
	})
}

// SetLastEntryID sets the "last_entry_id" field.
func (u *ResellerBalanceAccountUpsertOne) SetLastEntryID(v uint64) *ResellerBalanceAccountUpsertOne {
	return u.Update(func(s *ResellerBalanceAccountUpsert) {
		s.SetLastEntryID(v)
	})
}

// AddLastEntryID adds v to the "last_entry_id" field.
func (u *ResellerBalanceAccountUpsertOne) AddLastEntryID(v uint64) *ResellerBalanceAccountUpsertOne {
	return u.Update(func(s *ResellerBalanceAccountUpsert) {
		s.AddLastEntryID(v)
	})
}

// UpdateLastEntryID sets the "last_entry_id" field to the value that was provided on create.
func (u *ResellerBalanceAccountUpsertOne) UpdateLastEntryID() *ResellerBalanceAccountUpsertOne {
	return u.Update(func(s *ResellerBalanceAccountUpsert) {
		s.UpdateLastEntryID()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ResellerBalanceAccountUpsertOne) SetUpdatedAt(v time.Time) *ResellerBalanceAccountUpsertOne {
	return u.Update(func(s *ResellerBalanceAccountUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ResellerBalanceAccountUpsertOne) UpdateUpdatedAt() *ResellerBalanceAccountUpsertOne {
	return u.Update(func(s *ResellerBalanceAccountUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ResellerBalanceAccountUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ResellerBalanceAccountCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ResellerBalanceAccountUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ResellerBalanceAccountUpsertOne) ID(ctx context.Context) (id uint64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ResellerBalanceAccountUpsertOne) IDX(ctx context.Context) uint64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ResellerBalanceAccountCreateBulk is the builder for creating many ResellerBalanceAccount entities in bulk.
type ResellerBalanceAccountCreateBulk struct {
	config
	err      error
	builders []*ResellerBalanceAccountCreate
	conflict []sql.ConflictOption
}

// Save creates the ResellerBalanceAccount entities in the database.
func (_c *ResellerBalanceAccountCreateBulk) Save(ctx context.Context) ([]*ResellerBalanceAccount, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ResellerBalanceAccount, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ResellerBalanceAccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ResellerBalanceAccountCreateBulk) SaveX(ctx context.Context) []*ResellerBalanceAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResellerBalanceAccountCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResellerBalanceAccountCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ResellerBalanceAccount.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ResellerBalanceAccountUpsert) {
//			SetSubsiteID(v+v).
//		}).
//		Exec(ctx)
func (_c *ResellerBalanceAccountCreateBulk) OnConflict(opts ...sql.ConflictOption) *ResellerBalanceAccountUpsertBulk {
	_c.conflict = opts
	return &ResellerBalanceAccountUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ResellerBalanceAccount.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ResellerBalanceAccountCreateBulk) OnConflictColumns(columns ...string) *ResellerBalanceAccountUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ResellerBalanceAccountUpsertBulk{
		create: _c,
	}
}

// ResellerBalanceAccountUpsertBulk is the builder for "upsert"-ing
// a bulk of ResellerBalanceAccount nodes.
type ResellerBalanceAccountUpsertBulk struct {
	create *ResellerBalanceAccountCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ResellerBalanceAccount.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(resellerbalanceaccount.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ResellerBalanceAccountUpsertBulk) UpdateNewValues() *ResellerBalanceAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(resellerbalanceaccount.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ResellerBalanceAccount.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ResellerBalanceAccountUpsertBulk) Ignore() *ResellerBalanceAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ResellerBalanceAccountUpsertBulk) DoNothing() *ResellerBalanceAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ResellerBalanceAccountCreateBulk.OnConflict
// documentation for more info.
func (u *ResellerBalanceAccountUpsertBulk) Update(set func(*ResellerBalanceAccountUpsert)) *ResellerBalanceAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ResellerBalanceAccountUpsert{UpdateSet: update})
	}))
	return u
}

// SetSubsiteID sets the "subsite_id" field.
func (u *ResellerBalanceAccountUpsertBulk) SetSubsiteID(v uint64) *ResellerBalanceAccountUpsertBulk {
	return u.Update(func(s *ResellerBalanceAccountUpsert) {
		s.SetSubsiteID(v)
	})
}

// AddSubsiteID adds v to the "subsite_id" field.
func (u *ResellerBalanceAccountUpsertBulk) AddSubsiteID(v uint64) *ResellerBalanceAccountUpsertBulk {
	return u.Update(func(s *ResellerBalanceAccountUpsert) {
		s.AddSubsiteID(v)
	})
}

// UpdateSubsiteID sets the "subsite_id" field to the value that was provided on create.
func (u *ResellerBalanceAccountUpsertBulk) UpdateSubsiteID() *ResellerBalanceAccountUpsertBulk {
	return u.Update(func(s *ResellerBalanceAccountUpsert) {
		s.UpdateSubsiteID()
	})
}

// SetCurrency sets the "currency" field.
func (u *ResellerBalanceAccountUpsertBulk) SetCurrency(v string) *ResellerBalanceAccountUpsertBulk {
	return u.Update(func(s *ResellerBalanceAccountUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *ResellerBalanceAccountUpsertBulk) UpdateCurrency() *ResellerBalanceAccountUpsertBulk {
	return u.Update(func(s *ResellerBalanceAccountUpsert) {
		s.UpdateCurrency()
	})
}

// SetAvailable sets the "available" field.
func (u *ResellerBalanceAccountUpsertBulk) SetAvailable(v int64) *ResellerBalanceAccountUpsertBulk {
	return u.Update(func(s *ResellerBalanceAccountUpsert) {
		s.SetAvailable(v)
	})
}

// AddAvailable adds v to the "available" field.
func (u *ResellerBalanceAccountUpsertBulk) AddAvailable(v int64) *ResellerBalanceAccountUpsertBulk {
	return u.Update(func(s *ResellerBalanceAccountUpsert) {
		s.AddAvailable(v)
	})
}

// UpdateAvailable sets the "available" field to the value that was provided on create.
func (u *ResellerBalanceAccountUpsertBulk) UpdateAvailable() *ResellerBalanceAccountUpsertBulk {
	return u.Update(func(s *ResellerBalanceAccountUpsert) {
		s.UpdateAvailable()
	})
}

// SetLocked sets the "locked" field.
func (u *ResellerBalanceAccountUpsertBulk) SetLocked(v int64) *ResellerBalanceAccountUpsertBulk {
	return u.Update(func(s *ResellerBalanceAccountUpsert) {
		s.SetLocked(v)
	})
}

// AddLocked adds v to the "locked" field.
func (u *ResellerBalanceAccountUpsertBulk) AddLocked(v int64) *ResellerBalanceAccountUpsertBulk {
	return u.Update(func(s *ResellerBalanceAccountUpsert) {
		s.AddLocked(v)
	})
}

// UpdateLocked sets the "locked" field to the value that was provided on create.
func (u *ResellerBalanceAccountUpsertBulk) UpdateLocked() *ResellerBalanceAccountUpsertBulk {
	return u.Update(func(s *ResellerBalanceAccountUpsert) {
		s.UpdateLocked()
	})
}

// SetNegative sets the "negative" field.
func (u *ResellerBalanceAccountUpsertBulk) SetNegative(v int64) *ResellerBalanceAccountUpsertBulk {
	return u.Update(func(s *ResellerBalanceAccountUpsert) {
		s.SetNegative(v)
	})
}

// AddNegative adds v to the "negative" field.
func (u *ResellerBalanceAccountUpsertBulk) AddNegative(v int64) *ResellerBalanceAccountUpsertBulk {
	return u.Update(func(s *ResellerBalanceAccountUpsert) {
		s.AddNegative(v)
	})
}

// UpdateNegative sets the "negative" field to the value that was provided on create.
func (u *ResellerBalanceAccountUpsertBulk) UpdateNegative() *ResellerBalanceAccountUpsertBulk {
	return u.Update(func(s *ResellerBalanceAccountUpsert) {
		s.UpdateNegative()
	})
}

// SetLastEntryID sets the "last_entry_id" field.
func (u *ResellerBalanceAccountUpsertBulk) SetLastEntryID(v uint64) *ResellerBalanceAccountUpsertBulk {
	return u.Update(func(s *ResellerBalanceAccountUpsert) {
		s.SetLastEntryID(v)
	})
}

// AddLastEntryID adds v to the "last_entry_id" field.
func (u *ResellerBalanceAccountUpsertBulk) AddLastEntryID(v uint64) *ResellerBalanceAccountUpsertBulk {
	return u.Update(func(s *ResellerBalanceAccountUpsert) {
		s.AddLastEntryID(v)
	})
}

// UpdateLastEntryID sets the "last_entry_id" field to the value that was provided on create.
func (u *ResellerBalanceAccountUpsertBulk) UpdateLastEntryID() *ResellerBalanceAccountUpsertBulk {
	return u.Update(func(s *ResellerBalanceAccountUpsert) {
		s.UpdateLastEntryID()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ResellerBalanceAccountUpsertBulk) SetUpdatedAt(v time.Time) *ResellerBalanceAccountUpsertBulk {
	return u.Update(func(s *ResellerBalanceAccountUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ResellerBalanceAccountUpsertBulk) UpdateUpdatedAt() *ResellerBalanceAccountUpsertBulk {
	return u.Update(func(s *ResellerBalanceAccountUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ResellerBalanceAccountUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ResellerBalanceAccountCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ResellerBalanceAccountCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ResellerBalanceAccountUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
