// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NovaWorks/zcard-next/server/internal/data/ent/securityauditlog"
)

// SecurityAuditLogCreate is the builder for creating a SecurityAuditLog entity.
type SecurityAuditLogCreate struct {
	config
	mutation *SecurityAuditLogMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetActorType sets the "actor_type" field.
func (_c *SecurityAuditLogCreate) SetActorType(v securityauditlog.ActorType) *SecurityAuditLogCreate {
	_c.mutation.SetActorType(v)
	return _c
}

// SetActorID sets the "actor_id" field.
func (_c *SecurityAuditLogCreate) SetActorID(v uint64) *SecurityAuditLogCreate {
	_c.mutation.SetActorID(v)
	return _c
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (_c *SecurityAuditLogCreate) SetNillableActorID(v *uint64) *SecurityAuditLogCreate {
	if v != nil {
		_c.SetActorID(*v)
	}
	return _c
}

// SetAction sets the "action" field.
func (_c *SecurityAuditLogCreate) SetAction(v string) *SecurityAuditLogCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetIP sets the "ip" field.
func (_c *SecurityAuditLogCreate) SetIP(v string) *SecurityAuditLogCreate {
	_c.mutation.SetIP(v)
	return _c
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_c *SecurityAuditLogCreate) SetNillableIP(v *string) *SecurityAuditLogCreate {
	if v != nil {
		_c.SetIP(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *SecurityAuditLogCreate) SetMetadata(v map[string]interface{}) *SecurityAuditLogCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SecurityAuditLogCreate) SetCreatedAt(v time.Time) *SecurityAuditLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SecurityAuditLogCreate) SetNillableCreatedAt(v *time.Time) *SecurityAuditLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SecurityAuditLogCreate) SetID(v uint64) *SecurityAuditLogCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the SecurityAuditLogMutation object of the builder.
func (_c *SecurityAuditLogCreate) Mutation() *SecurityAuditLogMutation {
	return _c.mutation
}

// Save creates the SecurityAuditLog in the database.
func (_c *SecurityAuditLogCreate) Save(ctx context.Context) (*SecurityAuditLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SecurityAuditLogCreate) SaveX(ctx context.Context) *SecurityAuditLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SecurityAuditLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SecurityAuditLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SecurityAuditLogCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := securityauditlog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SecurityAuditLogCreate) check() error {
	if _, ok := _c.mutation.ActorType(); !ok {
		return &ValidationError{Name: "actor_type", err: errors.New(`ent: missing required field "SecurityAuditLog.actor_type"`)}
	}
	if v, ok := _c.mutation.ActorType(); ok {
		if err := securityauditlog.ActorTypeValidator(v); err != nil {
			return &ValidationError{Name: "actor_type", err: fmt.Errorf(`ent: validator failed for field "SecurityAuditLog.actor_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "SecurityAuditLog.action"`)}
	}
	if v, ok := _c.mutation.Action(); ok {
		if err := securityauditlog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "SecurityAuditLog.action": %w`, err)}
		}
	}
	if v, ok := _c.mutation.IP(); ok {
		if err := securityauditlog.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "SecurityAuditLog.ip": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SecurityAuditLog.created_at"`)}
	}
	return nil
}

func (_c *SecurityAuditLogCreate) sqlSave(ctx context.Context) (*SecurityAuditLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SecurityAuditLogCreate) createSpec() (*SecurityAuditLog, *sqlgraph.CreateSpec) {
	var (
		_node = &SecurityAuditLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(securityauditlog.Table, sqlgraph.NewFieldSpec(securityauditlog.FieldID, field.TypeUint64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ActorType(); ok {
		_spec.SetField(securityauditlog.FieldActorType, field.TypeEnum, value)
		_node.ActorType = value
	}
	if value, ok := _c.mutation.ActorID(); ok {
		_spec.SetField(securityauditlog.FieldActorID, field.TypeUint64, value)
		_node.ActorID = value
	}
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(securityauditlog.FieldAction, field.TypeString, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.IP(); ok {
		_spec.SetField(securityauditlog.FieldIP, field.TypeString, value)
		_node.IP = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(securityauditlog.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(securityauditlog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SecurityAuditLog.Create().
//		SetActorType(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SecurityAuditLogUpsert) {
//			SetActorType(v+v).
//		}).
//		Exec(ctx)
func (_c *SecurityAuditLogCreate) OnConflict(opts ...sql.ConflictOption) *SecurityAuditLogUpsertOne {
	_c.conflict = opts
	return &SecurityAuditLogUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SecurityAuditLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SecurityAuditLogCreate) OnConflictColumns(columns ...string) *SecurityAuditLogUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SecurityAuditLogUpsertOne{
		create: _c,
	}
}

type (
	// SecurityAuditLogUpsertOne is the builder for "upsert"-ing
	//  one SecurityAuditLog node.
	SecurityAuditLogUpsertOne struct {
		create *SecurityAuditLogCreate
	}

	// SecurityAuditLogUpsert is the "OnConflict" setter.
	SecurityAuditLogUpsert struct {
		*sql.UpdateSet
	}
)

// SetActorType sets the "actor_type" field.
func (u *SecurityAuditLogUpsert) SetActorType(v securityauditlog.ActorType) *SecurityAuditLogUpsert {
	u.Set(securityauditlog.FieldActorType, v)
	return u
}

// UpdateActorType sets the "actor_type" field to the value that was provided on create.
func (u *SecurityAuditLogUpsert) UpdateActorType() *SecurityAuditLogUpsert {
	u.SetExcluded(securityauditlog.FieldActorType)
	return u
}

// SetActorID sets the "actor_id" field.
func (u *SecurityAuditLogUpsert) SetActorID(v uint64) *SecurityAuditLogUpsert {
	u.Set(securityauditlog.FieldActorID, v)
	return u
}

// UpdateActorID sets the "actor_id" field to the value that was provided on create.
func (u *SecurityAuditLogUpsert) UpdateActorID() *SecurityAuditLogUpsert {
	u.SetExcluded(securityauditlog.FieldActorID)
	return u
}

// AddActorID adds v to the "actor_id" field.
func (u *SecurityAuditLogUpsert) AddActorID(v uint64) *SecurityAuditLogUpsert {
	u.Add(securityauditlog.FieldActorID, v)
	return u
}

// ClearActorID clears the value of the "actor_id" field.
func (u *SecurityAuditLogUpsert) ClearActorID() *SecurityAuditLogUpsert {
	u.SetNull(securityauditlog.FieldActorID)
	return u
}

// SetAction sets the "action" field.
func (u *SecurityAuditLogUpsert) SetAction(v string) *SecurityAuditLogUpsert {
	u.Set(securityauditlog.FieldAction, v)
	return u
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *SecurityAuditLogUpsert) UpdateAction() *SecurityAuditLogUpsert {
	u.SetExcluded(securityauditlog.FieldAction)
	return u
}

// SetIP sets the "ip" field.
func (u *SecurityAuditLogUpsert) SetIP(v string) *SecurityAuditLogUpsert {
	u.Set(securityauditlog.FieldIP, v)
	return u
}

// UpdateIP sets the "ip" field to the value that was provided on create.
func (u *SecurityAuditLogUpsert) UpdateIP() *SecurityAuditLogUpsert {
	u.SetExcluded(securityauditlog.FieldIP)
	return u
}

// ClearIP clears the value of the "ip" field.
func (u *SecurityAuditLogUpsert) ClearIP() *SecurityAuditLogUpsert {
	u.SetNull(securityauditlog.FieldIP)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *SecurityAuditLogUpsert) SetMetadata(v map[string]interface{}) *SecurityAuditLogUpsert {
	u.Set(securityauditlog.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *SecurityAuditLogUpsert) UpdateMetadata() *SecurityAuditLogUpsert {
	u.SetExcluded(securityauditlog.FieldMetadata)
	return u
}

// ClearMetadata clears the value of the "metadata" field.
func (u *SecurityAuditLogUpsert) ClearMetadata() *SecurityAuditLogUpsert {
	u.SetNull(securityauditlog.FieldMetadata)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.SecurityAuditLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(securityauditlog.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SecurityAuditLogUpsertOne) UpdateNewValues() *SecurityAuditLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(securityauditlog.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(securityauditlog.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SecurityAuditLog.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SecurityAuditLogUpsertOne) Ignore() *SecurityAuditLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SecurityAuditLogUpsertOne) DoNothing() *SecurityAuditLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SecurityAuditLogCreate.OnConflict
// documentation for more info.
func (u *SecurityAuditLogUpsertOne) Update(set func(*SecurityAuditLogUpsert)) *SecurityAuditLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SecurityAuditLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetActorType sets the "actor_type" field.
func (u *SecurityAuditLogUpsertOne) SetActorType(v securityauditlog.ActorType) *SecurityAuditLogUpsertOne {
	return u.Update(func(s *SecurityAuditLogUpsert) {
		s.SetActorType(v)
	})
}

// UpdateActorType sets the "actor_type" field to the value that was provided on create.
func (u *SecurityAuditLogUpsertOne) UpdateActorType() *SecurityAuditLogUpsertOne {
	return u.Update(func(s *SecurityAuditLogUpsert) {
		s.UpdateActorType()
	})
}

// SetActorID sets the "actor_id" field.
func (u *SecurityAuditLogUpsertOne) SetActorID(v uint64) *SecurityAuditLogUpsertOne {
	return u.Update(func(s *SecurityAuditLogUpsert) {
		s.SetActorID(v)
	})
}

// AddActorID adds v to the "actor_id" field.
func (u *SecurityAuditLogUpsertOne) AddActorID(v uint64) *SecurityAuditLogUpsertOne {
	return u.Update(func(s *SecurityAuditLogUpsert) {
		s.AddActorID(v)
	})
}

// UpdateActorID sets the "actor_id" field to the value that was provided on create.
func (u *SecurityAuditLogUpsertOne) UpdateActorID() *SecurityAuditLogUpsertOne {
	return u.Update(func(s *SecurityAuditLogUpsert) {
		s.UpdateActorID()
	})
}

// ClearActorID clears the value of the "actor_id" field.
func (u *SecurityAuditLogUpsertOne) ClearActorID() *SecurityAuditLogUpsertOne {
	return u.Update(func(s *SecurityAuditLogUpsert) {
		s.ClearActorID()
	})
}

// SetAction sets the "action" field.
func (u *SecurityAuditLogUpsertOne) SetAction(v string) *SecurityAuditLogUpsertOne {
	return u.Update(func(s *SecurityAuditLogUpsert) {
		s.SetAction(v)
	})
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *SecurityAuditLogUpsertOne) UpdateAction() *SecurityAuditLogUpsertOne {
	return u.Update(func(s *SecurityAuditLogUpsert) {
		s.UpdateAction()
	})
}

// SetIP sets the "ip" field.
func (u *SecurityAuditLogUpsertOne) SetIP(v string) *SecurityAuditLogUpsertOne {
	return u.Update(func(s *SecurityAuditLogUpsert) {
		s.SetIP(v)
	})
}

// UpdateIP sets the "ip" field to the value that was provided on create.
func (u *SecurityAuditLogUpsertOne) UpdateIP() *SecurityAuditLogUpsertOne {
	return u.Update(func(s *SecurityAuditLogUpsert) {
		s.UpdateIP()
	})
}

// ClearIP clears the value of the "ip" field.
func (u *SecurityAuditLogUpsertOne) ClearIP() *SecurityAuditLogUpsertOne {
	return u.Update(func(s *SecurityAuditLogUpsert) {
		s.ClearIP()
	})
}

// SetMetadata sets the "metadata" field.
func (u *SecurityAuditLogUpsertOne) SetMetadata(v map[string]interface{}) *SecurityAuditLogUpsertOne {
	return u.Update(func(s *SecurityAuditLogUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *SecurityAuditLogUpsertOne) UpdateMetadata() *SecurityAuditLogUpsertOne {
	return u.Update(func(s *SecurityAuditLogUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *SecurityAuditLogUpsertOne) ClearMetadata() *SecurityAuditLogUpsertOne {
	return u.Update(func(s *SecurityAuditLogUpsert) {
		s.ClearMetadata()
	})
}

// Exec executes the query.
func (u *SecurityAuditLogUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SecurityAuditLogCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SecurityAuditLogUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SecurityAuditLogUpsertOne) ID(ctx context.Context) (id uint64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SecurityAuditLogUpsertOne) IDX(ctx context.Context) uint64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SecurityAuditLogCreateBulk is the builder for creating many SecurityAuditLog entities in bulk.
type SecurityAuditLogCreateBulk struct {
	config
	err      error
	builders []*SecurityAuditLogCreate
	conflict []sql.ConflictOption
}

// Save creates the SecurityAuditLog entities in the database.
func (_c *SecurityAuditLogCreateBulk) Save(ctx context.Context) ([]*SecurityAuditLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SecurityAuditLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SecurityAuditLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SecurityAuditLogCreateBulk) SaveX(ctx context.Context) []*SecurityAuditLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SecurityAuditLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SecurityAuditLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SecurityAuditLog.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SecurityAuditLogUpsert) {
//			SetActorType(v+v).
//		}).
//		Exec(ctx)
func (_c *SecurityAuditLogCreateBulk) OnConflict(opts ...sql.ConflictOption) *SecurityAuditLogUpsertBulk {
	_c.conflict = opts
	return &SecurityAuditLogUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SecurityAuditLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SecurityAuditLogCreateBulk) OnConflictColumns(columns ...string) *SecurityAuditLogUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SecurityAuditLogUpsertBulk{
		create: _c,
	}
}

// SecurityAuditLogUpsertBulk is the builder for "upsert"-ing
// a bulk of SecurityAuditLog nodes.
type SecurityAuditLogUpsertBulk struct {
	create *SecurityAuditLogCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SecurityAuditLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(securityauditlog.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SecurityAuditLogUpsertBulk) UpdateNewValues() *SecurityAuditLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(securityauditlog.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(securityauditlog.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SecurityAuditLog.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SecurityAuditLogUpsertBulk) Ignore() *SecurityAuditLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SecurityAuditLogUpsertBulk) DoNothing() *SecurityAuditLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SecurityAuditLogCreateBulk.OnConflict
// documentation for more info.
func (u *SecurityAuditLogUpsertBulk) Update(set func(*SecurityAuditLogUpsert)) *SecurityAuditLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SecurityAuditLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetActorType sets the "actor_type" field.
func (u *SecurityAuditLogUpsertBulk) SetActorType(v securityauditlog.ActorType) *SecurityAuditLogUpsertBulk {
	return u.Update(func(s *SecurityAuditLogUpsert) {
		s.SetActorType(v)
	})
}

// UpdateActorType sets the "actor_type" field to the value that was provided on create.
func (u *SecurityAuditLogUpsertBulk) UpdateActorType() *SecurityAuditLogUpsertBulk {
	return u.Update(func(s *SecurityAuditLogUpsert) {
		s.UpdateActorType()
	})
}

// SetActorID sets the "actor_id" field.
func (u *SecurityAuditLogUpsertBulk) SetActorID(v uint64) *SecurityAuditLogUpsertBulk {
	return u.Update(func(s *SecurityAuditLogUpsert) {
		s.SetActorID(v)
	})
}

// AddActorID adds v to the "actor_id" field.
func (u *SecurityAuditLogUpsertBulk) AddActorID(v uint64) *SecurityAuditLogUpsertBulk {
	return u.Update(func(s *SecurityAuditLogUpsert) {
		s.AddActorID(v)
	})
}

// UpdateActorID sets the "actor_id" field to the value that was provided on create.
func (u *SecurityAuditLogUpsertBulk) UpdateActorID() *SecurityAuditLogUpsertBulk {
	return u.Update(func(s *SecurityAuditLogUpsert) {
		s.UpdateActorID()
	})
}

// ClearActorID clears the value of the "actor_id" field.
func (u *SecurityAuditLogUpsertBulk) ClearActorID() *SecurityAuditLogUpsertBulk {
	return u.Update(func(s *SecurityAuditLogUpsert) {
		s.ClearActorID()
	})
}

// SetAction sets the "action" field.
func (u *SecurityAuditLogUpsertBulk) SetAction(v string) *SecurityAuditLogUpsertBulk {
	return u.Update(func(s *SecurityAuditLogUpsert) {
		s.SetAction(v)
	})
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *SecurityAuditLogUpsertBulk) UpdateAction() *SecurityAuditLogUpsertBulk {
	return u.Update(func(s *SecurityAuditLogUpsert) {
		s.UpdateAction()
	})
}

// SetIP sets the "ip" field.
func (u *SecurityAuditLogUpsertBulk) SetIP(v string) *SecurityAuditLogUpsertBulk {
	return u.Update(func(s *SecurityAuditLogUpsert) {
		s.SetIP(v)
	})
}

// UpdateIP sets the "ip" field to the value that was provided on create.
func (u *SecurityAuditLogUpsertBulk) UpdateIP() *SecurityAuditLogUpsertBulk {
	return u.Update(func(s *SecurityAuditLogUpsert) {
		s.UpdateIP()
	})
}

// ClearIP clears the value of the "ip" field.
func (u *SecurityAuditLogUpsertBulk) ClearIP() *SecurityAuditLogUpsertBulk {
	return u.Update(func(s *SecurityAuditLogUpsert) {
		s.ClearIP()
	})
}

// SetMetadata sets the "metadata" field.
func (u *SecurityAuditLogUpsertBulk) SetMetadata(v map[string]interface{}) *SecurityAuditLogUpsertBulk {
	return u.Update(func(s *SecurityAuditLogUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *SecurityAuditLogUpsertBulk) UpdateMetadata() *SecurityAuditLogUpsertBulk {
	return u.Update(func(s *SecurityAuditLogUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *SecurityAuditLogUpsertBulk) ClearMetadata() *SecurityAuditLogUpsertBulk {
	return u.Update(func(s *SecurityAuditLogUpsert) {
		s.ClearMetadata()
	})
}

// Exec executes the query.
func (u *SecurityAuditLogUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SecurityAuditLogCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SecurityAuditLogCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SecurityAuditLogUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
