// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/NovaWorks/zcard-next/server/internal/data/ent/predicate"
	"github.com/NovaWorks/zcard-next/server/internal/data/ent/supplyorder"
)

// SupplyOrderUpdate is the builder for updating SupplyOrder entities.
type SupplyOrderUpdate struct {
	config
	hooks    []Hook
	mutation *SupplyOrderMutation
}

// Where appends a list predicates to the SupplyOrderUpdate builder.
func (_u *SupplyOrderUpdate) Where(ps ...predicate.SupplyOrder) *SupplyOrderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SupplyOrderUpdate) SetUpdatedAt(v time.Time) *SupplyOrderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *SupplyOrderUpdate) SetAccountID(v uint64) *SupplyOrderUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *SupplyOrderUpdate) SetNillableAccountID(v *uint64) *SupplyOrderUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *SupplyOrderUpdate) AddAccountID(v int64) *SupplyOrderUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetDownstreamOrderNo sets the "downstream_order_no" field.
func (_u *SupplyOrderUpdate) SetDownstreamOrderNo(v string) *SupplyOrderUpdate {
	_u.mutation.SetDownstreamOrderNo(v)
	return _u
}

// SetNillableDownstreamOrderNo sets the "downstream_order_no" field if the given value is not nil.
func (_u *SupplyOrderUpdate) SetNillableDownstreamOrderNo(v *string) *SupplyOrderUpdate {
	if v != nil {
		_u.SetDownstreamOrderNo(*v)
	}
	return _u
}

// SetItems sets the "items" field.
func (_u *SupplyOrderUpdate) SetItems(v []map[string]interface{}) *SupplyOrderUpdate {
	_u.mutation.SetItems(v)
	return _u
}

// AppendItems appends value to the "items" field.
func (_u *SupplyOrderUpdate) AppendItems(v []map[string]interface{}) *SupplyOrderUpdate {
	_u.mutation.AppendItems(v)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *SupplyOrderUpdate) SetAmount(v int64) *SupplyOrderUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *SupplyOrderUpdate) SetNillableAmount(v *int64) *SupplyOrderUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *SupplyOrderUpdate) AddAmount(v int64) *SupplyOrderUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *SupplyOrderUpdate) SetStatus(v supplyorder.Status) *SupplyOrderUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SupplyOrderUpdate) SetNillableStatus(v *supplyorder.Status) *SupplyOrderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLocalOrderID sets the "local_order_id" field.
func (_u *SupplyOrderUpdate) SetLocalOrderID(v uint64) *SupplyOrderUpdate {
	_u.mutation.ResetLocalOrderID()
	_u.mutation.SetLocalOrderID(v)
	return _u
}

// SetNillableLocalOrderID sets the "local_order_id" field if the given value is not nil.
func (_u *SupplyOrderUpdate) SetNillableLocalOrderID(v *uint64) *SupplyOrderUpdate {
	if v != nil {
		_u.SetLocalOrderID(*v)
	}
	return _u
}

// AddLocalOrderID adds value to the "local_order_id" field.
func (_u *SupplyOrderUpdate) AddLocalOrderID(v int64) *SupplyOrderUpdate {
	_u.mutation.AddLocalOrderID(v)
	return _u
}

// ClearLocalOrderID clears the value of the "local_order_id" field.
func (_u *SupplyOrderUpdate) ClearLocalOrderID() *SupplyOrderUpdate {
	_u.mutation.ClearLocalOrderID()
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *SupplyOrderUpdate) SetPaidAt(v time.Time) *SupplyOrderUpdate {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *SupplyOrderUpdate) SetNillablePaidAt(v *time.Time) *SupplyOrderUpdate {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *SupplyOrderUpdate) ClearPaidAt() *SupplyOrderUpdate {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetFulfilledAt sets the "fulfilled_at" field.
func (_u *SupplyOrderUpdate) SetFulfilledAt(v time.Time) *SupplyOrderUpdate {
	_u.mutation.SetFulfilledAt(v)
	return _u
}

// SetNillableFulfilledAt sets the "fulfilled_at" field if the given value is not nil.
func (_u *SupplyOrderUpdate) SetNillableFulfilledAt(v *time.Time) *SupplyOrderUpdate {
	if v != nil {
		_u.SetFulfilledAt(*v)
	}
	return _u
}

// ClearFulfilledAt clears the value of the "fulfilled_at" field.
func (_u *SupplyOrderUpdate) ClearFulfilledAt() *SupplyOrderUpdate {
	_u.mutation.ClearFulfilledAt()
	return _u
}

// Mutation returns the SupplyOrderMutation object of the builder.
func (_u *SupplyOrderUpdate) Mutation() *SupplyOrderMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SupplyOrderUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupplyOrderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SupplyOrderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupplyOrderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SupplyOrderUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := supplyorder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupplyOrderUpdate) check() error {
	if v, ok := _u.mutation.DownstreamOrderNo(); ok {
		if err := supplyorder.DownstreamOrderNoValidator(v); err != nil {
			return &ValidationError{Name: "downstream_order_no", err: fmt.Errorf(`ent: validator failed for field "SupplyOrder.downstream_order_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := supplyorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SupplyOrder.status": %w`, err)}
		}
	}
	return nil
}

func (_u *SupplyOrderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supplyorder.Table, supplyorder.Columns, sqlgraph.NewFieldSpec(supplyorder.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(supplyorder.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(supplyorder.FieldAccountID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(supplyorder.FieldAccountID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.DownstreamOrderNo(); ok {
		_spec.SetField(supplyorder.FieldDownstreamOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.Items(); ok {
		_spec.SetField(supplyorder.FieldItems, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedItems(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, supplyorder.FieldItems, value)
		})
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(supplyorder.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(supplyorder.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(supplyorder.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LocalOrderID(); ok {
		_spec.SetField(supplyorder.FieldLocalOrderID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedLocalOrderID(); ok {
		_spec.AddField(supplyorder.FieldLocalOrderID, field.TypeUint64, value)
	}
	if _u.mutation.LocalOrderIDCleared() {
		_spec.ClearField(supplyorder.FieldLocalOrderID, field.TypeUint64)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(supplyorder.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(supplyorder.FieldPaidAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FulfilledAt(); ok {
		_spec.SetField(supplyorder.FieldFulfilledAt, field.TypeTime, value)
	}
	if _u.mutation.FulfilledAtCleared() {
		_spec.ClearField(supplyorder.FieldFulfilledAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supplyorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SupplyOrderUpdateOne is the builder for updating a single SupplyOrder entity.
type SupplyOrderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SupplyOrderMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SupplyOrderUpdateOne) SetUpdatedAt(v time.Time) *SupplyOrderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *SupplyOrderUpdateOne) SetAccountID(v uint64) *SupplyOrderUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *SupplyOrderUpdateOne) SetNillableAccountID(v *uint64) *SupplyOrderUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *SupplyOrderUpdateOne) AddAccountID(v int64) *SupplyOrderUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetDownstreamOrderNo sets the "downstream_order_no" field.
func (_u *SupplyOrderUpdateOne) SetDownstreamOrderNo(v string) *SupplyOrderUpdateOne {
	_u.mutation.SetDownstreamOrderNo(v)
	return _u
}

// SetNillableDownstreamOrderNo sets the "downstream_order_no" field if the given value is not nil.
func (_u *SupplyOrderUpdateOne) SetNillableDownstreamOrderNo(v *string) *SupplyOrderUpdateOne {
	if v != nil {
		_u.SetDownstreamOrderNo(*v)
	}
	return _u
}

// SetItems sets the "items" field.
func (_u *SupplyOrderUpdateOne) SetItems(v []map[string]interface{}) *SupplyOrderUpdateOne {
	_u.mutation.SetItems(v)
	return _u
}

// AppendItems appends value to the "items" field.
func (_u *SupplyOrderUpdateOne) AppendItems(v []map[string]interface{}) *SupplyOrderUpdateOne {
	_u.mutation.AppendItems(v)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *SupplyOrderUpdateOne) SetAmount(v int64) *SupplyOrderUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *SupplyOrderUpdateOne) SetNillableAmount(v *int64) *SupplyOrderUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *SupplyOrderUpdateOne) AddAmount(v int64) *SupplyOrderUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *SupplyOrderUpdateOne) SetStatus(v supplyorder.Status) *SupplyOrderUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SupplyOrderUpdateOne) SetNillableStatus(v *supplyorder.Status) *SupplyOrderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLocalOrderID sets the "local_order_id" field.
func (_u *SupplyOrderUpdateOne) SetLocalOrderID(v uint64) *SupplyOrderUpdateOne {
	_u.mutation.ResetLocalOrderID()
	_u.mutation.SetLocalOrderID(v)
	return _u
}

// SetNillableLocalOrderID sets the "local_order_id" field if the given value is not nil.
func (_u *SupplyOrderUpdateOne) SetNillableLocalOrderID(v *uint64) *SupplyOrderUpdateOne {
	if v != nil {
		_u.SetLocalOrderID(*v)
	}
	return _u
}

// AddLocalOrderID adds value to the "local_order_id" field.
func (_u *SupplyOrderUpdateOne) AddLocalOrderID(v int64) *SupplyOrderUpdateOne {
	_u.mutation.AddLocalOrderID(v)
	return _u
}

// ClearLocalOrderID clears the value of the "local_order_id" field.
func (_u *SupplyOrderUpdateOne) ClearLocalOrderID() *SupplyOrderUpdateOne {
	_u.mutation.ClearLocalOrderID()
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *SupplyOrderUpdateOne) SetPaidAt(v time.Time) *SupplyOrderUpdateOne {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *SupplyOrderUpdateOne) SetNillablePaidAt(v *time.Time) *SupplyOrderUpdateOne {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *SupplyOrderUpdateOne) ClearPaidAt() *SupplyOrderUpdateOne {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetFulfilledAt sets the "fulfilled_at" field.
func (_u *SupplyOrderUpdateOne) SetFulfilledAt(v time.Time) *SupplyOrderUpdateOne {
	_u.mutation.SetFulfilledAt(v)
	return _u
}

// SetNillableFulfilledAt sets the "fulfilled_at" field if the given value is not nil.
func (_u *SupplyOrderUpdateOne) SetNillableFulfilledAt(v *time.Time) *SupplyOrderUpdateOne {
	if v != nil {
		_u.SetFulfilledAt(*v)
	}
	return _u
}

// ClearFulfilledAt clears the value of the "fulfilled_at" field.
func (_u *SupplyOrderUpdateOne) ClearFulfilledAt() *SupplyOrderUpdateOne {
	_u.mutation.ClearFulfilledAt()
	return _u
}

// Mutation returns the SupplyOrderMutation object of the builder.
func (_u *SupplyOrderUpdateOne) Mutation() *SupplyOrderMutation {
	return _u.mutation
}

// Where appends a list predicates to the SupplyOrderUpdate builder.
func (_u *SupplyOrderUpdateOne) Where(ps ...predicate.SupplyOrder) *SupplyOrderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SupplyOrderUpdateOne) Select(field string, fields ...string) *SupplyOrderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SupplyOrder entity.
func (_u *SupplyOrderUpdateOne) Save(ctx context.Context) (*SupplyOrder, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupplyOrderUpdateOne) SaveX(ctx context.Context) *SupplyOrder {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SupplyOrderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupplyOrderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SupplyOrderUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := supplyorder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupplyOrderUpdateOne) check() error {
	if v, ok := _u.mutation.DownstreamOrderNo(); ok {
		if err := supplyorder.DownstreamOrderNoValidator(v); err != nil {
			return &ValidationError{Name: "downstream_order_no", err: fmt.Errorf(`ent: validator failed for field "SupplyOrder.downstream_order_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := supplyorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SupplyOrder.status": %w`, err)}
		}
	}
	return nil
}

func (_u *SupplyOrderUpdateOne) sqlSave(ctx context.Context) (_node *SupplyOrder, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supplyorder.Table, supplyorder.Columns, sqlgraph.NewFieldSpec(supplyorder.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SupplyOrder.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, supplyorder.FieldID)
		for _, f := range fields {
			if !supplyorder.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != supplyorder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(supplyorder.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(supplyorder.FieldAccountID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(supplyorder.FieldAccountID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.DownstreamOrderNo(); ok {
		_spec.SetField(supplyorder.FieldDownstreamOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.Items(); ok {
		_spec.SetField(supplyorder.FieldItems, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedItems(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, supplyorder.FieldItems, value)
		})
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(supplyorder.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(supplyorder.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(supplyorder.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LocalOrderID(); ok {
		_spec.SetField(supplyorder.FieldLocalOrderID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedLocalOrderID(); ok {
		_spec.AddField(supplyorder.FieldLocalOrderID, field.TypeUint64, value)
	}
	if _u.mutation.LocalOrderIDCleared() {
		_spec.ClearField(supplyorder.FieldLocalOrderID, field.TypeUint64)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(supplyorder.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(supplyorder.FieldPaidAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FulfilledAt(); ok {
		_spec.SetField(supplyorder.FieldFulfilledAt, field.TypeTime, value)
	}
	if _u.mutation.FulfilledAtCleared() {
		_spec.ClearField(supplyorder.FieldFulfilledAt, field.TypeTime)
	}
	_node = &SupplyOrder{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supplyorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
