// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: admin/v1/content.proto

package adminv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Banner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Position      string                 `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`                    // top | middle | bottom
	TitleJson     string                 `protobuf:"bytes,4,opt,name=title_json,json=titleJson,proto3" json:"title_json,omitempty"` // 多语言标题 {"zh_CN": "...", "en": "..."}
	Image         string                 `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	MobileImage   string                 `protobuf:"bytes,6,opt,name=mobile_image,json=mobileImage,proto3" json:"mobile_image,omitempty"`
	LinkType      string                 `protobuf:"bytes,7,opt,name=link_type,json=linkType,proto3" json:"link_type,omitempty"` // product | category | url | ad
	LinkValue     string                 `protobuf:"bytes,8,opt,name=link_value,json=linkValue,proto3" json:"link_value,omitempty"`
	IsActive      bool                   `protobuf:"varint,9,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	StartAt       int64                  `protobuf:"varint,10,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"` // unix 秒；0 = 不限
	EndAt         int64                  `protobuf:"varint,11,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	Sort          int32                  `protobuf:"varint,12,opt,name=sort,proto3" json:"sort,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Banner) Reset() {
	*x = Banner{}
	mi := &file_admin_v1_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Banner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Banner) ProtoMessage() {}

func (x *Banner) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Banner.ProtoReflect.Descriptor instead.
func (*Banner) Descriptor() ([]byte, []int) {
	return file_admin_v1_content_proto_rawDescGZIP(), []int{0}
}

func (x *Banner) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Banner) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Banner) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *Banner) GetTitleJson() string {
	if x != nil {
		return x.TitleJson
	}
	return ""
}

func (x *Banner) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Banner) GetMobileImage() string {
	if x != nil {
		return x.MobileImage
	}
	return ""
}

func (x *Banner) GetLinkType() string {
	if x != nil {
		return x.LinkType
	}
	return ""
}

func (x *Banner) GetLinkValue() string {
	if x != nil {
		return x.LinkValue
	}
	return ""
}

func (x *Banner) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Banner) GetStartAt() int64 {
	if x != nil {
		return x.StartAt
	}
	return 0
}

func (x *Banner) GetEndAt() int64 {
	if x != nil {
		return x.EndAt
	}
	return 0
}

func (x *Banner) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *Banner) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Banner) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type CreateBannerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Position      string                 `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	TitleJson     string                 `protobuf:"bytes,3,opt,name=title_json,json=titleJson,proto3" json:"title_json,omitempty"`
	Image         string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	MobileImage   string                 `protobuf:"bytes,5,opt,name=mobile_image,json=mobileImage,proto3" json:"mobile_image,omitempty"`
	LinkType      string                 `protobuf:"bytes,6,opt,name=link_type,json=linkType,proto3" json:"link_type,omitempty"`
	LinkValue     string                 `protobuf:"bytes,7,opt,name=link_value,json=linkValue,proto3" json:"link_value,omitempty"`
	IsActive      bool                   `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	StartAt       int64                  `protobuf:"varint,9,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt         int64                  `protobuf:"varint,10,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	Sort          int32                  `protobuf:"varint,11,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBannerRequest) Reset() {
	*x = CreateBannerRequest{}
	mi := &file_admin_v1_content_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBannerRequest) ProtoMessage() {}

func (x *CreateBannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_content_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBannerRequest.ProtoReflect.Descriptor instead.
func (*CreateBannerRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_content_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBannerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateBannerRequest) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *CreateBannerRequest) GetTitleJson() string {
	if x != nil {
		return x.TitleJson
	}
	return ""
}

func (x *CreateBannerRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CreateBannerRequest) GetMobileImage() string {
	if x != nil {
		return x.MobileImage
	}
	return ""
}

func (x *CreateBannerRequest) GetLinkType() string {
	if x != nil {
		return x.LinkType
	}
	return ""
}

func (x *CreateBannerRequest) GetLinkValue() string {
	if x != nil {
		return x.LinkValue
	}
	return ""
}

func (x *CreateBannerRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *CreateBannerRequest) GetStartAt() int64 {
	if x != nil {
		return x.StartAt
	}
	return 0
}

func (x *CreateBannerRequest) GetEndAt() int64 {
	if x != nil {
		return x.EndAt
	}
	return 0
}

func (x *CreateBannerRequest) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type UpdateBannerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Position      string                 `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	TitleJson     string                 `protobuf:"bytes,4,opt,name=title_json,json=titleJson,proto3" json:"title_json,omitempty"`
	Image         string                 `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	MobileImage   string                 `protobuf:"bytes,6,opt,name=mobile_image,json=mobileImage,proto3" json:"mobile_image,omitempty"`
	LinkType      string                 `protobuf:"bytes,7,opt,name=link_type,json=linkType,proto3" json:"link_type,omitempty"`
	LinkValue     string                 `protobuf:"bytes,8,opt,name=link_value,json=linkValue,proto3" json:"link_value,omitempty"`
	IsActive      bool                   `protobuf:"varint,9,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	StartAt       int64                  `protobuf:"varint,10,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt         int64                  `protobuf:"varint,11,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	Sort          int32                  `protobuf:"varint,12,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBannerRequest) Reset() {
	*x = UpdateBannerRequest{}
	mi := &file_admin_v1_content_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBannerRequest) ProtoMessage() {}

func (x *UpdateBannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_content_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBannerRequest.ProtoReflect.Descriptor instead.
func (*UpdateBannerRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_content_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateBannerRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateBannerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateBannerRequest) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *UpdateBannerRequest) GetTitleJson() string {
	if x != nil {
		return x.TitleJson
	}
	return ""
}

func (x *UpdateBannerRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *UpdateBannerRequest) GetMobileImage() string {
	if x != nil {
		return x.MobileImage
	}
	return ""
}

func (x *UpdateBannerRequest) GetLinkType() string {
	if x != nil {
		return x.LinkType
	}
	return ""
}

func (x *UpdateBannerRequest) GetLinkValue() string {
	if x != nil {
		return x.LinkValue
	}
	return ""
}

func (x *UpdateBannerRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *UpdateBannerRequest) GetStartAt() int64 {
	if x != nil {
		return x.StartAt
	}
	return 0
}

func (x *UpdateBannerRequest) GetEndAt() int64 {
	if x != nil {
		return x.EndAt
	}
	return 0
}

func (x *UpdateBannerRequest) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type DeleteBannerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBannerRequest) Reset() {
	*x = DeleteBannerRequest{}
	mi := &file_admin_v1_content_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBannerRequest) ProtoMessage() {}

func (x *DeleteBannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_content_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBannerRequest.ProtoReflect.Descriptor instead.
func (*DeleteBannerRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_content_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteBannerRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListBannersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      string                 `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"` // 空 = 全部
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBannersRequest) Reset() {
	*x = ListBannersRequest{}
	mi := &file_admin_v1_content_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBannersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBannersRequest) ProtoMessage() {}

func (x *ListBannersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_content_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBannersRequest.ProtoReflect.Descriptor instead.
func (*ListBannersRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_content_proto_rawDescGZIP(), []int{4}
}

func (x *ListBannersRequest) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *ListBannersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListBannersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListBannersReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Banners       []*Banner              `protobuf:"bytes,1,rep,name=banners,proto3" json:"banners,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBannersReply) Reset() {
	*x = ListBannersReply{}
	mi := &file_admin_v1_content_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBannersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBannersReply) ProtoMessage() {}

func (x *ListBannersReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_content_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBannersReply.ProtoReflect.Descriptor instead.
func (*ListBannersReply) Descriptor() ([]byte, []int) {
	return file_admin_v1_content_proto_rawDescGZIP(), []int{5}
}

func (x *ListBannersReply) GetBanners() []*Banner {
	if x != nil {
		return x.Banners
	}
	return nil
}

func (x *ListBannersReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListBannersReply) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListBannersReply) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type Post struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // blog | notice
	TitleJson     string                 `protobuf:"bytes,4,opt,name=title_json,json=titleJson,proto3" json:"title_json,omitempty"`
	SummaryJson   string                 `protobuf:"bytes,5,opt,name=summary_json,json=summaryJson,proto3" json:"summary_json,omitempty"`
	ContentJson   string                 `protobuf:"bytes,6,opt,name=content_json,json=contentJson,proto3" json:"content_json,omitempty"`
	Thumbnail     string                 `protobuf:"bytes,7,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	CategoryId    uint64                 `protobuf:"varint,8,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	IsPublished   bool                   `protobuf:"varint,9,opt,name=is_published,json=isPublished,proto3" json:"is_published,omitempty"`
	PublishedAt   int64                  `protobuf:"varint,10,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Post) Reset() {
	*x = Post{}
	mi := &file_admin_v1_content_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_content_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_admin_v1_content_proto_rawDescGZIP(), []int{6}
}

func (x *Post) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Post) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Post) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Post) GetTitleJson() string {
	if x != nil {
		return x.TitleJson
	}
	return ""
}

func (x *Post) GetSummaryJson() string {
	if x != nil {
		return x.SummaryJson
	}
	return ""
}

func (x *Post) GetContentJson() string {
	if x != nil {
		return x.ContentJson
	}
	return ""
}

func (x *Post) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

func (x *Post) GetCategoryId() uint64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *Post) GetIsPublished() bool {
	if x != nil {
		return x.IsPublished
	}
	return false
}

func (x *Post) GetPublishedAt() int64 {
	if x != nil {
		return x.PublishedAt
	}
	return 0
}

func (x *Post) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Post) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type CreatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	TitleJson     string                 `protobuf:"bytes,3,opt,name=title_json,json=titleJson,proto3" json:"title_json,omitempty"`
	SummaryJson   string                 `protobuf:"bytes,4,opt,name=summary_json,json=summaryJson,proto3" json:"summary_json,omitempty"`
	ContentJson   string                 `protobuf:"bytes,5,opt,name=content_json,json=contentJson,proto3" json:"content_json,omitempty"`
	Thumbnail     string                 `protobuf:"bytes,6,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	CategoryId    uint64                 `protobuf:"varint,7,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	IsPublished   bool                   `protobuf:"varint,8,opt,name=is_published,json=isPublished,proto3" json:"is_published,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostRequest) Reset() {
	*x = CreatePostRequest{}
	mi := &file_admin_v1_content_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostRequest) ProtoMessage() {}

func (x *CreatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_content_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostRequest.ProtoReflect.Descriptor instead.
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_content_proto_rawDescGZIP(), []int{7}
}

func (x *CreatePostRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreatePostRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreatePostRequest) GetTitleJson() string {
	if x != nil {
		return x.TitleJson
	}
	return ""
}

func (x *CreatePostRequest) GetSummaryJson() string {
	if x != nil {
		return x.SummaryJson
	}
	return ""
}

func (x *CreatePostRequest) GetContentJson() string {
	if x != nil {
		return x.ContentJson
	}
	return ""
}

func (x *CreatePostRequest) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

func (x *CreatePostRequest) GetCategoryId() uint64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CreatePostRequest) GetIsPublished() bool {
	if x != nil {
		return x.IsPublished
	}
	return false
}

type UpdatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TitleJson     string                 `protobuf:"bytes,2,opt,name=title_json,json=titleJson,proto3" json:"title_json,omitempty"`
	SummaryJson   string                 `protobuf:"bytes,3,opt,name=summary_json,json=summaryJson,proto3" json:"summary_json,omitempty"`
	ContentJson   string                 `protobuf:"bytes,4,opt,name=content_json,json=contentJson,proto3" json:"content_json,omitempty"`
	Thumbnail     string                 `protobuf:"bytes,5,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	CategoryId    uint64                 `protobuf:"varint,6,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostRequest) Reset() {
	*x = UpdatePostRequest{}
	mi := &file_admin_v1_content_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostRequest) ProtoMessage() {}

func (x *UpdatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_content_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostRequest.ProtoReflect.Descriptor instead.
func (*UpdatePostRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_content_proto_rawDescGZIP(), []int{8}
}

func (x *UpdatePostRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePostRequest) GetTitleJson() string {
	if x != nil {
		return x.TitleJson
	}
	return ""
}

func (x *UpdatePostRequest) GetSummaryJson() string {
	if x != nil {
		return x.SummaryJson
	}
	return ""
}

func (x *UpdatePostRequest) GetContentJson() string {
	if x != nil {
		return x.ContentJson
	}
	return ""
}

func (x *UpdatePostRequest) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

func (x *UpdatePostRequest) GetCategoryId() uint64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

type PublishPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Publish       bool                   `protobuf:"varint,2,opt,name=publish,proto3" json:"publish,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishPostRequest) Reset() {
	*x = PublishPostRequest{}
	mi := &file_admin_v1_content_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishPostRequest) ProtoMessage() {}

func (x *PublishPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_content_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishPostRequest.ProtoReflect.Descriptor instead.
func (*PublishPostRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_content_proto_rawDescGZIP(), []int{9}
}

func (x *PublishPostRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PublishPostRequest) GetPublish() bool {
	if x != nil {
		return x.Publish
	}
	return false
}

type DeletePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostRequest) Reset() {
	*x = DeletePostRequest{}
	mi := &file_admin_v1_content_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostRequest) ProtoMessage() {}

func (x *DeletePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_content_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostRequest.ProtoReflect.Descriptor instead.
func (*DeletePostRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_content_proto_rawDescGZIP(), []int{10}
}

func (x *DeletePostRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListPostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // 空 = 全部
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPostsRequest) Reset() {
	*x = ListPostsRequest{}
	mi := &file_admin_v1_content_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostsRequest) ProtoMessage() {}

func (x *ListPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_content_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostsRequest.ProtoReflect.Descriptor instead.
func (*ListPostsRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_content_proto_rawDescGZIP(), []int{11}
}

func (x *ListPostsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListPostsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPostsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListPostsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*Post                `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPostsReply) Reset() {
	*x = ListPostsReply{}
	mi := &file_admin_v1_content_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPostsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostsReply) ProtoMessage() {}

func (x *ListPostsReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_content_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostsReply.ProtoReflect.Descriptor instead.
func (*ListPostsReply) Descriptor() ([]byte, []int) {
	return file_admin_v1_content_proto_rawDescGZIP(), []int{12}
}

func (x *ListPostsReply) GetPosts() []*Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

func (x *ListPostsReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListPostsReply) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPostsReply) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type PostCategory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Sort          int32                  `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostCategory) Reset() {
	*x = PostCategory{}
	mi := &file_admin_v1_content_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostCategory) ProtoMessage() {}

func (x *PostCategory) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_content_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostCategory.ProtoReflect.Descriptor instead.
func (*PostCategory) Descriptor() ([]byte, []int) {
	return file_admin_v1_content_proto_rawDescGZIP(), []int{13}
}

func (x *PostCategory) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PostCategory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PostCategory) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *PostCategory) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *PostCategory) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type CreatePostCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Sort          int32                  `protobuf:"varint,3,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostCategoryRequest) Reset() {
	*x = CreatePostCategoryRequest{}
	mi := &file_admin_v1_content_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostCategoryRequest) ProtoMessage() {}

func (x *CreatePostCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_content_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostCategoryRequest.ProtoReflect.Descriptor instead.
func (*CreatePostCategoryRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_content_proto_rawDescGZIP(), []int{14}
}

func (x *CreatePostCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePostCategoryRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreatePostCategoryRequest) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type UpdatePostCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Sort          int32                  `protobuf:"varint,3,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostCategoryRequest) Reset() {
	*x = UpdatePostCategoryRequest{}
	mi := &file_admin_v1_content_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostCategoryRequest) ProtoMessage() {}

func (x *UpdatePostCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_content_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostCategoryRequest.ProtoReflect.Descriptor instead.
func (*UpdatePostCategoryRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_content_proto_rawDescGZIP(), []int{15}
}

func (x *UpdatePostCategoryRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePostCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePostCategoryRequest) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type DeletePostCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostCategoryRequest) Reset() {
	*x = DeletePostCategoryRequest{}
	mi := &file_admin_v1_content_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostCategoryRequest) ProtoMessage() {}

func (x *DeletePostCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_content_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostCategoryRequest.ProtoReflect.Descriptor instead.
func (*DeletePostCategoryRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_content_proto_rawDescGZIP(), []int{16}
}

func (x *DeletePostCategoryRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListPostCategoriesAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPostCategoriesAdminRequest) Reset() {
	*x = ListPostCategoriesAdminRequest{}
	mi := &file_admin_v1_content_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPostCategoriesAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostCategoriesAdminRequest) ProtoMessage() {}

func (x *ListPostCategoriesAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_content_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostCategoriesAdminRequest.ProtoReflect.Descriptor instead.
func (*ListPostCategoriesAdminRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_content_proto_rawDescGZIP(), []int{17}
}

type ListPostCategoriesAdminReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*PostCategory        `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPostCategoriesAdminReply) Reset() {
	*x = ListPostCategoriesAdminReply{}
	mi := &file_admin_v1_content_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPostCategoriesAdminReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostCategoriesAdminReply) ProtoMessage() {}

func (x *ListPostCategoriesAdminReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_content_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostCategoriesAdminReply.ProtoReflect.Descriptor instead.
func (*ListPostCategoriesAdminReply) Descriptor() ([]byte, []int) {
	return file_admin_v1_content_proto_rawDescGZIP(), []int{18}
}

func (x *ListPostCategoriesAdminReply) GetCategories() []*PostCategory {
	if x != nil {
		return x.Categories
	}
	return nil
}

var File_admin_v1_content_proto protoreflect.FileDescriptor

const file_admin_v1_content_proto_rawDesc = "" +
	"\n" +
	"\x16admin/v1/content.proto\x12\x12zcard.api.admin.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xfd\x02\n" +
	"\x06Banner\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\tR\bposition\x12\x1d\n" +
	"\n" +
	"title_json\x18\x04 \x01(\tR\ttitleJson\x12\x14\n" +
	"\x05image\x18\x05 \x01(\tR\x05image\x12!\n" +
	"\fmobile_image\x18\x06 \x01(\tR\vmobileImage\x12\x1b\n" +
	"\tlink_type\x18\a \x01(\tR\blinkType\x12\x1d\n" +
	"\n" +
	"link_value\x18\b \x01(\tR\tlinkValue\x12\x1b\n" +
	"\tis_active\x18\t \x01(\bR\bisActive\x12\x19\n" +
	"\bstart_at\x18\n" +
	" \x01(\x03R\astartAt\x12\x15\n" +
	"\x06end_at\x18\v \x01(\x03R\x05endAt\x12\x12\n" +
	"\x04sort\x18\f \x01(\x05R\x04sort\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\x03R\tupdatedAt\"\xcb\x02\n" +
	"\x13CreateBannerRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\x12\x1f\n" +
	"\bposition\x18\x02 \x01(\tB\x03\xe0A\x02R\bposition\x12\x1d\n" +
	"\n" +
	"title_json\x18\x03 \x01(\tR\ttitleJson\x12\x19\n" +
	"\x05image\x18\x04 \x01(\tB\x03\xe0A\x02R\x05image\x12!\n" +
	"\fmobile_image\x18\x05 \x01(\tR\vmobileImage\x12\x1b\n" +
	"\tlink_type\x18\x06 \x01(\tR\blinkType\x12\x1d\n" +
	"\n" +
	"link_value\x18\a \x01(\tR\tlinkValue\x12\x1b\n" +
	"\tis_active\x18\b \x01(\bR\bisActive\x12\x19\n" +
	"\bstart_at\x18\t \x01(\x03R\astartAt\x12\x15\n" +
	"\x06end_at\x18\n" +
	" \x01(\x03R\x05endAt\x12\x12\n" +
	"\x04sort\x18\v \x01(\x05R\x04sort\"\xd1\x02\n" +
	"\x13UpdateBannerRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x04B\x03\xe0A\x02R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\tR\bposition\x12\x1d\n" +
	"\n" +
	"title_json\x18\x04 \x01(\tR\ttitleJson\x12\x14\n" +
	"\x05image\x18\x05 \x01(\tR\x05image\x12!\n" +
	"\fmobile_image\x18\x06 \x01(\tR\vmobileImage\x12\x1b\n" +
	"\tlink_type\x18\a \x01(\tR\blinkType\x12\x1d\n" +
	"\n" +
	"link_value\x18\b \x01(\tR\tlinkValue\x12\x1b\n" +
	"\tis_active\x18\t \x01(\bR\bisActive\x12\x19\n" +
	"\bstart_at\x18\n" +
	" \x01(\x03R\astartAt\x12\x15\n" +
	"\x06end_at\x18\v \x01(\x03R\x05endAt\x12\x12\n" +
	"\x04sort\x18\f \x01(\x05R\x04sort\"*\n" +
	"\x13DeleteBannerRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x04B\x03\xe0A\x02R\x02id\"a\n" +
	"\x12ListBannersRequest\x12\x1a\n" +
	"\bposition\x18\x01 \x01(\tR\bposition\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\x8f\x01\n" +
	"\x10ListBannersReply\x124\n" +
	"\abanners\x18\x01 \x03(\v2\x1a.zcard.api.admin.v1.BannerR\abanners\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xe6\x02\n" +
	"\x04Post\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"title_json\x18\x04 \x01(\tR\ttitleJson\x12!\n" +
	"\fsummary_json\x18\x05 \x01(\tR\vsummaryJson\x12!\n" +
	"\fcontent_json\x18\x06 \x01(\tR\vcontentJson\x12\x1c\n" +
	"\tthumbnail\x18\a \x01(\tR\tthumbnail\x12\x1f\n" +
	"\vcategory_id\x18\b \x01(\x04R\n" +
	"categoryId\x12!\n" +
	"\fis_published\x18\t \x01(\bR\visPublished\x12!\n" +
	"\fpublished_at\x18\n" +
	" \x01(\x03R\vpublishedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\x03R\tupdatedAt\"\x96\x02\n" +
	"\x11CreatePostRequest\x12\x17\n" +
	"\x04slug\x18\x01 \x01(\tB\x03\xe0A\x02R\x04slug\x12\x17\n" +
	"\x04type\x18\x02 \x01(\tB\x03\xe0A\x02R\x04type\x12\"\n" +
	"\n" +
	"title_json\x18\x03 \x01(\tB\x03\xe0A\x02R\ttitleJson\x12!\n" +
	"\fsummary_json\x18\x04 \x01(\tR\vsummaryJson\x12&\n" +
	"\fcontent_json\x18\x05 \x01(\tB\x03\xe0A\x02R\vcontentJson\x12\x1c\n" +
	"\tthumbnail\x18\x06 \x01(\tR\tthumbnail\x12\x1f\n" +
	"\vcategory_id\x18\a \x01(\x04R\n" +
	"categoryId\x12!\n" +
	"\fis_published\x18\b \x01(\bR\visPublished\"\xcc\x01\n" +
	"\x11UpdatePostRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x04B\x03\xe0A\x02R\x02id\x12\x1d\n" +
	"\n" +
	"title_json\x18\x02 \x01(\tR\ttitleJson\x12!\n" +
	"\fsummary_json\x18\x03 \x01(\tR\vsummaryJson\x12!\n" +
	"\fcontent_json\x18\x04 \x01(\tR\vcontentJson\x12\x1c\n" +
	"\tthumbnail\x18\x05 \x01(\tR\tthumbnail\x12\x1f\n" +
	"\vcategory_id\x18\x06 \x01(\x04R\n" +
	"categoryId\"C\n" +
	"\x12PublishPostRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x04B\x03\xe0A\x02R\x02id\x12\x18\n" +
	"\apublish\x18\x02 \x01(\bR\apublish\"(\n" +
	"\x11DeletePostRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x04B\x03\xe0A\x02R\x02id\"W\n" +
	"\x10ListPostsRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\x87\x01\n" +
	"\x0eListPostsReply\x12.\n" +
	"\x05posts\x18\x01 \x03(\v2\x18.zcard.api.admin.v1.PostR\x05posts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"y\n" +
	"\fPostCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\x05R\x04sort\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\"a\n" +
	"\x19CreatePostCategoryRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\x12\x17\n" +
	"\x04slug\x18\x02 \x01(\tB\x03\xe0A\x02R\x04slug\x12\x12\n" +
	"\x04sort\x18\x03 \x01(\x05R\x04sort\"X\n" +
	"\x19UpdatePostCategoryRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x04B\x03\xe0A\x02R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04sort\x18\x03 \x01(\x05R\x04sort\"0\n" +
	"\x19DeletePostCategoryRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x04B\x03\xe0A\x02R\x02id\" \n" +
	"\x1eListPostCategoriesAdminRequest\"`\n" +
	"\x1cListPostCategoriesAdminReply\x12@\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2 .zcard.api.admin.v1.PostCategoryR\n" +
	"categories2\xdb\r\n" +
	"\x13AdminContentService\x12}\n" +
	"\fCreateBanner\x12'.zcard.api.admin.v1.CreateBannerRequest\x1a\x1a.zcard.api.admin.v1.Banner\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/v1/admin/content/banners\x12\x82\x01\n" +
	"\fUpdateBanner\x12'.zcard.api.admin.v1.UpdateBannerRequest\x1a\x1a.zcard.api.admin.v1.Banner\"-\x82\xd3\xe4\x93\x02':\x01*\x1a\"/api/v1/admin/content/banners/{id}\x12{\n" +
	"\fDeleteBanner\x12'.zcard.api.admin.v1.DeleteBannerRequest\x1a\x16.google.protobuf.Empty\"*\x82\xd3\xe4\x93\x02$*\"/api/v1/admin/content/banners/{id}\x12\x82\x01\n" +
	"\vListBanners\x12&.zcard.api.admin.v1.ListBannersRequest\x1a$.zcard.api.admin.v1.ListBannersReply\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/api/v1/admin/content/banners\x12u\n" +
	"\n" +
	"CreatePost\x12%.zcard.api.admin.v1.CreatePostRequest\x1a\x18.zcard.api.admin.v1.Post\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/v1/admin/content/posts\x12z\n" +
	"\n" +
	"UpdatePost\x12%.zcard.api.admin.v1.UpdatePostRequest\x1a\x18.zcard.api.admin.v1.Post\"+\x82\xd3\xe4\x93\x02%:\x01*\x1a /api/v1/admin/content/posts/{id}\x12\x84\x01\n" +
	"\vPublishPost\x12&.zcard.api.admin.v1.PublishPostRequest\x1a\x18.zcard.api.admin.v1.Post\"3\x82\xd3\xe4\x93\x02-:\x01*\"(/api/v1/admin/content/posts/{id}/publish\x12u\n" +
	"\n" +
	"DeletePost\x12%.zcard.api.admin.v1.DeletePostRequest\x1a\x16.google.protobuf.Empty\"(\x82\xd3\xe4\x93\x02\"* /api/v1/admin/content/posts/{id}\x12z\n" +
	"\tListPosts\x12$.zcard.api.admin.v1.ListPostsRequest\x1a\".zcard.api.admin.v1.ListPostsReply\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1/admin/content/posts\x12\x8e\x01\n" +
	"\x0eCreateCategory\x12-.zcard.api.admin.v1.CreatePostCategoryRequest\x1a .zcard.api.admin.v1.PostCategory\"+\x82\xd3\xe4\x93\x02%:\x01*\" /api/v1/admin/content/categories\x12\x93\x01\n" +
	"\x0eUpdateCategory\x12-.zcard.api.admin.v1.UpdatePostCategoryRequest\x1a .zcard.api.admin.v1.PostCategory\"0\x82\xd3\xe4\x93\x02*:\x01*\x1a%/api/v1/admin/content/categories/{id}\x12\x86\x01\n" +
	"\x0eDeleteCategory\x12-.zcard.api.admin.v1.DeletePostCategoryRequest\x1a\x16.google.protobuf.Empty\"-\x82\xd3\xe4\x93\x02'*%/api/v1/admin/content/categories/{id}\x12\xa0\x01\n" +
	"\x0eListCategories\x122.zcard.api.admin.v1.ListPostCategoriesAdminRequest\x1a0.zcard.api.admin.v1.ListPostCategoriesAdminReply\"(\x82\xd3\xe4\x93\x02\"\x12 /api/v1/admin/content/categoriesB=Z;github.com/NovaWorks/zcard-next/server/api/admin/v1;adminv1b\x06proto3"

var (
	file_admin_v1_content_proto_rawDescOnce sync.Once
	file_admin_v1_content_proto_rawDescData []byte
)

func file_admin_v1_content_proto_rawDescGZIP() []byte {
	file_admin_v1_content_proto_rawDescOnce.Do(func() {
		file_admin_v1_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_v1_content_proto_rawDesc), len(file_admin_v1_content_proto_rawDesc)))
	})
	return file_admin_v1_content_proto_rawDescData
}

var file_admin_v1_content_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_admin_v1_content_proto_goTypes = []any{
	(*Banner)(nil),                         // 0: zcard.api.admin.v1.Banner
	(*CreateBannerRequest)(nil),            // 1: zcard.api.admin.v1.CreateBannerRequest
	(*UpdateBannerRequest)(nil),            // 2: zcard.api.admin.v1.UpdateBannerRequest
	(*DeleteBannerRequest)(nil),            // 3: zcard.api.admin.v1.DeleteBannerRequest
	(*ListBannersRequest)(nil),             // 4: zcard.api.admin.v1.ListBannersRequest
	(*ListBannersReply)(nil),               // 5: zcard.api.admin.v1.ListBannersReply
	(*Post)(nil),                           // 6: zcard.api.admin.v1.Post
	(*CreatePostRequest)(nil),              // 7: zcard.api.admin.v1.CreatePostRequest
	(*UpdatePostRequest)(nil),              // 8: zcard.api.admin.v1.UpdatePostRequest
	(*PublishPostRequest)(nil),             // 9: zcard.api.admin.v1.PublishPostRequest
	(*DeletePostRequest)(nil),              // 10: zcard.api.admin.v1.DeletePostRequest
	(*ListPostsRequest)(nil),               // 11: zcard.api.admin.v1.ListPostsRequest
	(*ListPostsReply)(nil),                 // 12: zcard.api.admin.v1.ListPostsReply
	(*PostCategory)(nil),                   // 13: zcard.api.admin.v1.PostCategory
	(*CreatePostCategoryRequest)(nil),      // 14: zcard.api.admin.v1.CreatePostCategoryRequest
	(*UpdatePostCategoryRequest)(nil),      // 15: zcard.api.admin.v1.UpdatePostCategoryRequest
	(*DeletePostCategoryRequest)(nil),      // 16: zcard.api.admin.v1.DeletePostCategoryRequest
	(*ListPostCategoriesAdminRequest)(nil), // 17: zcard.api.admin.v1.ListPostCategoriesAdminRequest
	(*ListPostCategoriesAdminReply)(nil),   // 18: zcard.api.admin.v1.ListPostCategoriesAdminReply
	(*emptypb.Empty)(nil),                  // 19: google.protobuf.Empty
}
var file_admin_v1_content_proto_depIdxs = []int32{
	0,  // 0: zcard.api.admin.v1.ListBannersReply.banners:type_name -> zcard.api.admin.v1.Banner
	6,  // 1: zcard.api.admin.v1.ListPostsReply.posts:type_name -> zcard.api.admin.v1.Post
	13, // 2: zcard.api.admin.v1.ListPostCategoriesAdminReply.categories:type_name -> zcard.api.admin.v1.PostCategory
	1,  // 3: zcard.api.admin.v1.AdminContentService.CreateBanner:input_type -> zcard.api.admin.v1.CreateBannerRequest
	2,  // 4: zcard.api.admin.v1.AdminContentService.UpdateBanner:input_type -> zcard.api.admin.v1.UpdateBannerRequest
	3,  // 5: zcard.api.admin.v1.AdminContentService.DeleteBanner:input_type -> zcard.api.admin.v1.DeleteBannerRequest
	4,  // 6: zcard.api.admin.v1.AdminContentService.ListBanners:input_type -> zcard.api.admin.v1.ListBannersRequest
	7,  // 7: zcard.api.admin.v1.AdminContentService.CreatePost:input_type -> zcard.api.admin.v1.CreatePostRequest
	8,  // 8: zcard.api.admin.v1.AdminContentService.UpdatePost:input_type -> zcard.api.admin.v1.UpdatePostRequest
	9,  // 9: zcard.api.admin.v1.AdminContentService.PublishPost:input_type -> zcard.api.admin.v1.PublishPostRequest
	10, // 10: zcard.api.admin.v1.AdminContentService.DeletePost:input_type -> zcard.api.admin.v1.DeletePostRequest
	11, // 11: zcard.api.admin.v1.AdminContentService.ListPosts:input_type -> zcard.api.admin.v1.ListPostsRequest
	14, // 12: zcard.api.admin.v1.AdminContentService.CreateCategory:input_type -> zcard.api.admin.v1.CreatePostCategoryRequest
	15, // 13: zcard.api.admin.v1.AdminContentService.UpdateCategory:input_type -> zcard.api.admin.v1.UpdatePostCategoryRequest
	16, // 14: zcard.api.admin.v1.AdminContentService.DeleteCategory:input_type -> zcard.api.admin.v1.DeletePostCategoryRequest
	17, // 15: zcard.api.admin.v1.AdminContentService.ListCategories:input_type -> zcard.api.admin.v1.ListPostCategoriesAdminRequest
	0,  // 16: zcard.api.admin.v1.AdminContentService.CreateBanner:output_type -> zcard.api.admin.v1.Banner
	0,  // 17: zcard.api.admin.v1.AdminContentService.UpdateBanner:output_type -> zcard.api.admin.v1.Banner
	19, // 18: zcard.api.admin.v1.AdminContentService.DeleteBanner:output_type -> google.protobuf.Empty
	5,  // 19: zcard.api.admin.v1.AdminContentService.ListBanners:output_type -> zcard.api.admin.v1.ListBannersReply
	6,  // 20: zcard.api.admin.v1.AdminContentService.CreatePost:output_type -> zcard.api.admin.v1.Post
	6,  // 21: zcard.api.admin.v1.AdminContentService.UpdatePost:output_type -> zcard.api.admin.v1.Post
	6,  // 22: zcard.api.admin.v1.AdminContentService.PublishPost:output_type -> zcard.api.admin.v1.Post
	19, // 23: zcard.api.admin.v1.AdminContentService.DeletePost:output_type -> google.protobuf.Empty
	12, // 24: zcard.api.admin.v1.AdminContentService.ListPosts:output_type -> zcard.api.admin.v1.ListPostsReply
	13, // 25: zcard.api.admin.v1.AdminContentService.CreateCategory:output_type -> zcard.api.admin.v1.PostCategory
	13, // 26: zcard.api.admin.v1.AdminContentService.UpdateCategory:output_type -> zcard.api.admin.v1.PostCategory
	19, // 27: zcard.api.admin.v1.AdminContentService.DeleteCategory:output_type -> google.protobuf.Empty
	18, // 28: zcard.api.admin.v1.AdminContentService.ListCategories:output_type -> zcard.api.admin.v1.ListPostCategoriesAdminReply
	16, // [16:29] is the sub-list for method output_type
	3,  // [3:16] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_admin_v1_content_proto_init() }
func file_admin_v1_content_proto_init() {
	if File_admin_v1_content_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_v1_content_proto_rawDesc), len(file_admin_v1_content_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_v1_content_proto_goTypes,
		DependencyIndexes: file_admin_v1_content_proto_depIdxs,
		MessageInfos:      file_admin_v1_content_proto_msgTypes,
	}.Build()
	File_admin_v1_content_proto = out.File
	file_admin_v1_content_proto_goTypes = nil
	file_admin_v1_content_proto_depIdxs = nil
}
