// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v3.0.0
// - protoc             (unknown)
// source: admin/v1/inventory.proto

package adminv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationAdminInventoryServiceCancelImport = "/zcard.api.admin.v1.AdminInventoryService/CancelImport"
const OperationAdminInventoryServiceExportCards = "/zcard.api.admin.v1.AdminInventoryService/ExportCards"
const OperationAdminInventoryServiceImportConfirm = "/zcard.api.admin.v1.AdminInventoryService/ImportConfirm"
const OperationAdminInventoryServiceImportPreview = "/zcard.api.admin.v1.AdminInventoryService/ImportPreview"
const OperationAdminInventoryServiceListCards = "/zcard.api.admin.v1.AdminInventoryService/ListCards"
const OperationAdminInventoryServiceListImports = "/zcard.api.admin.v1.AdminInventoryService/ListImports"
const OperationAdminInventoryServiceListPremiumCards = "/zcard.api.admin.v1.AdminInventoryService/ListPremiumCards"
const OperationAdminInventoryServiceToggleCard = "/zcard.api.admin.v1.AdminInventoryService/ToggleCard"
const OperationAdminInventoryServiceViewCardContent = "/zcard.api.admin.v1.AdminInventoryService/ViewCardContent"

type AdminInventoryServiceHTTPServer interface {
	// CancelImport CancelImport 撤销批次（删除本批 available 卡）。
	CancelImport(context.Context, *CancelImportRequest) (*emptypb.Empty, error)
	// ExportCards ExportCards 导出卡密（card:export 权限 + 审计 + 限流 + CsvSafe）。
	ExportCards(context.Context, *ExportCardsRequest) (*ExportCardsReply, error)
	// ImportConfirm ImportConfirm 确认导入（分片写入 + 批次追踪）。
	ImportConfirm(context.Context, *ImportConfirmRequest) (*ImportBatch, error)
	// ImportPreview ImportPreview 上传预览（去重统计 + 样本预览）。
	ImportPreview(context.Context, *ImportPreviewRequest) (*ImportPreviewReply, error)
	// ListCards ListCards 卡密列表（掩码默认；card:view_content 权限才可见完整内容）。
	ListCards(context.Context, *ListCardsRequest) (*ListCardsReply, error)
	// ListImports ListImports 导入批次列表。
	ListImports(context.Context, *ListImportsRequest) (*ListImportsReply, error)
	// ListPremiumCards ListPremiumCards 靓号列表（number_hash 命中 + 可用卡；card:premium 权限）。
	ListPremiumCards(context.Context, *ListPremiumCardsRequest) (*ListPremiumCardsReply, error)
	// ToggleCard ToggleCard 禁用/启用单张卡。
	ToggleCard(context.Context, *ToggleCardRequest) (*emptypb.Empty, error)
	// ViewCardContent ViewCardContent 查看完整卡密（card:view_content 权限 + 安全审计）。
	ViewCardContent(context.Context, *ViewCardContentRequest) (*ViewCardContentReply, error)
}

func RegisterAdminInventoryServiceHTTPServer(s *http.Server, srv AdminInventoryServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/api/v1/admin/inventory/preview", _AdminInventoryService_ImportPreview0_HTTP_Handler(srv))
	r.Handle("POST", "/api/v1/admin/inventory/import", _AdminInventoryService_ImportConfirm0_HTTP_Handler(srv))
	r.Handle("GET", "/api/v1/admin/inventory/imports", _AdminInventoryService_ListImports0_HTTP_Handler(srv))
	r.Handle("POST", "/api/v1/admin/inventory/imports/{id}/cancel", _AdminInventoryService_CancelImport0_HTTP_Handler(srv))
	r.Handle("GET", "/api/v1/admin/inventory/cards", _AdminInventoryService_ListCards0_HTTP_Handler(srv))
	r.Handle("POST", "/api/v1/admin/inventory/export", _AdminInventoryService_ExportCards0_HTTP_Handler(srv))
	r.Handle("PUT", "/api/v1/admin/inventory/cards/{id}/toggle", _AdminInventoryService_ToggleCard0_HTTP_Handler(srv))
	r.Handle("GET", "/api/v1/admin/inventory/cards/{id}/content", _AdminInventoryService_ViewCardContent0_HTTP_Handler(srv))
	r.Handle("GET", "/api/v1/admin/inventory/cards/premium", _AdminInventoryService_ListPremiumCards0_HTTP_Handler(srv))
}

func _AdminInventoryService_ImportPreview0_HTTP_Handler(srv AdminInventoryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ImportPreviewRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminInventoryServiceImportPreview)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ImportPreview(ctx, req.(*ImportPreviewRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ImportPreviewReply)
		return ctx.Result(200, reply)
	}
}

func _AdminInventoryService_ImportConfirm0_HTTP_Handler(srv AdminInventoryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ImportConfirmRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminInventoryServiceImportConfirm)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ImportConfirm(ctx, req.(*ImportConfirmRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ImportBatch)
		return ctx.Result(200, reply)
	}
}

func _AdminInventoryService_ListImports0_HTTP_Handler(srv AdminInventoryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListImportsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminInventoryServiceListImports)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListImports(ctx, req.(*ListImportsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListImportsReply)
		return ctx.Result(200, reply)
	}
}

func _AdminInventoryService_CancelImport0_HTTP_Handler(srv AdminInventoryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CancelImportRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminInventoryServiceCancelImport)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CancelImport(ctx, req.(*CancelImportRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _AdminInventoryService_ListCards0_HTTP_Handler(srv AdminInventoryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListCardsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminInventoryServiceListCards)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListCards(ctx, req.(*ListCardsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListCardsReply)
		return ctx.Result(200, reply)
	}
}

func _AdminInventoryService_ExportCards0_HTTP_Handler(srv AdminInventoryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ExportCardsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminInventoryServiceExportCards)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ExportCards(ctx, req.(*ExportCardsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ExportCardsReply)
		return ctx.Result(200, reply)
	}
}

func _AdminInventoryService_ToggleCard0_HTTP_Handler(srv AdminInventoryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ToggleCardRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminInventoryServiceToggleCard)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ToggleCard(ctx, req.(*ToggleCardRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _AdminInventoryService_ViewCardContent0_HTTP_Handler(srv AdminInventoryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ViewCardContentRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminInventoryServiceViewCardContent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ViewCardContent(ctx, req.(*ViewCardContentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ViewCardContentReply)
		return ctx.Result(200, reply)
	}
}

func _AdminInventoryService_ListPremiumCards0_HTTP_Handler(srv AdminInventoryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListPremiumCardsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminInventoryServiceListPremiumCards)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListPremiumCards(ctx, req.(*ListPremiumCardsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListPremiumCardsReply)
		return ctx.Result(200, reply)
	}
}

type AdminInventoryServiceHTTPClient interface {
	// CancelImport CancelImport 撤销批次（删除本批 available 卡）。
	CancelImport(ctx context.Context, req *CancelImportRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// ExportCards ExportCards 导出卡密（card:export 权限 + 审计 + 限流 + CsvSafe）。
	ExportCards(ctx context.Context, req *ExportCardsRequest, opts ...http.CallOption) (rsp *ExportCardsReply, err error)
	// ImportConfirm ImportConfirm 确认导入（分片写入 + 批次追踪）。
	ImportConfirm(ctx context.Context, req *ImportConfirmRequest, opts ...http.CallOption) (rsp *ImportBatch, err error)
	// ImportPreview ImportPreview 上传预览（去重统计 + 样本预览）。
	ImportPreview(ctx context.Context, req *ImportPreviewRequest, opts ...http.CallOption) (rsp *ImportPreviewReply, err error)
	// ListCards ListCards 卡密列表（掩码默认；card:view_content 权限才可见完整内容）。
	ListCards(ctx context.Context, req *ListCardsRequest, opts ...http.CallOption) (rsp *ListCardsReply, err error)
	// ListImports ListImports 导入批次列表。
	ListImports(ctx context.Context, req *ListImportsRequest, opts ...http.CallOption) (rsp *ListImportsReply, err error)
	// ListPremiumCards ListPremiumCards 靓号列表（number_hash 命中 + 可用卡；card:premium 权限）。
	ListPremiumCards(ctx context.Context, req *ListPremiumCardsRequest, opts ...http.CallOption) (rsp *ListPremiumCardsReply, err error)
	// ToggleCard ToggleCard 禁用/启用单张卡。
	ToggleCard(ctx context.Context, req *ToggleCardRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// ViewCardContent ViewCardContent 查看完整卡密（card:view_content 权限 + 安全审计）。
	ViewCardContent(ctx context.Context, req *ViewCardContentRequest, opts ...http.CallOption) (rsp *ViewCardContentReply, err error)
}

type AdminInventoryServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewAdminInventoryServiceHTTPClient(client *http.Client) AdminInventoryServiceHTTPClient {
	return &AdminInventoryServiceHTTPClientImpl{client}
}

// CancelImport CancelImport 撤销批次（删除本批 available 卡）。
func (c *AdminInventoryServiceHTTPClientImpl) CancelImport(ctx context.Context, in *CancelImportRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/v1/admin/inventory/imports/{id}/cancel"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAdminInventoryServiceCancelImport),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ExportCards ExportCards 导出卡密（card:export 权限 + 审计 + 限流 + CsvSafe）。
func (c *AdminInventoryServiceHTTPClientImpl) ExportCards(ctx context.Context, in *ExportCardsRequest, opts ...http.CallOption) (*ExportCardsReply, error) {
	var out ExportCardsReply
	pattern := "/api/v1/admin/inventory/export"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAdminInventoryServiceExportCards),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ImportConfirm ImportConfirm 确认导入（分片写入 + 批次追踪）。
func (c *AdminInventoryServiceHTTPClientImpl) ImportConfirm(ctx context.Context, in *ImportConfirmRequest, opts ...http.CallOption) (*ImportBatch, error) {
	var out ImportBatch
	pattern := "/api/v1/admin/inventory/import"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAdminInventoryServiceImportConfirm),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ImportPreview ImportPreview 上传预览（去重统计 + 样本预览）。
func (c *AdminInventoryServiceHTTPClientImpl) ImportPreview(ctx context.Context, in *ImportPreviewRequest, opts ...http.CallOption) (*ImportPreviewReply, error) {
	var out ImportPreviewReply
	pattern := "/api/v1/admin/inventory/preview"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAdminInventoryServiceImportPreview),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListCards ListCards 卡密列表（掩码默认；card:view_content 权限才可见完整内容）。
func (c *AdminInventoryServiceHTTPClientImpl) ListCards(ctx context.Context, in *ListCardsRequest, opts ...http.CallOption) (*ListCardsReply, error) {
	var out ListCardsReply
	pattern := "/api/v1/admin/inventory/cards"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminInventoryServiceListCards),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListImports ListImports 导入批次列表。
func (c *AdminInventoryServiceHTTPClientImpl) ListImports(ctx context.Context, in *ListImportsRequest, opts ...http.CallOption) (*ListImportsReply, error) {
	var out ListImportsReply
	pattern := "/api/v1/admin/inventory/imports"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminInventoryServiceListImports),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListPremiumCards ListPremiumCards 靓号列表（number_hash 命中 + 可用卡；card:premium 权限）。
func (c *AdminInventoryServiceHTTPClientImpl) ListPremiumCards(ctx context.Context, in *ListPremiumCardsRequest, opts ...http.CallOption) (*ListPremiumCardsReply, error) {
	var out ListPremiumCardsReply
	pattern := "/api/v1/admin/inventory/cards/premium"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminInventoryServiceListPremiumCards),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ToggleCard ToggleCard 禁用/启用单张卡。
func (c *AdminInventoryServiceHTTPClientImpl) ToggleCard(ctx context.Context, in *ToggleCardRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/v1/admin/inventory/cards/{id}/toggle"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAdminInventoryServiceToggleCard),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ViewCardContent ViewCardContent 查看完整卡密（card:view_content 权限 + 安全审计）。
func (c *AdminInventoryServiceHTTPClientImpl) ViewCardContent(ctx context.Context, in *ViewCardContentRequest, opts ...http.CallOption) (*ViewCardContentReply, error) {
	var out ViewCardContentReply
	pattern := "/api/v1/admin/inventory/cards/{id}/content"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminInventoryServiceViewCardContent),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
