// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: admin/v1/memberlevel.proto

package adminv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MemberLevel struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ThresholdType     string                 `protobuf:"bytes,3,opt,name=threshold_type,json=thresholdType,proto3" json:"threshold_type,omitempty"`
	ThresholdRecharge int64                  `protobuf:"varint,4,opt,name=threshold_recharge,json=thresholdRecharge,proto3" json:"threshold_recharge,omitempty"`
	ThresholdConsume  int64                  `protobuf:"varint,5,opt,name=threshold_consume,json=thresholdConsume,proto3" json:"threshold_consume,omitempty"`
	Discount          int32                  `protobuf:"varint,6,opt,name=discount,proto3" json:"discount,omitempty"` // 万分比
	Sort              int32                  `protobuf:"varint,7,opt,name=sort,proto3" json:"sort,omitempty"`
	Enabled           bool                   `protobuf:"varint,8,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// 积分产生规则 JSON：{"spend_cents": 每消费多少分, "points": 产出积分数}
	PointsRuleJson string `protobuf:"bytes,9,opt,name=points_rule_json,json=pointsRuleJson,proto3" json:"points_rule_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MemberLevel) Reset() {
	*x = MemberLevel{}
	mi := &file_admin_v1_memberlevel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberLevel) ProtoMessage() {}

func (x *MemberLevel) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_memberlevel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberLevel.ProtoReflect.Descriptor instead.
func (*MemberLevel) Descriptor() ([]byte, []int) {
	return file_admin_v1_memberlevel_proto_rawDescGZIP(), []int{0}
}

func (x *MemberLevel) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MemberLevel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MemberLevel) GetThresholdType() string {
	if x != nil {
		return x.ThresholdType
	}
	return ""
}

func (x *MemberLevel) GetThresholdRecharge() int64 {
	if x != nil {
		return x.ThresholdRecharge
	}
	return 0
}

func (x *MemberLevel) GetThresholdConsume() int64 {
	if x != nil {
		return x.ThresholdConsume
	}
	return 0
}

func (x *MemberLevel) GetDiscount() int32 {
	if x != nil {
		return x.Discount
	}
	return 0
}

func (x *MemberLevel) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *MemberLevel) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *MemberLevel) GetPointsRuleJson() string {
	if x != nil {
		return x.PointsRuleJson
	}
	return ""
}

type MemberLevelList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Levels        []*MemberLevel         `protobuf:"bytes,1,rep,name=levels,proto3" json:"levels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberLevelList) Reset() {
	*x = MemberLevelList{}
	mi := &file_admin_v1_memberlevel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberLevelList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberLevelList) ProtoMessage() {}

func (x *MemberLevelList) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_memberlevel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberLevelList.ProtoReflect.Descriptor instead.
func (*MemberLevelList) Descriptor() ([]byte, []int) {
	return file_admin_v1_memberlevel_proto_rawDescGZIP(), []int{1}
}

func (x *MemberLevelList) GetLevels() []*MemberLevel {
	if x != nil {
		return x.Levels
	}
	return nil
}

type CreateMemberLevelRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ThresholdType     string                 `protobuf:"bytes,2,opt,name=threshold_type,json=thresholdType,proto3" json:"threshold_type,omitempty"`
	ThresholdRecharge int64                  `protobuf:"varint,3,opt,name=threshold_recharge,json=thresholdRecharge,proto3" json:"threshold_recharge,omitempty"`
	ThresholdConsume  int64                  `protobuf:"varint,4,opt,name=threshold_consume,json=thresholdConsume,proto3" json:"threshold_consume,omitempty"`
	Discount          int32                  `protobuf:"varint,5,opt,name=discount,proto3" json:"discount,omitempty"`
	Sort              int32                  `protobuf:"varint,6,opt,name=sort,proto3" json:"sort,omitempty"`
	Enabled           bool                   `protobuf:"varint,7,opt,name=enabled,proto3" json:"enabled,omitempty"`
	PointsRuleJson    string                 `protobuf:"bytes,8,opt,name=points_rule_json,json=pointsRuleJson,proto3" json:"points_rule_json,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateMemberLevelRequest) Reset() {
	*x = CreateMemberLevelRequest{}
	mi := &file_admin_v1_memberlevel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMemberLevelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMemberLevelRequest) ProtoMessage() {}

func (x *CreateMemberLevelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_memberlevel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMemberLevelRequest.ProtoReflect.Descriptor instead.
func (*CreateMemberLevelRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_memberlevel_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMemberLevelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMemberLevelRequest) GetThresholdType() string {
	if x != nil {
		return x.ThresholdType
	}
	return ""
}

func (x *CreateMemberLevelRequest) GetThresholdRecharge() int64 {
	if x != nil {
		return x.ThresholdRecharge
	}
	return 0
}

func (x *CreateMemberLevelRequest) GetThresholdConsume() int64 {
	if x != nil {
		return x.ThresholdConsume
	}
	return 0
}

func (x *CreateMemberLevelRequest) GetDiscount() int32 {
	if x != nil {
		return x.Discount
	}
	return 0
}

func (x *CreateMemberLevelRequest) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *CreateMemberLevelRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *CreateMemberLevelRequest) GetPointsRuleJson() string {
	if x != nil {
		return x.PointsRuleJson
	}
	return ""
}

type UpdateMemberLevelRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Discount       int32                  `protobuf:"varint,3,opt,name=discount,proto3" json:"discount,omitempty"`
	Sort           int32                  `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"`
	Enabled        bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	PointsRuleJson string                 `protobuf:"bytes,6,opt,name=points_rule_json,json=pointsRuleJson,proto3" json:"points_rule_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateMemberLevelRequest) Reset() {
	*x = UpdateMemberLevelRequest{}
	mi := &file_admin_v1_memberlevel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMemberLevelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemberLevelRequest) ProtoMessage() {}

func (x *UpdateMemberLevelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_memberlevel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemberLevelRequest.ProtoReflect.Descriptor instead.
func (*UpdateMemberLevelRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_memberlevel_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateMemberLevelRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateMemberLevelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateMemberLevelRequest) GetDiscount() int32 {
	if x != nil {
		return x.Discount
	}
	return 0
}

func (x *UpdateMemberLevelRequest) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *UpdateMemberLevelRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *UpdateMemberLevelRequest) GetPointsRuleJson() string {
	if x != nil {
		return x.PointsRuleJson
	}
	return ""
}

type DeleteMemberLevelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMemberLevelRequest) Reset() {
	*x = DeleteMemberLevelRequest{}
	mi := &file_admin_v1_memberlevel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMemberLevelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMemberLevelRequest) ProtoMessage() {}

func (x *DeleteMemberLevelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_memberlevel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMemberLevelRequest.ProtoReflect.Descriptor instead.
func (*DeleteMemberLevelRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_memberlevel_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteMemberLevelRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_admin_v1_memberlevel_proto protoreflect.FileDescriptor

const file_admin_v1_memberlevel_proto_rawDesc = "" +
	"\n" +
	"\x1aadmin/v1/memberlevel.proto\x12\x12zcard.api.admin.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xa8\x02\n" +
	"\vMemberLevel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0ethreshold_type\x18\x03 \x01(\tR\rthresholdType\x12-\n" +
	"\x12threshold_recharge\x18\x04 \x01(\x03R\x11thresholdRecharge\x12+\n" +
	"\x11threshold_consume\x18\x05 \x01(\x03R\x10thresholdConsume\x12\x1a\n" +
	"\bdiscount\x18\x06 \x01(\x05R\bdiscount\x12\x12\n" +
	"\x04sort\x18\a \x01(\x05R\x04sort\x12\x18\n" +
	"\aenabled\x18\b \x01(\bR\aenabled\x12(\n" +
	"\x10points_rule_json\x18\t \x01(\tR\x0epointsRuleJson\"J\n" +
	"\x0fMemberLevelList\x127\n" +
	"\x06levels\x18\x01 \x03(\v2\x1f.zcard.api.admin.v1.MemberLevelR\x06levels\"\xa5\x02\n" +
	"\x18CreateMemberLevelRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0ethreshold_type\x18\x02 \x01(\tR\rthresholdType\x12-\n" +
	"\x12threshold_recharge\x18\x03 \x01(\x03R\x11thresholdRecharge\x12+\n" +
	"\x11threshold_consume\x18\x04 \x01(\x03R\x10thresholdConsume\x12\x1a\n" +
	"\bdiscount\x18\x05 \x01(\x05R\bdiscount\x12\x12\n" +
	"\x04sort\x18\x06 \x01(\x05R\x04sort\x12\x18\n" +
	"\aenabled\x18\a \x01(\bR\aenabled\x12(\n" +
	"\x10points_rule_json\x18\b \x01(\tR\x0epointsRuleJson\"\xb2\x01\n" +
	"\x18UpdateMemberLevelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bdiscount\x18\x03 \x01(\x05R\bdiscount\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\x05R\x04sort\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12(\n" +
	"\x10points_rule_json\x18\x06 \x01(\tR\x0epointsRuleJson\"*\n" +
	"\x18DeleteMemberLevelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id2\xb4\x04\n" +
	"\x17AdminMemberLevelService\x12t\n" +
	"\x10ListMemberLevels\x12\x16.google.protobuf.Empty\x1a#.zcard.api.admin.v1.MemberLevelList\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1/admin/member-levels\x12\x8a\x01\n" +
	"\x11CreateMemberLevel\x12,.zcard.api.admin.v1.CreateMemberLevelRequest\x1a\x1f.zcard.api.admin.v1.MemberLevel\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/v1/admin/member-levels\x12\x8f\x01\n" +
	"\x11UpdateMemberLevel\x12,.zcard.api.admin.v1.UpdateMemberLevelRequest\x1a\x1f.zcard.api.admin.v1.MemberLevel\"+\x82\xd3\xe4\x93\x02%:\x01*\x1a /api/v1/admin/member-levels/{id}\x12\x83\x01\n" +
	"\x11DeleteMemberLevel\x12,.zcard.api.admin.v1.DeleteMemberLevelRequest\x1a\x16.google.protobuf.Empty\"(\x82\xd3\xe4\x93\x02\"* /api/v1/admin/member-levels/{id}B=Z;github.com/NovaWorks/zcard-next/server/api/admin/v1;adminv1b\x06proto3"

var (
	file_admin_v1_memberlevel_proto_rawDescOnce sync.Once
	file_admin_v1_memberlevel_proto_rawDescData []byte
)

func file_admin_v1_memberlevel_proto_rawDescGZIP() []byte {
	file_admin_v1_memberlevel_proto_rawDescOnce.Do(func() {
		file_admin_v1_memberlevel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_v1_memberlevel_proto_rawDesc), len(file_admin_v1_memberlevel_proto_rawDesc)))
	})
	return file_admin_v1_memberlevel_proto_rawDescData
}

var file_admin_v1_memberlevel_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_admin_v1_memberlevel_proto_goTypes = []any{
	(*MemberLevel)(nil),              // 0: zcard.api.admin.v1.MemberLevel
	(*MemberLevelList)(nil),          // 1: zcard.api.admin.v1.MemberLevelList
	(*CreateMemberLevelRequest)(nil), // 2: zcard.api.admin.v1.CreateMemberLevelRequest
	(*UpdateMemberLevelRequest)(nil), // 3: zcard.api.admin.v1.UpdateMemberLevelRequest
	(*DeleteMemberLevelRequest)(nil), // 4: zcard.api.admin.v1.DeleteMemberLevelRequest
	(*emptypb.Empty)(nil),            // 5: google.protobuf.Empty
}
var file_admin_v1_memberlevel_proto_depIdxs = []int32{
	0, // 0: zcard.api.admin.v1.MemberLevelList.levels:type_name -> zcard.api.admin.v1.MemberLevel
	5, // 1: zcard.api.admin.v1.AdminMemberLevelService.ListMemberLevels:input_type -> google.protobuf.Empty
	2, // 2: zcard.api.admin.v1.AdminMemberLevelService.CreateMemberLevel:input_type -> zcard.api.admin.v1.CreateMemberLevelRequest
	3, // 3: zcard.api.admin.v1.AdminMemberLevelService.UpdateMemberLevel:input_type -> zcard.api.admin.v1.UpdateMemberLevelRequest
	4, // 4: zcard.api.admin.v1.AdminMemberLevelService.DeleteMemberLevel:input_type -> zcard.api.admin.v1.DeleteMemberLevelRequest
	1, // 5: zcard.api.admin.v1.AdminMemberLevelService.ListMemberLevels:output_type -> zcard.api.admin.v1.MemberLevelList
	0, // 6: zcard.api.admin.v1.AdminMemberLevelService.CreateMemberLevel:output_type -> zcard.api.admin.v1.MemberLevel
	0, // 7: zcard.api.admin.v1.AdminMemberLevelService.UpdateMemberLevel:output_type -> zcard.api.admin.v1.MemberLevel
	5, // 8: zcard.api.admin.v1.AdminMemberLevelService.DeleteMemberLevel:output_type -> google.protobuf.Empty
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_admin_v1_memberlevel_proto_init() }
func file_admin_v1_memberlevel_proto_init() {
	if File_admin_v1_memberlevel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_v1_memberlevel_proto_rawDesc), len(file_admin_v1_memberlevel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_v1_memberlevel_proto_goTypes,
		DependencyIndexes: file_admin_v1_memberlevel_proto_depIdxs,
		MessageInfos:      file_admin_v1_memberlevel_proto_msgTypes,
	}.Build()
	File_admin_v1_memberlevel_proto = out.File
	file_admin_v1_memberlevel_proto_goTypes = nil
	file_admin_v1_memberlevel_proto_depIdxs = nil
}
