// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v3.0.0
// - protoc             (unknown)
// source: admin/v1/memberlevel.proto

package adminv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationAdminMemberLevelServiceCreateMemberLevel = "/zcard.api.admin.v1.AdminMemberLevelService/CreateMemberLevel"
const OperationAdminMemberLevelServiceDeleteMemberLevel = "/zcard.api.admin.v1.AdminMemberLevelService/DeleteMemberLevel"
const OperationAdminMemberLevelServiceListMemberLevels = "/zcard.api.admin.v1.AdminMemberLevelService/ListMemberLevels"
const OperationAdminMemberLevelServiceUpdateMemberLevel = "/zcard.api.admin.v1.AdminMemberLevelService/UpdateMemberLevel"

type AdminMemberLevelServiceHTTPServer interface {
	CreateMemberLevel(context.Context, *CreateMemberLevelRequest) (*MemberLevel, error)
	DeleteMemberLevel(context.Context, *DeleteMemberLevelRequest) (*emptypb.Empty, error)
	ListMemberLevels(context.Context, *emptypb.Empty) (*MemberLevelList, error)
	UpdateMemberLevel(context.Context, *UpdateMemberLevelRequest) (*MemberLevel, error)
}

func RegisterAdminMemberLevelServiceHTTPServer(s *http.Server, srv AdminMemberLevelServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/api/v1/admin/member-levels", _AdminMemberLevelService_ListMemberLevels0_HTTP_Handler(srv))
	r.Handle("POST", "/api/v1/admin/member-levels", _AdminMemberLevelService_CreateMemberLevel0_HTTP_Handler(srv))
	r.Handle("PUT", "/api/v1/admin/member-levels/{id}", _AdminMemberLevelService_UpdateMemberLevel0_HTTP_Handler(srv))
	r.Handle("DELETE", "/api/v1/admin/member-levels/{id}", _AdminMemberLevelService_DeleteMemberLevel0_HTTP_Handler(srv))
}

func _AdminMemberLevelService_ListMemberLevels0_HTTP_Handler(srv AdminMemberLevelServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminMemberLevelServiceListMemberLevels)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMemberLevels(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MemberLevelList)
		return ctx.Result(200, reply)
	}
}

func _AdminMemberLevelService_CreateMemberLevel0_HTTP_Handler(srv AdminMemberLevelServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateMemberLevelRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminMemberLevelServiceCreateMemberLevel)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateMemberLevel(ctx, req.(*CreateMemberLevelRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MemberLevel)
		return ctx.Result(200, reply)
	}
}

func _AdminMemberLevelService_UpdateMemberLevel0_HTTP_Handler(srv AdminMemberLevelServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateMemberLevelRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminMemberLevelServiceUpdateMemberLevel)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateMemberLevel(ctx, req.(*UpdateMemberLevelRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MemberLevel)
		return ctx.Result(200, reply)
	}
}

func _AdminMemberLevelService_DeleteMemberLevel0_HTTP_Handler(srv AdminMemberLevelServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteMemberLevelRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminMemberLevelServiceDeleteMemberLevel)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteMemberLevel(ctx, req.(*DeleteMemberLevelRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

type AdminMemberLevelServiceHTTPClient interface {
	CreateMemberLevel(ctx context.Context, req *CreateMemberLevelRequest, opts ...http.CallOption) (rsp *MemberLevel, err error)
	DeleteMemberLevel(ctx context.Context, req *DeleteMemberLevelRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	ListMemberLevels(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *MemberLevelList, err error)
	UpdateMemberLevel(ctx context.Context, req *UpdateMemberLevelRequest, opts ...http.CallOption) (rsp *MemberLevel, err error)
}

type AdminMemberLevelServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewAdminMemberLevelServiceHTTPClient(client *http.Client) AdminMemberLevelServiceHTTPClient {
	return &AdminMemberLevelServiceHTTPClientImpl{client}
}

func (c *AdminMemberLevelServiceHTTPClientImpl) CreateMemberLevel(ctx context.Context, in *CreateMemberLevelRequest, opts ...http.CallOption) (*MemberLevel, error) {
	var out MemberLevel
	pattern := "/api/v1/admin/member-levels"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAdminMemberLevelServiceCreateMemberLevel),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminMemberLevelServiceHTTPClientImpl) DeleteMemberLevel(ctx context.Context, in *DeleteMemberLevelRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/v1/admin/member-levels/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminMemberLevelServiceDeleteMemberLevel),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminMemberLevelServiceHTTPClientImpl) ListMemberLevels(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*MemberLevelList, error) {
	var out MemberLevelList
	pattern := "/api/v1/admin/member-levels"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminMemberLevelServiceListMemberLevels),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminMemberLevelServiceHTTPClientImpl) UpdateMemberLevel(ctx context.Context, in *UpdateMemberLevelRequest, opts ...http.CallOption) (*MemberLevel, error) {
	var out MemberLevel
	pattern := "/api/v1/admin/member-levels/{id}"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAdminMemberLevelServiceUpdateMemberLevel),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
