-- Modify "supply_connections" table
ALTER TABLE "supply_connections" ADD COLUMN "low_stock_scanned_at" bigint NOT NULL DEFAULT 0, ADD COLUMN "low_stock_message" character varying NOT NULL DEFAULT '';
-- Modify "supply_mappings" table
ALTER TABLE "supply_mappings" ADD COLUMN "stock_probe_after" bigint NOT NULL DEFAULT 0, ADD COLUMN "stock_probe_lease" bigint NOT NULL DEFAULT 0, ADD COLUMN "stock_probe_failures" bigint NOT NULL DEFAULT 0;
-- Create index "supplymapping_connection_id_stock_probe_after_id" to table: "supply_mappings"
CREATE INDEX "supplymapping_connection_id_stock_probe_after_id" ON "supply_mappings" ("connection_id", "stock_probe_after", "id");
-- Create "stock_alerts" table
CREATE TABLE "stock_alerts" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "product_id" bigint NOT NULL, "sku_id" bigint NOT NULL DEFAULT 0, "source_key" character varying NOT NULL, "threshold" bigint NOT NULL DEFAULT 0, "state" smallint NOT NULL DEFAULT 0, "notified_state" smallint NOT NULL DEFAULT 0, "last_notified_at" bigint NOT NULL DEFAULT 0, PRIMARY KEY ("id"));
-- Create index "stockalert_product_id_sku_id" to table: "stock_alerts"
CREATE UNIQUE INDEX "stockalert_product_id_sku_id" ON "stock_alerts" ("product_id", "sku_id");
