-- Modify "categories" table
ALTER TABLE "categories" ADD COLUMN "placement_version" bigint NOT NULL DEFAULT 0;
-- Modify "product_content_batches" table
ALTER TABLE "product_content_batches" ADD COLUMN "skipped_locked" integer NOT NULL DEFAULT 0;
-- Modify "products" table
ALTER TABLE "products" ADD COLUMN "is_locked" boolean NOT NULL DEFAULT false, ADD COLUMN "lock_version" bigint NOT NULL DEFAULT 0, ADD COLUMN "locked_by" bigint NOT NULL DEFAULT 0, ADD COLUMN "locked_at" timestamptz NULL;
-- Create "category_product_placements" table
CREATE TABLE "category_product_placements" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "subsite_id" bigint NOT NULL DEFAULT 0, "category_id" bigint NOT NULL, "product_id" bigint NOT NULL, "is_pinned" boolean NOT NULL DEFAULT false, "is_recommended" boolean NOT NULL DEFAULT false, "position" integer NOT NULL DEFAULT 0, PRIMARY KEY ("id"));
-- Create index "categoryproductplacement_subsite_id_category_id_product_id" to table: "category_product_placements"
CREATE UNIQUE INDEX "categoryproductplacement_subsite_id_category_id_product_id" ON "category_product_placements" ("subsite_id", "category_id", "product_id");
-- Create index "categoryproductplacement_subsite_id_product_id" to table: "category_product_placements"
CREATE INDEX "categoryproductplacement_subsite_id_product_id" ON "category_product_placements" ("subsite_id", "product_id");
