-- Modify "orders" table
ALTER TABLE "orders" ADD COLUMN "request_fingerprint" character varying NULL, ADD COLUMN "plugin_decisions" jsonb NULL;
-- Modify "products" table
ALTER TABLE "products" ADD COLUMN "plugin_rule_revision" bigint NOT NULL DEFAULT 0;
-- Create "installed_plugins" table
CREATE TABLE "installed_plugins" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "plugin_id" character varying NOT NULL, "desired_enabled" boolean NOT NULL DEFAULT false, "desired_generation" bigint NOT NULL DEFAULT 0, "observed_generation" bigint NOT NULL DEFAULT 0, "desired_digest" character varying NOT NULL DEFAULT '', "observed_digest" character varying NOT NULL DEFAULT '', "approved_scopes" jsonb NULL, "block_reasons" jsonb NULL, "current_operation_id" character varying NOT NULL DEFAULT '', "uninstalled" boolean NOT NULL DEFAULT false, PRIMARY KEY ("id"));
-- Create index "installed_plugins_plugin_id_key" to table: "installed_plugins"
CREATE UNIQUE INDEX "installed_plugins_plugin_id_key" ON "installed_plugins" ("plugin_id");
-- Create "plugin_data" table
CREATE TABLE "plugin_data" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "plugin_id" character varying NOT NULL, "subsite_id" bigint NOT NULL, "entity_type" character varying NOT NULL, "entity_id" bigint NOT NULL, "key" character varying NOT NULL, "payload" bytea NOT NULL, "schema_version" bigint NOT NULL DEFAULT 1, "revision" bigint NOT NULL DEFAULT 0, PRIMARY KEY ("id"));
-- Create index "plugindata_plugin_id_subsite_id_entity_type_entity_id_key" to table: "plugin_data"
CREATE UNIQUE INDEX "plugindata_plugin_id_subsite_id_entity_type_entity_id_key" ON "plugin_data" ("plugin_id", "subsite_id", "entity_type", "entity_id", "key");
-- Create "plugin_operations" table
CREATE TABLE "plugin_operations" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "operation_id" character varying NOT NULL, "plugin_id" character varying NOT NULL, "action" character varying NOT NULL, "request_sha256" character varying NOT NULL, "actor_id" bigint NOT NULL, "subsite_id" bigint NOT NULL, "expected_generation" bigint NOT NULL, "target_generation" bigint NOT NULL DEFAULT 0, "target_digest" character varying NOT NULL DEFAULT '', "approved_scopes" jsonb NULL, "phase" character varying NOT NULL, "failure_code" character varying NOT NULL DEFAULT '', PRIMARY KEY ("id"));
-- Create index "plugin_operations_operation_id_key" to table: "plugin_operations"
CREATE UNIQUE INDEX "plugin_operations_operation_id_key" ON "plugin_operations" ("operation_id");
-- Create index "pluginoperation_plugin_id_created_at" to table: "plugin_operations"
CREATE INDEX "pluginoperation_plugin_id_created_at" ON "plugin_operations" ("plugin_id", "created_at");
-- Create "plugin_requirements" table
CREATE TABLE "plugin_requirements" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "plugin_id" character varying NOT NULL, "subsite_id" bigint NOT NULL, "product_id" bigint NOT NULL, "required" boolean NOT NULL DEFAULT false, "revision" bigint NOT NULL DEFAULT 0, PRIMARY KEY ("id"));
-- Create index "pluginrequirement_plugin_id_subsite_id_product_id" to table: "plugin_requirements"
CREATE UNIQUE INDEX "pluginrequirement_plugin_id_subsite_id_product_id" ON "plugin_requirements" ("plugin_id", "subsite_id", "product_id");
-- Create index "pluginrequirement_subsite_id_product_id" to table: "plugin_requirements"
CREATE INDEX "pluginrequirement_subsite_id_product_id" ON "plugin_requirements" ("subsite_id", "product_id");
-- Create "plugin_rule_level_refs" table
CREATE TABLE "plugin_rule_level_refs" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "plugin_id" character varying NOT NULL, "subsite_id" bigint NOT NULL, "product_id" bigint NOT NULL, "level_id" bigint NOT NULL, PRIMARY KEY ("id"));
-- Create index "pluginrulelevelref_level_id" to table: "plugin_rule_level_refs"
CREATE INDEX "pluginrulelevelref_level_id" ON "plugin_rule_level_refs" ("level_id");
-- Create index "pluginrulelevelref_plugin_id_subsite_id_product_id_level_id" to table: "plugin_rule_level_refs"
CREATE UNIQUE INDEX "pluginrulelevelref_plugin_id_subsite_id_product_id_level_id" ON "plugin_rule_level_refs" ("plugin_id", "subsite_id", "product_id", "level_id");
