// Code generated by ent, DO NOT EDIT.

package procurementorder

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the procurementorder type in the database.
	Label = "procurement_order"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldOrderItemID holds the string denoting the order_item_id field in the database.
	FieldOrderItemID = "order_item_id"
	// FieldConnectionID holds the string denoting the connection_id field in the database.
	FieldConnectionID = "connection_id"
	// FieldUpstreamOrderID holds the string denoting the upstream_order_id field in the database.
	FieldUpstreamOrderID = "upstream_order_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldFailStrategy holds the string denoting the fail_strategy field in the database.
	FieldFailStrategy = "fail_strategy"
	// FieldRetryCount holds the string denoting the retry_count field in the database.
	FieldRetryCount = "retry_count"
	// FieldNextRetryAt holds the string denoting the next_retry_at field in the database.
	FieldNextRetryAt = "next_retry_at"
	// FieldLastPollAt holds the string denoting the last_poll_at field in the database.
	FieldLastPollAt = "last_poll_at"
	// FieldDedupeKey holds the string denoting the dedupe_key field in the database.
	FieldDedupeKey = "dedupe_key"
	// FieldTraceID holds the string denoting the trace_id field in the database.
	FieldTraceID = "trace_id"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// FieldUpstreamRefundID holds the string denoting the upstream_refund_id field in the database.
	FieldUpstreamRefundID = "upstream_refund_id"
	// Table holds the table name of the procurementorder in the database.
	Table = "procurement_orders"
)

// Columns holds all SQL columns for procurementorder fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldOrderItemID,
	FieldConnectionID,
	FieldUpstreamOrderID,
	FieldStatus,
	FieldFailStrategy,
	FieldRetryCount,
	FieldNextRetryAt,
	FieldLastPollAt,
	FieldDedupeKey,
	FieldTraceID,
	FieldLastError,
	FieldUpstreamRefundID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// UpstreamOrderIDValidator is a validator for the "upstream_order_id" field. It is called by the builders before save.
	UpstreamOrderIDValidator func(string) error
	// DefaultRetryCount holds the default value on creation for the "retry_count" field.
	DefaultRetryCount int32
	// DedupeKeyValidator is a validator for the "dedupe_key" field. It is called by the builders before save.
	DedupeKeyValidator func(string) error
	// TraceIDValidator is a validator for the "trace_id" field. It is called by the builders before save.
	TraceIDValidator func(string) error
	// UpstreamRefundIDValidator is a validator for the "upstream_refund_id" field. It is called by the builders before save.
	UpstreamRefundIDValidator func(string) error
)

// Status defines the type for the "status" enum field.
type Status string

// StatusPending is the default value of the Status enum.
const DefaultStatus = StatusPending

// Status values.
const (
	StatusPending   Status = "pending"
	StatusSubmitted Status = "submitted"
	StatusPolling   Status = "polling"
	StatusFulfilled Status = "fulfilled"
	StatusRejected  Status = "rejected"
	StatusRefunding Status = "refunding"
	StatusRefunded  Status = "refunded"
	StatusManual    Status = "manual"
	StatusFailed    Status = "failed"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPending, StatusSubmitted, StatusPolling, StatusFulfilled, StatusRejected, StatusRefunding, StatusRefunded, StatusManual, StatusFailed:
		return nil
	default:
		return fmt.Errorf("procurementorder: invalid enum value for status field: %q", s)
	}
}

// FailStrategy defines the type for the "fail_strategy" enum field.
type FailStrategy string

// FailStrategyAutoRefund is the default value of the FailStrategy enum.
const DefaultFailStrategy = FailStrategyAutoRefund

// FailStrategy values.
const (
	FailStrategyAutoRefund FailStrategy = "auto_refund"
	FailStrategyManual     FailStrategy = "manual"
)

func (fs FailStrategy) String() string {
	return string(fs)
}

// FailStrategyValidator is a validator for the "fail_strategy" field enum values. It is called by the builders before save.
func FailStrategyValidator(fs FailStrategy) error {
	switch fs {
	case FailStrategyAutoRefund, FailStrategyManual:
		return nil
	default:
		return fmt.Errorf("procurementorder: invalid enum value for fail_strategy field: %q", fs)
	}
}

// OrderOption defines the ordering options for the ProcurementOrder queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByOrderItemID orders the results by the order_item_id field.
func ByOrderItemID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderItemID, opts...).ToFunc()
}

// ByConnectionID orders the results by the connection_id field.
func ByConnectionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConnectionID, opts...).ToFunc()
}

// ByUpstreamOrderID orders the results by the upstream_order_id field.
func ByUpstreamOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamOrderID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByFailStrategy orders the results by the fail_strategy field.
func ByFailStrategy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailStrategy, opts...).ToFunc()
}

// ByRetryCount orders the results by the retry_count field.
func ByRetryCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRetryCount, opts...).ToFunc()
}

// ByNextRetryAt orders the results by the next_retry_at field.
func ByNextRetryAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextRetryAt, opts...).ToFunc()
}

// ByLastPollAt orders the results by the last_poll_at field.
func ByLastPollAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastPollAt, opts...).ToFunc()
}

// ByDedupeKey orders the results by the dedupe_key field.
func ByDedupeKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDedupeKey, opts...).ToFunc()
}

// ByTraceID orders the results by the trace_id field.
func ByTraceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTraceID, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByUpstreamRefundID orders the results by the upstream_refund_id field.
func ByUpstreamRefundID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamRefundID, opts...).ToFunc()
}
