// Run against an isolated installed localhost server, never production.
// ZCARD_TEST_BASE_URL, ZCARD_TEST_LOGIN_FILE, PLAYWRIGHT_MODULE (optional).
const fs = require('node:fs');
const assert = require('node:assert/strict');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const base = process.env.ZCARD_TEST_BASE_URL;
if (!base || !['127.0.0.1', 'localhost', '[::1]'].includes(new URL(base).hostname)) throw Error('Isolated localhost server required');
const output = process.env.ZCARD_TEST_OUTPUT || '/tmp/zcard-lock-placement-browser';
fs.mkdirSync(output, { recursive: true });
(async () => {
  const authR = await fetch(base + '/api/v1/admin/auth/login', { method: 'POST', headers: {'Content-Type':'application/json'}, body: fs.readFileSync(process.env.ZCARD_TEST_LOGIN_FILE, 'utf8') });
  assert.equal(authR.status, 200);
  const auth = await authR.json(), token = auth.token || auth.access_token;
  const api = async (url, data, method = data ? 'POST' : 'GET') => {
    const r = await fetch(base + '/api/v1/admin' + url, {method,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:data===undefined?undefined:JSON.stringify(data)});
    const b = await r.json(); assert.equal(r.status,200,JSON.stringify(b));return b;
  };
  const stamp = Date.now();
  const parent = await api('/categories', {name:`运营测试${stamp}`});
  const child = await api('/categories', {name:'子分类',parent_id:parent.id});
  const create = (name, price, status, cat=parent.id) => api('/products',{name,category_id:cat,price_cents:price,stock_type:'url',status,stock_visible:true,description:'<p>测试内容</p>',delivery_text:'https://example.com'});
  const locked = await create('锁定保留商品',1000,0);
  const pinned = await create('子分类精选商品',3000,1,child.id);
  const cheap = await create('普通低价商品',1000,1);
  const browser = await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
  const page = await browser.newPage({viewport:{width:1440,height:1000}});
  page.setDefaultTimeout(15000);
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  const drawer = page.locator('.category-placements');
  const tableRow = name => page.locator('tr.n-data-table-tr').filter({has:page.getByText(name,{exact:true})});
  try {
    await page.addInitScript(t=>localStorage.setItem('token',JSON.stringify(t)),token);
    await page.goto(base+'/admin/product');
    await page.getByText(parent.name,{exact:true}).first().click();
    const row = tableRow(locked.name);
    await row.getByRole('button',{name:'锁定',exact:true}).click();
    await page.getByRole('button',{name:'锁定商品',exact:true}).click();
    await row.getByRole('button',{name:'解锁',exact:true}).waitFor();
    assert((await api(`/products/${locked.id}`)).is_locked);
    assert(await row.getByRole('checkbox').evaluate(el=>el.classList.contains('n-checkbox--disabled')),'locked row selectable');
    await page.locator('thead').getByRole('checkbox').check();
    assert.equal(await row.getByRole('checkbox').isChecked(),false);
    assert(await page.getByText('已选',{exact:false}).filter({has:page.locator('b')}).textContent().then(s=>s.includes('2')));
    await page.locator('.n-data-table .n-scrollbar-container').evaluateAll(els=>els.forEach(el=>el.scrollLeft=0));
    await page.locator('.n-message').last().waitFor({state:'hidden'});
    await page.screenshot({path:output+'/desktop-lock.png',fullPage:true});
    await row.getByRole('button',{name:'查看',exact:true}).click();
    await page.getByText('商品已锁定',{exact:false}).last().waitFor();
    assert(await page.getByPlaceholder('请输入商品名称').isDisabled());
    assert.equal(await page.getByRole('button',{name:'保存',exact:true}).count(),0);
    await page.keyboard.press('Escape');
    await page.getByRole('button',{name:'置顶与推荐',exact:true}).click();
    await drawer.getByText('还没有置顶或推荐商品，从下方选择商品即可开始。',{exact:true}).waitFor();
    assert(await drawer.locator('.placement-candidate').filter({hasText:locked.name}).getByRole('button').isDisabled());
    await drawer.locator('.placement-candidate').filter({hasText:pinned.name}).getByRole('button').click();
    await drawer.locator('.placement-candidate').filter({hasText:cheap.name}).getByRole('button').click();
    await drawer.locator('.placement-row').filter({hasText:cheap.name}).getByRole('button',{name:'上移',exact:true}).click();
    assert((await drawer.locator('.placement-row').first().textContent()).includes(cheap.name));
    await drawer.getByRole('button',{name:'保存设置',exact:true}).click();
    await drawer.getByText('设置已保存。',{exact:false}).waitFor();
    const state=await api(`/categories/${parent.id}/placements`);
    assert.equal(state.items[0].product.id,cheap.id);assert.equal(state.items[1].product.id,pinned.id);
    await drawer.locator('.placement-row').filter({hasText:pinned.name}).getByRole('button',{name:'移到最前',exact:true}).click();
    await page.route('**/api/v1/admin/categories/*/placements',route=>route.request().method()==='PUT'?route.fulfill({status:409,contentType:'application/json',body:JSON.stringify({code:409,reason:'catalog.PLACEMENT_STALE',message:'分类设置已被更新；当前草稿已保留'})}):route.continue());
    await drawer.getByRole('button',{name:'保存设置',exact:true}).click();
    await drawer.getByText('分类设置已被更新；当前草稿已保留',{exact:false}).waitFor();
    assert((await drawer.locator('.placement-row').first().textContent()).includes(pinned.name),'failed save lost draft');
    await drawer.getByRole('button',{name:'关闭',exact:true}).click();
    await page.getByRole('button',{name:'继续编辑',exact:true}).click();
    await page.unroute('**/api/v1/admin/categories/*/placements');
    await drawer.getByRole('button',{name:'保存设置',exact:true}).click();
    await drawer.getByText('设置已保存。',{exact:false}).waitFor();
    await page.locator('.n-message').last().waitFor({state:'hidden'});
    await page.screenshot({path:output+'/desktop-placements.png',fullPage:true});
    await page.setViewportSize({width:390,height:844});
    await page.screenshot({path:output+'/mobile-placements.png',fullPage:false});
    assert(await drawer.evaluate(el=>el.scrollWidth<=el.clientWidth+1),'drawer horizontal overflow');
    const storefront=await browser.newPage({viewport:{width:1440,height:1000}});
    await storefront.goto(base+`/?category_id=${parent.id}&sort=default`);
    await storefront.getByText(pinned.name,{exact:true}).first().waitFor();
    await storefront.screenshot({path:output+'/storefront.png',fullPage:true});
    const getPublic=async query=>{const r=await fetch(base+'/api/v1/storefront/products?'+query);assert.equal(r.status,200);return r.json()};
    const list=await getPublic(`category_id=${parent.id}&sort=default`);
    assert.equal(list.items[0].id,pinned.id);assert(list.items[0].category_recommend);
    const sorted=await getPublic(`category_id=${parent.id}&sort=price_asc`);assert.equal(sorted.items[0].id,cheap.id);
    const sub=await getPublic(`category_id=${child.id}`);assert(!sub.items[0].category_recommend);
    assert(!((await api(`/products/${pinned.id}`)).is_recommend));
    assert.deepEqual(errors,[]);
    console.log(JSON.stringify({passed:true,checks:['lock confirmation and read-only editor','select-all skips off-shelf locked rows','descendant products','reorder and save','conflict preserves draft','discard confirmation','mobile drawer','storefront scoped badge and sort'],screenshots:output},null,2));
  } catch(e) { await page.screenshot({path:output+'/failure.png',fullPage:true}); fs.writeFileSync(output+'/failure.txt',await page.locator('body').innerText());throw e; }
  finally{await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
