// Code generated by ent, DO NOT EDIT.

package reconciliationjob

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/NovaWorks/zcard-next/server/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uint64) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint64) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint64) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint64) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint64) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint64) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint64) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint64) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint64) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldEQ(FieldUpdatedAt, v))
}

// ConnectionID applies equality check predicate on the "connection_id" field. It's identical to ConnectionIDEQ.
func ConnectionID(v uint64) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldEQ(FieldConnectionID, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldEQ(FieldType, v))
}

// TimeRangeStart applies equality check predicate on the "time_range_start" field. It's identical to TimeRangeStartEQ.
func TimeRangeStart(v time.Time) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldEQ(FieldTimeRangeStart, v))
}

// TimeRangeEnd applies equality check predicate on the "time_range_end" field. It's identical to TimeRangeEndEQ.
func TimeRangeEnd(v time.Time) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldEQ(FieldTimeRangeEnd, v))
}

// TotalCount applies equality check predicate on the "total_count" field. It's identical to TotalCountEQ.
func TotalCount(v int32) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldEQ(FieldTotalCount, v))
}

// MatchedCount applies equality check predicate on the "matched_count" field. It's identical to MatchedCountEQ.
func MatchedCount(v int32) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldEQ(FieldMatchedCount, v))
}

// MismatchedCount applies equality check predicate on the "mismatched_count" field. It's identical to MismatchedCountEQ.
func MismatchedCount(v int32) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldEQ(FieldMismatchedCount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldLTE(FieldUpdatedAt, v))
}

// ConnectionIDEQ applies the EQ predicate on the "connection_id" field.
func ConnectionIDEQ(v uint64) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldEQ(FieldConnectionID, v))
}

// ConnectionIDNEQ applies the NEQ predicate on the "connection_id" field.
func ConnectionIDNEQ(v uint64) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldNEQ(FieldConnectionID, v))
}

// ConnectionIDIn applies the In predicate on the "connection_id" field.
func ConnectionIDIn(vs ...uint64) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldIn(FieldConnectionID, vs...))
}

// ConnectionIDNotIn applies the NotIn predicate on the "connection_id" field.
func ConnectionIDNotIn(vs ...uint64) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldNotIn(FieldConnectionID, vs...))
}

// ConnectionIDGT applies the GT predicate on the "connection_id" field.
func ConnectionIDGT(v uint64) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldGT(FieldConnectionID, v))
}

// ConnectionIDGTE applies the GTE predicate on the "connection_id" field.
func ConnectionIDGTE(v uint64) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldGTE(FieldConnectionID, v))
}

// ConnectionIDLT applies the LT predicate on the "connection_id" field.
func ConnectionIDLT(v uint64) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldLT(FieldConnectionID, v))
}

// ConnectionIDLTE applies the LTE predicate on the "connection_id" field.
func ConnectionIDLTE(v uint64) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldLTE(FieldConnectionID, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldContainsFold(FieldType, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldNotIn(FieldStatus, vs...))
}

// TimeRangeStartEQ applies the EQ predicate on the "time_range_start" field.
func TimeRangeStartEQ(v time.Time) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldEQ(FieldTimeRangeStart, v))
}

// TimeRangeStartNEQ applies the NEQ predicate on the "time_range_start" field.
func TimeRangeStartNEQ(v time.Time) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldNEQ(FieldTimeRangeStart, v))
}

// TimeRangeStartIn applies the In predicate on the "time_range_start" field.
func TimeRangeStartIn(vs ...time.Time) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldIn(FieldTimeRangeStart, vs...))
}

// TimeRangeStartNotIn applies the NotIn predicate on the "time_range_start" field.
func TimeRangeStartNotIn(vs ...time.Time) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldNotIn(FieldTimeRangeStart, vs...))
}

// TimeRangeStartGT applies the GT predicate on the "time_range_start" field.
func TimeRangeStartGT(v time.Time) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldGT(FieldTimeRangeStart, v))
}

// TimeRangeStartGTE applies the GTE predicate on the "time_range_start" field.
func TimeRangeStartGTE(v time.Time) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldGTE(FieldTimeRangeStart, v))
}

// TimeRangeStartLT applies the LT predicate on the "time_range_start" field.
func TimeRangeStartLT(v time.Time) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldLT(FieldTimeRangeStart, v))
}

// TimeRangeStartLTE applies the LTE predicate on the "time_range_start" field.
func TimeRangeStartLTE(v time.Time) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldLTE(FieldTimeRangeStart, v))
}

// TimeRangeEndEQ applies the EQ predicate on the "time_range_end" field.
func TimeRangeEndEQ(v time.Time) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldEQ(FieldTimeRangeEnd, v))
}

// TimeRangeEndNEQ applies the NEQ predicate on the "time_range_end" field.
func TimeRangeEndNEQ(v time.Time) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldNEQ(FieldTimeRangeEnd, v))
}

// TimeRangeEndIn applies the In predicate on the "time_range_end" field.
func TimeRangeEndIn(vs ...time.Time) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldIn(FieldTimeRangeEnd, vs...))
}

// TimeRangeEndNotIn applies the NotIn predicate on the "time_range_end" field.
func TimeRangeEndNotIn(vs ...time.Time) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldNotIn(FieldTimeRangeEnd, vs...))
}

// TimeRangeEndGT applies the GT predicate on the "time_range_end" field.
func TimeRangeEndGT(v time.Time) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldGT(FieldTimeRangeEnd, v))
}

// TimeRangeEndGTE applies the GTE predicate on the "time_range_end" field.
func TimeRangeEndGTE(v time.Time) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldGTE(FieldTimeRangeEnd, v))
}

// TimeRangeEndLT applies the LT predicate on the "time_range_end" field.
func TimeRangeEndLT(v time.Time) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldLT(FieldTimeRangeEnd, v))
}

// TimeRangeEndLTE applies the LTE predicate on the "time_range_end" field.
func TimeRangeEndLTE(v time.Time) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldLTE(FieldTimeRangeEnd, v))
}

// TotalCountEQ applies the EQ predicate on the "total_count" field.
func TotalCountEQ(v int32) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldEQ(FieldTotalCount, v))
}

// TotalCountNEQ applies the NEQ predicate on the "total_count" field.
func TotalCountNEQ(v int32) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldNEQ(FieldTotalCount, v))
}

// TotalCountIn applies the In predicate on the "total_count" field.
func TotalCountIn(vs ...int32) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldIn(FieldTotalCount, vs...))
}

// TotalCountNotIn applies the NotIn predicate on the "total_count" field.
func TotalCountNotIn(vs ...int32) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldNotIn(FieldTotalCount, vs...))
}

// TotalCountGT applies the GT predicate on the "total_count" field.
func TotalCountGT(v int32) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldGT(FieldTotalCount, v))
}

// TotalCountGTE applies the GTE predicate on the "total_count" field.
func TotalCountGTE(v int32) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldGTE(FieldTotalCount, v))
}

// TotalCountLT applies the LT predicate on the "total_count" field.
func TotalCountLT(v int32) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldLT(FieldTotalCount, v))
}

// TotalCountLTE applies the LTE predicate on the "total_count" field.
func TotalCountLTE(v int32) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldLTE(FieldTotalCount, v))
}

// MatchedCountEQ applies the EQ predicate on the "matched_count" field.
func MatchedCountEQ(v int32) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldEQ(FieldMatchedCount, v))
}

// MatchedCountNEQ applies the NEQ predicate on the "matched_count" field.
func MatchedCountNEQ(v int32) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldNEQ(FieldMatchedCount, v))
}

// MatchedCountIn applies the In predicate on the "matched_count" field.
func MatchedCountIn(vs ...int32) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldIn(FieldMatchedCount, vs...))
}

// MatchedCountNotIn applies the NotIn predicate on the "matched_count" field.
func MatchedCountNotIn(vs ...int32) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldNotIn(FieldMatchedCount, vs...))
}

// MatchedCountGT applies the GT predicate on the "matched_count" field.
func MatchedCountGT(v int32) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldGT(FieldMatchedCount, v))
}

// MatchedCountGTE applies the GTE predicate on the "matched_count" field.
func MatchedCountGTE(v int32) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldGTE(FieldMatchedCount, v))
}

// MatchedCountLT applies the LT predicate on the "matched_count" field.
func MatchedCountLT(v int32) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldLT(FieldMatchedCount, v))
}

// MatchedCountLTE applies the LTE predicate on the "matched_count" field.
func MatchedCountLTE(v int32) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldLTE(FieldMatchedCount, v))
}

// MismatchedCountEQ applies the EQ predicate on the "mismatched_count" field.
func MismatchedCountEQ(v int32) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldEQ(FieldMismatchedCount, v))
}

// MismatchedCountNEQ applies the NEQ predicate on the "mismatched_count" field.
func MismatchedCountNEQ(v int32) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldNEQ(FieldMismatchedCount, v))
}

// MismatchedCountIn applies the In predicate on the "mismatched_count" field.
func MismatchedCountIn(vs ...int32) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldIn(FieldMismatchedCount, vs...))
}

// MismatchedCountNotIn applies the NotIn predicate on the "mismatched_count" field.
func MismatchedCountNotIn(vs ...int32) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldNotIn(FieldMismatchedCount, vs...))
}

// MismatchedCountGT applies the GT predicate on the "mismatched_count" field.
func MismatchedCountGT(v int32) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldGT(FieldMismatchedCount, v))
}

// MismatchedCountGTE applies the GTE predicate on the "mismatched_count" field.
func MismatchedCountGTE(v int32) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldGTE(FieldMismatchedCount, v))
}

// MismatchedCountLT applies the LT predicate on the "mismatched_count" field.
func MismatchedCountLT(v int32) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldLT(FieldMismatchedCount, v))
}

// MismatchedCountLTE applies the LTE predicate on the "mismatched_count" field.
func MismatchedCountLTE(v int32) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldLTE(FieldMismatchedCount, v))
}

// ResultJSONIsNil applies the IsNil predicate on the "result_json" field.
func ResultJSONIsNil() predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldIsNull(FieldResultJSON))
}

// ResultJSONNotNil applies the NotNil predicate on the "result_json" field.
func ResultJSONNotNil() predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.FieldNotNull(FieldResultJSON))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ReconciliationJob) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ReconciliationJob) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ReconciliationJob) predicate.ReconciliationJob {
	return predicate.ReconciliationJob(sql.NotPredicates(p))
}
