package authz

// 权限点声明（P0-03 T1/T4）：每条 admin RPC 一条声明，Op 与 HTTP 注解同源。
// 新增管理路由必须在此（或对应模块）Declare——漏声明启动即失败（Reconcile fail-fast）。

func init() {
	Declare(
		// ── 认证（identity）──────────────────────────────
		Perm{Code: "auth:login", Desc: "管理员登录", Domain: "auth",
			Op: "zcard.api.admin.v1.AdminAuthService/Login", Method: "POST", Path: "/api/v1/admin/auth/login", Public: true},
		Perm{Code: "auth:profile", Desc: "查看当前身份", Domain: "auth",
			Op: "zcard.api.admin.v1.AdminAuthService/GetProfile", Method: "GET", Path: "/api/v1/admin/auth/profile"},
		Perm{Code: "auth:logout", Desc: "登出", Domain: "auth",
			Op: "zcard.api.admin.v1.AdminAuthService/Logout", Method: "POST", Path: "/api/v1/admin/auth/logout"},
		Perm{Code: "auth:refresh", Desc: "刷新令牌", Domain: "auth", Public: true,
			Op: "zcard.api.admin.v1.AdminAuthService/RefreshToken", Method: "POST", Path: "/api/v1/admin/auth/refresh"},
		Perm{Code: "auth:totp", Desc: "TOTP 绑定管理", Domain: "auth",
			Op: "zcard.api.admin.v1.AdminAuthService/EnableTOTP", Method: "POST", Path: "/api/v1/admin/auth/totp/enable"},
		Perm{Code: "auth:totp", Desc: "TOTP 绑定管理", Domain: "auth",
			Op: "zcard.api.admin.v1.AdminAuthService/ConfirmTOTP", Method: "POST", Path: "/api/v1/admin/auth/totp/confirm"},
		Perm{Code: "auth:totp", Desc: "TOTP 绑定管理", Domain: "auth",
			Op: "zcard.api.admin.v1.AdminAuthService/DisableTOTP", Method: "POST", Path: "/api/v1/admin/auth/totp/disable"},

		// ── 设置中心（settings）──────────────────────────
		Perm{Code: "settings:read", Desc: "查看设置", Domain: "settings",
			Op: "zcard.api.admin.v1.AdminSettingsService/ListSettings", Method: "GET", Path: "/api/v1/admin/settings"},
		Perm{Code: "settings:read_detail", Desc: "查看设置项", Domain: "settings",
			Op: "zcard.api.admin.v1.AdminSettingsService/GetSetting", Method: "GET", Path: "/api/v1/admin/settings/{group}/{key}"},
		Perm{Code: "settings:update", Desc: "修改设置", Domain: "settings",
			Op: "zcard.api.admin.v1.AdminSettingsService/UpdateSetting", Method: "PUT", Path: "/api/v1/admin/settings/{group}/{key}"},

		// ── 权限管理（authz，本任务 T2 新增路由）──────────
		Perm{Code: "authz:role_read", Desc: "查看角色", Domain: "authz",
			Op: "zcard.api.admin.v1.RoleService/ListRoles", Method: "GET", Path: "/api/v1/admin/authz/roles"},
		Perm{Code: "authz:role_read_detail", Desc: "查看角色详情", Domain: "authz",
			Op: "zcard.api.admin.v1.RoleService/GetRole", Method: "GET", Path: "/api/v1/admin/authz/roles/{id}"},
		Perm{Code: "authz:role_write", Desc: "创建/修改角色（超管专属）", Domain: "authz", AdminOnly: true,
			Op: "zcard.api.admin.v1.RoleService/CreateRole", Method: "POST", Path: "/api/v1/admin/authz/roles"},
		Perm{Code: "authz:role_write", Desc: "创建/修改角色（超管专属）", Domain: "authz", AdminOnly: true,
			Op: "zcard.api.admin.v1.RoleService/UpdateRole", Method: "PUT", Path: "/api/v1/admin/authz/roles/{id}"},
		Perm{Code: "authz:role_delete", Desc: "删除角色（超管专属）", Domain: "authz", AdminOnly: true,
			Op: "zcard.api.admin.v1.RoleService/DeleteRole", Method: "DELETE", Path: "/api/v1/admin/authz/roles/{id}"},
		Perm{Code: "authz:role_grant", Desc: "角色权限勾选（超管专属）", Domain: "authz", AdminOnly: true,
			Op: "zcard.api.admin.v1.RoleService/UpdateRolePermissions", Method: "PUT", Path: "/api/v1/admin/authz/roles/{id}/permissions"},
		Perm{Code: "authz:tree", Desc: "查看权限目录", Domain: "authz",
			Op: "zcard.api.admin.v1.RoleService/GetPermissionTree", Method: "GET", Path: "/api/v1/admin/authz/permissions"},

		// ── 员工管理（identity 数据层 + authz API 面）─────
		Perm{Code: "identity:admin_read", Desc: "查看员工", Domain: "identity",
			Op: "zcard.api.admin.v1.AdminUserService/ListAdmins", Method: "GET", Path: "/api/v1/admin/admins"},
		Perm{Code: "identity:admin_write", Desc: "创建/修改员工（超管专属）", Domain: "identity", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminUserService/CreateAdmin", Method: "POST", Path: "/api/v1/admin/admins"},
		Perm{Code: "identity:admin_write", Desc: "创建/修改员工（超管专属）", Domain: "identity", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminUserService/UpdateAdmin", Method: "PUT", Path: "/api/v1/admin/admins/{id}"},
		Perm{Code: "identity:admin_toggle", Desc: "启停员工（超管专属）", Domain: "identity", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminUserService/ToggleAdmin", Method: "PUT", Path: "/api/v1/admin/admins/{id}/toggle"},

		// ── 商品目录（catalog，P1-01）──────────────────
		Perm{Code: "catalog:read", Desc: "查看商品", Domain: "catalog",
			Op: "zcard.api.admin.v1.AdminCatalogService/ListProducts", Method: "GET", Path: "/api/v1/admin/products"},
		Perm{Code: "catalog:read_detail", Desc: "查看商品详情", Domain: "catalog",
			Op: "zcard.api.admin.v1.AdminCatalogService/GetProduct", Method: "GET", Path: "/api/v1/admin/products/{id}"},
		Perm{Code: "catalog:write", Desc: "创建商品（超管）", Domain: "catalog", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminCatalogService/CreateProduct", Method: "POST", Path: "/api/v1/admin/products"},
		Perm{Code: "catalog:write", Desc: "修改商品（超管）", Domain: "catalog", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminCatalogService/UpdateProduct", Method: "PUT", Path: "/api/v1/admin/products/{id}"},
		Perm{Code: "catalog:write", Desc: "批量上下架（超管）", Domain: "catalog", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminCatalogService/BatchUpdateProductStatus", Method: "POST", Path: "/api/v1/admin/products/batch-status"},
		Perm{Code: "catalog:delete", Desc: "删除商品", Domain: "catalog", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminCatalogService/DeleteProduct", Method: "DELETE", Path: "/api/v1/admin/products/{id}"},
		Perm{Code: "catalog:category_read", Desc: "查看分类", Domain: "catalog",
			Op: "zcard.api.admin.v1.AdminCatalogService/ListCategories", Method: "GET", Path: "/api/v1/admin/categories"},
		Perm{Code: "catalog:category_write", Desc: "创建分类（超管）", Domain: "catalog", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminCatalogService/CreateCategory", Method: "POST", Path: "/api/v1/admin/categories"},
		Perm{Code: "catalog:category_write", Desc: "修改分类（超管）", Domain: "catalog", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminCatalogService/UpdateCategory", Method: "PUT", Path: "/api/v1/admin/categories/{id}"},
		Perm{Code: "catalog:category_delete", Desc: "删除分类", Domain: "catalog", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminCatalogService/DeleteCategory", Method: "DELETE", Path: "/api/v1/admin/categories/{id}"},
		Perm{Code: "catalog:tag_read", Desc: "查看标签", Domain: "catalog",
			Op: "zcard.api.admin.v1.AdminCatalogService/ListTags", Method: "GET", Path: "/api/v1/admin/tags"},
		Perm{Code: "catalog:tag_write", Desc: "创建标签（超管）", Domain: "catalog", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminCatalogService/CreateTag", Method: "POST", Path: "/api/v1/admin/tags"},
		Perm{Code: "catalog:tag_delete", Desc: "删除标签（超管）", Domain: "catalog", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminCatalogService/DeleteTag", Method: "DELETE", Path: "/api/v1/admin/tags/{id}"},
		Perm{Code: "catalog:control_read", Desc: "查看控件", Domain: "catalog",
			Op: "zcard.api.admin.v1.AdminCatalogService/ListControls", Method: "GET", Path: "/api/v1/admin/products/{product_id}/controls"},
		Perm{Code: "catalog:control_write", Desc: "创建/修改控件（超管）", Domain: "catalog", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminCatalogService/CreateControl", Method: "POST", Path: "/api/v1/admin/products/{product_id}/controls"},
		Perm{Code: "catalog:control_write", Desc: "创建/修改控件（超管）", Domain: "catalog", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminCatalogService/UpdateControl", Method: "PUT", Path: "/api/v1/admin/controls/{id}"},
		Perm{Code: "catalog:control_delete", Desc: "删除控件（超管）", Domain: "catalog", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminCatalogService/DeleteControl", Method: "DELETE", Path: "/api/v1/admin/controls/{id}"},
		Perm{Code: "catalog:review_read", Desc: "查看评价", Domain: "catalog",
			Op: "zcard.api.admin.v1.AdminCatalogService/ListReviews", Method: "GET", Path: "/api/v1/admin/reviews"},
		Perm{Code: "catalog:review_manage", Desc: "评价审核（超管）", Domain: "catalog", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminCatalogService/ApproveReview", Method: "POST", Path: "/api/v1/admin/reviews/{id}/approve"},
		Perm{Code: "catalog:review_manage", Desc: "评价拒绝（超管）", Domain: "catalog", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminCatalogService/RejectReview", Method: "POST", Path: "/api/v1/admin/reviews/{id}/reject"},
		Perm{Code: "catalog:review_manage", Desc: "创建虚拟评价（超管）", Domain: "catalog", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminCatalogService/CreateVirtualReview", Method: "POST", Path: "/api/v1/admin/virtual-reviews"},
		Perm{Code: "catalog:sku_read", Desc: "查看 SKU", Domain: "catalog",
			Op: "zcard.api.admin.v1.AdminCatalogService/ListSkus", Method: "GET", Path: "/api/v1/admin/products/{product_id}/skus"},
		Perm{Code: "catalog:sku_write", Desc: "创建 SKU（超管）", Domain: "catalog", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminCatalogService/CreateSku", Method: "POST", Path: "/api/v1/admin/products/{product_id}/skus"},
		Perm{Code: "catalog:sku_write", Desc: "修改 SKU（超管）", Domain: "catalog", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminCatalogService/UpdateSku", Method: "PUT", Path: "/api/v1/admin/skus/{id}"},
		Perm{Code: "catalog:sku_write", Desc: "删除 SKU（超管）", Domain: "catalog", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminCatalogService/DeleteSku", Method: "DELETE", Path: "/api/v1/admin/skus/{id}"},
		Perm{Code: "catalog:group_read", Desc: "查看会员商品组", Domain: "catalog",
			Op: "zcard.api.admin.v1.AdminCatalogService/ListMemberGroups", Method: "GET", Path: "/api/v1/admin/member-groups"},
		Perm{Code: "catalog:group_write", Desc: "创建商品组（超管）", Domain: "catalog", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminCatalogService/CreateMemberGroup", Method: "POST", Path: "/api/v1/admin/member-groups"},
		Perm{Code: "catalog:group_write", Desc: "修改商品组（超管）", Domain: "catalog", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminCatalogService/UpdateMemberGroup", Method: "PUT", Path: "/api/v1/admin/member-groups/{id}"},
		Perm{Code: "catalog:group_write", Desc: "删除商品组（超管）", Domain: "catalog", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminCatalogService/DeleteMemberGroup", Method: "DELETE", Path: "/api/v1/admin/member-groups/{id}"},

		// ── 卡密库存（inventory，P1-02）────────────────
		Perm{Code: "inventory:read", Desc: "查看卡密", Domain: "inventory",
			Op: "zcard.api.admin.v1.AdminInventoryService/ListCards", Method: "GET", Path: "/api/v1/admin/inventory/cards"},
		Perm{Code: "inventory:import", Desc: "导入预览（超管）", Domain: "inventory", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminInventoryService/ImportPreview", Method: "POST", Path: "/api/v1/admin/inventory/preview"},
		Perm{Code: "inventory:import", Desc: "确认导入（超管）", Domain: "inventory", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminInventoryService/ImportConfirm", Method: "POST", Path: "/api/v1/admin/inventory/import"},
		Perm{Code: "inventory:read", Desc: "导入批次", Domain: "inventory",
			Op: "zcard.api.admin.v1.AdminInventoryService/ListImports", Method: "GET", Path: "/api/v1/admin/inventory/imports"},
		Perm{Code: "inventory:import", Desc: "撤销批次（超管）", Domain: "inventory", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminInventoryService/CancelImport", Method: "POST", Path: "/api/v1/admin/inventory/imports/{id}/cancel"},
		Perm{Code: "card:export", Desc: "导出卡密（超管）", Domain: "inventory", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminInventoryService/ExportCards", Method: "POST", Path: "/api/v1/admin/inventory/export"},
		Perm{Code: "inventory:write", Desc: "禁用/启用卡（超管）", Domain: "inventory", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminInventoryService/ToggleCard", Method: "PUT", Path: "/api/v1/admin/inventory/cards/{id}/toggle"},

		// ── 订单（order，P1-03）───────────────────────
		Perm{Code: "order:read", Desc: "查看订单", Domain: "order",
			Op: "zcard.api.admin.v1.AdminOrderService/ListOrders", Method: "GET", Path: "/api/v1/admin/orders"},
		Perm{Code: "order:read_detail", Desc: "查看订单详情", Domain: "order",
			Op: "zcard.api.admin.v1.AdminOrderService/GetOrder", Method: "GET", Path: "/api/v1/admin/orders/{order_no}"},
		Perm{Code: "order:cancel", Desc: "取消订单（超管）", Domain: "order", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminOrderService/CancelOrder", Method: "POST", Path: "/api/v1/admin/orders/{order_no}/cancel"},

		// ── 支付（payment，P1-04）─────────────────────
		Perm{Code: "payment:read", Desc: "查看渠道", Domain: "payment",
			Op: "zcard.api.admin.v1.AdminPaymentService/ListChannels", Method: "GET", Path: "/api/v1/admin/payment/channels"},
		Perm{Code: "payment:read", Desc: "查看驱动元数据（配置面表单 schema）", Domain: "payment",
			Op: "zcard.api.admin.v1.AdminPaymentService/ListDrivers", Method: "GET", Path: "/api/v1/admin/payment/drivers"},
		Perm{Code: "payment:read", Desc: "驱动字段动态选项（配置面下拉数据源）", Domain: "payment",
			Op: "zcard.api.admin.v1.AdminPaymentService/FieldOptions", Method: "GET", Path: "/api/v1/admin/payment/drivers/{code}/field-options"},
		Perm{Code: "payment:write", Desc: "创建渠道（超管）", Domain: "payment", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminPaymentService/CreateChannel", Method: "POST", Path: "/api/v1/admin/payment/channels"},
		Perm{Code: "payment:write", Desc: "修改渠道（超管）", Domain: "payment", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminPaymentService/UpdateChannel", Method: "PUT", Path: "/api/v1/admin/payment/channels/{id}"},
		Perm{Code: "payment:delete", Desc: "删除渠道", Domain: "payment", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminPaymentService/DeleteChannel", Method: "DELETE", Path: "/api/v1/admin/payment/channels/{id}"},
		Perm{Code: "payment:read_detail", Desc: "查看支付单", Domain: "payment",
			Op: "zcard.api.admin.v1.AdminPaymentService/ListPayments", Method: "GET", Path: "/api/v1/admin/payments"},
		Perm{Code: "payment:read_detail", Desc: "查看支付单详情", Domain: "payment",
			Op: "zcard.api.admin.v1.AdminPaymentService/GetPayment", Method: "GET", Path: "/api/v1/admin/payments/{id}"},
		Perm{Code: "payment:capture", Desc: "补单（超管）", Domain: "payment", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminPaymentService/CapturePayment", Method: "POST", Path: "/api/v1/admin/payments/{id}/capture"},
		Perm{Code: "order:refund", Desc: "创建退款", Domain: "payment", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminPaymentService/CreateRefund", Method: "POST", Path: "/api/v1/admin/refunds"},
		Perm{Code: "order:refund", Desc: "查看退款", Domain: "payment",
			Op: "zcard.api.admin.v1.AdminPaymentService/ListRefunds", Method: "GET", Path: "/api/v1/admin/refunds"},

		// ── 钱包（wallet，P1-05）──────────────────────
		Perm{Code: "wallet:read", Desc: "查用户余额", Domain: "wallet",
			Op: "zcard.api.admin.v1.AdminWalletService/GetBalance", Method: "GET", Path: "/api/v1/admin/wallet/{user_id}"},
		Perm{Code: "wallet:adjust", Desc: "手动调账（超管）", Domain: "wallet", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminWalletService/Adjust", Method: "POST", Path: "/api/v1/admin/wallet/{user_id}/adjust"},
		Perm{Code: "wallet:read", Desc: "查用户流水", Domain: "wallet",
			Op: "zcard.api.admin.v1.AdminWalletService/ListTransactions", Method: "GET", Path: "/api/v1/admin/wallet/{user_id}/transactions"},
		Perm{Code: "wallet:withdraw", Desc: "提现单列表", Domain: "wallet",
			Op: "zcard.api.admin.v1.AdminWalletService/ListWithdrawals", Method: "GET", Path: "/api/v1/admin/wallet/withdrawals"},
		Perm{Code: "wallet:withdraw_review", Desc: "提现审核（超管）", Domain: "wallet", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminWalletService/ReviewWithdrawal", Method: "POST", Path: "/api/v1/admin/wallet/withdrawals/{id}/review"},
		Perm{Code: "wallet:withdraw_review", Desc: "提现打款（超管）", Domain: "wallet", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminWalletService/PayWithdrawal", Method: "POST", Path: "/api/v1/admin/wallet/withdrawals/{id}/pay"},
		Perm{Code: "giftcard:write", Desc: "礼品卡批次创建（超管）", Domain: "wallet", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminWalletService/CreateGiftcardBatch", Method: "POST", Path: "/api/v1/admin/wallet/giftcard-batches"},
		Perm{Code: "giftcard:read", Desc: "礼品卡批次列表", Domain: "wallet",
			Op: "zcard.api.admin.v1.AdminWalletService/ListGiftcardBatches", Method: "GET", Path: "/api/v1/admin/wallet/giftcard-batches"},

		// ── 履约（fulfillment，P1-06）─────────────────
		Perm{Code: "order:view_delivery", Desc: "查看交付记录", Domain: "fulfillment",
			Op: "zcard.api.admin.v1.AdminFulfillmentService/ListDeliveries", Method: "GET", Path: "/api/v1/admin/fulfillment"},
		Perm{Code: "order:view_delivery", Desc: "待发货列表", Domain: "fulfillment",
			Op: "zcard.api.admin.v1.AdminFulfillmentService/ListPending", Method: "GET", Path: "/api/v1/admin/fulfillment/pending"},
		Perm{Code: "order:deliver", Desc: "手动发货（超管）", Domain: "fulfillment", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminFulfillmentService/ManualDeliver", Method: "POST", Path: "/api/v1/admin/fulfillment/{order_no}/deliver"},

		// ── 货币管理（settings，P0-04 T3）──────────────
		Perm{Code: "settings:currency_read", Desc: "查看货币", Domain: "settings",
			Op: "zcard.api.admin.v1.AdminCurrencyService/ListCurrencies", Method: "GET", Path: "/api/v1/admin/currencies"},
		Perm{Code: "settings:currency_write", Desc: "新增/修改货币（超管专属）", Domain: "settings", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminCurrencyService/CreateCurrency", Method: "POST", Path: "/api/v1/admin/currencies"},
		Perm{Code: "settings:currency_write", Desc: "新增/修改货币（超管专属）", Domain: "settings", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminCurrencyService/UpdateCurrency", Method: "PUT", Path: "/api/v1/admin/currencies/{code}"},
		Perm{Code: "settings:currency_delete", Desc: "删除货币", Domain: "settings", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminCurrencyService/DeleteCurrency", Method: "DELETE", Path: "/api/v1/admin/currencies/{code}"},

		// ── 会员等级（memberlevel，P3-01 M1b）────────────
		Perm{Code: "memberlevel:read", Desc: "查看会员等级", Domain: "memberlevel",
			Op: "zcard.api.admin.v1.AdminMemberLevelService/ListMemberLevels", Method: "GET", Path: "/api/v1/admin/member-levels"},
		Perm{Code: "memberlevel:write", Desc: "创建会员等级（超管）", Domain: "memberlevel", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminMemberLevelService/CreateMemberLevel", Method: "POST", Path: "/api/v1/admin/member-levels"},
		Perm{Code: "memberlevel:write", Desc: "修改会员等级（超管）", Domain: "memberlevel", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminMemberLevelService/UpdateMemberLevel", Method: "PUT", Path: "/api/v1/admin/member-levels/{id}"},
		Perm{Code: "memberlevel:delete", Desc: "删除会员等级（超管）", Domain: "memberlevel", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminMemberLevelService/DeleteMemberLevel", Method: "DELETE", Path: "/api/v1/admin/member-levels/{id}"},

		// ── 优惠券（coupon，P3-02 M1b）─────────────────
		Perm{Code: "coupon:read", Desc: "查看优惠券", Domain: "coupon",
			Op: "zcard.api.admin.v1.AdminCouponService/ListCoupons", Method: "GET", Path: "/api/v1/admin/coupons"},
		Perm{Code: "coupon:write", Desc: "批量生成优惠券（超管）", Domain: "coupon", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminCouponService/CreateCouponBatch", Method: "POST", Path: "/api/v1/admin/coupons/batch"},
		Perm{Code: "coupon:write", Desc: "作废优惠券（超管）", Domain: "coupon", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminCouponService/DisableCoupon", Method: "POST", Path: "/api/v1/admin/coupons/disable"},

		// ── 工作台（dashboard，P3-07 M1b）──────────────
		Perm{Code: "dashboard:read", Desc: "查看工作台指标", Domain: "dashboard",
			Op: "zcard.api.admin.v1.AdminDashboardService/GetDashboard", Method: "GET", Path: "/api/v1/admin/dashboard"},
		Perm{Code: "dashboard:read", Desc: "佣金列表", Domain: "dashboard",
			Op: "zcard.api.admin.v1.AdminDashboardService/ListCommissions", Method: "GET", Path: "/api/v1/admin/affiliate/commissions"},
		Perm{Code: "dashboard:read", Desc: "对账总览", Domain: "dashboard",
			Op: "zcard.api.admin.v1.AdminDashboardService/GetReconciliation", Method: "GET", Path: "/api/v1/admin/dashboard/reconciliation"},
		Perm{Code: "dashboard:read", Desc: "历史日结查询", Domain: "dashboard",
			Op: "zcard.api.admin.v1.AdminDashboardService/GetDailyStats", Method: "GET", Path: "/api/v1/admin/dashboard/daily-stats"},
		Perm{Code: "reconcile:read", Desc: "对账任务详情", Domain: "dashboard",
			Op: "zcard.api.admin.v1.AdminDashboardService/GetReconciliationJob", Method: "GET", Path: "/api/v1/admin/dashboard/reconciliation-jobs/{id}"},
		Perm{Code: "reconcile:read", Desc: "对账明细列表", Domain: "dashboard",
			Op: "zcard.api.admin.v1.AdminDashboardService/ListReconciliationItems", Method: "GET", Path: "/api/v1/admin/dashboard/reconciliation-jobs/{id}/items"},
		Perm{Code: "reconcile:write", Desc: "创建/执行对账任务（超管）", Domain: "dashboard", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminDashboardService/CreateReconciliationJob", Method: "POST", Path: "/api/v1/admin/dashboard/reconciliation-jobs"},
		Perm{Code: "reconcile:write", Desc: "执行对账任务（超管）", Domain: "dashboard", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminDashboardService/RunReconciliationJob", Method: "POST", Path: "/api/v1/admin/dashboard/reconciliation-jobs/{id}/run"},

		// ── 敏感权限点预登记（§5.20.4 防内部偷卡；路由 M1 落地）──
		Perm{Code: "card:view_content", Desc: "查看完整卡密（需二次确认+审计）", Domain: "inventory", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminInventoryService/ViewCardContent", Method: "GET", Path: "/api/v1/admin/inventory/cards/{id}/content"},
		Perm{Code: "card:premium", Desc: "查看靓号列表（超管）", Domain: "inventory", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminInventoryService/ListPremiumCards", Method: "GET", Path: "/api/v1/admin/inventory/cards/premium"},
		Perm{Code: "card:export", Desc: "导出卡密（审批+审计+限流）", Domain: "inventory", AdminOnly: true},

		Perm{Code: "order:refund", Desc: "订单退款（二次确认+审计）", Domain: "order", AdminOnly: true},
		Perm{Code: "system:update", Desc: "在线更新/密钥轮换", Domain: "system", AdminOnly: true},

		// ── 货源连接（supply，P2-01）──────────────────
		Perm{Code: "supply:read", Desc: "查看货源连接", Domain: "supply",
			Op: "zcard.api.admin.v1.AdminSupplyService/ListConnections", Method: "GET", Path: "/api/v1/admin/supply/connections"},
		Perm{Code: "supply:write", Desc: "管理货源连接（超管）", Domain: "supply", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminSupplyService/CreateConnection", Method: "POST", Path: "/api/v1/admin/supply/connections"},
		Perm{Code: "supply:write", Desc: "更新连接（超管）", Domain: "supply", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminSupplyService/UpdateConnection", Method: "PUT", Path: "/api/v1/admin/supply/connections/{id}"},
		Perm{Code: "supply:write", Desc: "删除连接（超管）", Domain: "supply", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminSupplyService/DeleteConnection", Method: "DELETE", Path: "/api/v1/admin/supply/connections/{id}"},
		Perm{Code: "supply:read", Desc: "连接探活", Domain: "supply",
			Op: "zcard.api.admin.v1.AdminSupplyService/PingConnection", Method: "POST", Path: "/api/v1/admin/supply/connections/{id}/ping"},
		Perm{Code: "supply:read", Desc: "商品映射列表", Domain: "supply",
			Op: "zcard.api.admin.v1.AdminSupplyService/ListMappings", Method: "GET", Path: "/api/v1/admin/supply/mappings"},
		Perm{Code: "supply:write", Desc: "维护映射（超管）", Domain: "supply", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminSupplyService/UpsertMapping", Method: "POST", Path: "/api/v1/admin/supply/mappings"},
		Perm{Code: "supply:write", Desc: "删除映射（超管）", Domain: "supply", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminSupplyService/DeleteMapping", Method: "DELETE", Path: "/api/v1/admin/supply/mappings/{id}"},
		Perm{Code: "supply:sync", Desc: "创建同步任务（超管）", Domain: "supply", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminSupplyService/CreateSyncTask", Method: "POST", Path: "/api/v1/admin/supply/sync-tasks"},
		Perm{Code: "supply:read", Desc: "同步任务列表", Domain: "supply",
			Op: "zcard.api.admin.v1.AdminSupplyService/ListSyncTasks", Method: "GET", Path: "/api/v1/admin/supply/sync-tasks"},
		Perm{Code: "supply:read", Desc: "同步任务详情", Domain: "supply",
			Op: "zcard.api.admin.v1.AdminSupplyService/GetSyncTask", Method: "GET", Path: "/api/v1/admin/supply/sync-tasks/{id}"},
		Perm{Code: "supply:sync", Desc: "取消同步任务（超管）", Domain: "supply", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminSupplyService/CancelSyncTask", Method: "POST", Path: "/api/v1/admin/supply/sync-tasks/{id}/cancel"},
		Perm{Code: "supply:read", Desc: "连接健康列表", Domain: "supply",
			Op: "zcard.api.admin.v1.AdminSupplyService/ListHealth", Method: "GET", Path: "/api/v1/admin/supply/health"},

		// ── 采购（procurement，P2-02）────────────────
		Perm{Code: "procurement:read", Desc: "采购单列表", Domain: "procurement",
			Op: "zcard.api.admin.v1.AdminProcurementService/ListProcurements", Method: "GET", Path: "/api/v1/admin/procurements"},
		Perm{Code: "procurement:read", Desc: "采购单详情", Domain: "procurement",
			Op: "zcard.api.admin.v1.AdminProcurementService/GetProcurement", Method: "GET", Path: "/api/v1/admin/procurements/{id}"},
		Perm{Code: "procurement:write", Desc: "手动重试采购（超管）", Domain: "procurement", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminProcurementService/RetryProcurement", Method: "POST", Path: "/api/v1/admin/procurements/{id}/retry"},
		Perm{Code: "procurement:write", Desc: "手动转人工（超管）", Domain: "procurement", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminProcurementService/MarkProcurementManual", Method: "POST", Path: "/api/v1/admin/procurements/{id}/manual"},

		// ── 对外供货（supplier，P2-03）────────────────
		Perm{Code: "supplier:read", Desc: "下游账户列表", Domain: "supplier",
			Op: "zcard.api.admin.v1.AdminSupplierService/ListAccounts", Method: "GET", Path: "/api/v1/admin/supplier/accounts"},
		Perm{Code: "supplier:write", Desc: "创建下游账户（超管）", Domain: "supplier", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminSupplierService/CreateAccount", Method: "POST", Path: "/api/v1/admin/supplier/accounts"},
		Perm{Code: "supplier:write", Desc: "审核账户（超管）", Domain: "supplier", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminSupplierService/ReviewAccount", Method: "POST", Path: "/api/v1/admin/supplier/accounts/{id}/review"},
		Perm{Code: "supplier:write", Desc: "启停账户（超管）", Domain: "supplier", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminSupplierService/ToggleAccount", Method: "POST", Path: "/api/v1/admin/supplier/accounts/{id}/toggle"},
		Perm{Code: "supplier:write", Desc: "重置密钥（超管）", Domain: "supplier", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminSupplierService/ResetSecret", Method: "POST", Path: "/api/v1/admin/supplier/accounts/{id}/reset-secret"},
		Perm{Code: "supplier:write", Desc: "配置回调地址（超管）", Domain: "supplier", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminSupplierService/SetNotifyURL", Method: "PUT", Path: "/api/v1/admin/supplier/accounts/{id}/notify-url"},
		Perm{Code: "supplier:write", Desc: "账户充值（超管）", Domain: "supplier", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminSupplierService/Recharge", Method: "POST", Path: "/api/v1/admin/supplier/accounts/{id}/recharge"},
		Perm{Code: "supplier:read", Desc: "账本流水", Domain: "supplier",
			Op: "zcard.api.admin.v1.AdminSupplierService/ListLedger", Method: "GET", Path: "/api/v1/admin/supplier/ledger"},
		Perm{Code: "supplier:write", Desc: "供货定价（超管）", Domain: "supplier", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminSupplierService/UpsertPrice", Method: "POST", Path: "/api/v1/admin/supplier/prices"},
		Perm{Code: "supplier:read", Desc: "回调记录", Domain: "supplier",
			Op: "zcard.api.admin.v1.AdminSupplierService/ListCallbacks", Method: "GET", Path: "/api/v1/admin/supplier/callbacks"},
		Perm{Code: "supplier:write", Desc: "手动重发回调（超管）", Domain: "supplier", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminSupplierService/ResendCallback", Method: "POST", Path: "/api/v1/admin/supplier/callbacks/{id}/resend"},

		// ── 内容（content，P2-04）────────────────────
		Perm{Code: "content:read", Desc: "横幅列表", Domain: "content",
			Op: "zcard.api.admin.v1.AdminContentService/ListBanners", Method: "GET", Path: "/api/v1/admin/content/banners"},
		Perm{Code: "content:write", Desc: "创建横幅（超管）", Domain: "content", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminContentService/CreateBanner", Method: "POST", Path: "/api/v1/admin/content/banners"},
		Perm{Code: "content:write", Desc: "更新横幅（超管）", Domain: "content", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminContentService/UpdateBanner", Method: "PUT", Path: "/api/v1/admin/content/banners/{id}"},
		Perm{Code: "content:write", Desc: "删除横幅（超管）", Domain: "content", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminContentService/DeleteBanner", Method: "DELETE", Path: "/api/v1/admin/content/banners/{id}"},
		Perm{Code: "content:read", Desc: "文章列表", Domain: "content",
			Op: "zcard.api.admin.v1.AdminContentService/ListPosts", Method: "GET", Path: "/api/v1/admin/content/posts"},
		Perm{Code: "content:write", Desc: "创建文章（超管）", Domain: "content", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminContentService/CreatePost", Method: "POST", Path: "/api/v1/admin/content/posts"},
		Perm{Code: "content:write", Desc: "更新文章（超管）", Domain: "content", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminContentService/UpdatePost", Method: "PUT", Path: "/api/v1/admin/content/posts/{id}"},
		Perm{Code: "content:write", Desc: "发布/取消文章（超管）", Domain: "content", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminContentService/PublishPost", Method: "POST", Path: "/api/v1/admin/content/posts/{id}/publish"},
		Perm{Code: "content:write", Desc: "删除文章（超管）", Domain: "content", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminContentService/DeletePost", Method: "DELETE", Path: "/api/v1/admin/content/posts/{id}"},
		Perm{Code: "content:read", Desc: "分类列表", Domain: "content",
			Op: "zcard.api.admin.v1.AdminContentService/ListCategories", Method: "GET", Path: "/api/v1/admin/content/categories"},
		Perm{Code: "content:write", Desc: "创建分类（超管）", Domain: "content", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminContentService/CreateCategory", Method: "POST", Path: "/api/v1/admin/content/categories"},
		Perm{Code: "content:write", Desc: "更新分类（超管）", Domain: "content", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminContentService/UpdateCategory", Method: "PUT", Path: "/api/v1/admin/content/categories/{id}"},
		Perm{Code: "content:write", Desc: "删除分类（超管）", Domain: "content", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminContentService/DeleteCategory", Method: "DELETE", Path: "/api/v1/admin/content/categories/{id}"},

		// ── 营销（coupon，P3-02 M3）──────────────────
		Perm{Code: "coupon:write", Desc: "赠送券（超管）", Domain: "coupon", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminCouponService/GrantCoupon", Method: "POST", Path: "/api/v1/admin/coupons/grant"},
		Perm{Code: "coupon:write", Desc: "创建秒杀（超管）", Domain: "coupon", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminCouponService/CreateFlashSale", Method: "POST", Path: "/api/v1/admin/flash-sales"},
		Perm{Code: "coupon:read", Desc: "秒杀列表", Domain: "coupon",
			Op: "zcard.api.admin.v1.AdminCouponService/ListFlashSales", Method: "GET", Path: "/api/v1/admin/flash-sales"},
		Perm{Code: "coupon:write", Desc: "删除秒杀（超管）", Domain: "coupon", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminCouponService/DeleteFlashSale", Method: "DELETE", Path: "/api/v1/admin/flash-sales/{id}"},
		Perm{Code: "coupon:write", Desc: "促销创建/更新（超管）", Domain: "coupon", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminCouponService/UpsertPromotion", Method: "POST", Path: "/api/v1/admin/promotions"},
		Perm{Code: "coupon:read", Desc: "促销列表", Domain: "coupon",
			Op: "zcard.api.admin.v1.AdminCouponService/ListPromotions", Method: "GET", Path: "/api/v1/admin/promotions"},

		// ── 分站（reseller，P3-04 主站面）──────────
		Perm{Code: "reseller:read", Desc: "分站列表", Domain: "reseller",
			Op: "zcard.api.admin.v1.AdminResellerService/ListProfiles", Method: "GET", Path: "/api/v1/admin/reseller/profiles"},
		Perm{Code: "reseller:review", Desc: "审核分站申请（超管）", Domain: "reseller", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminResellerService/ReviewApply", Method: "POST", Path: "/api/v1/admin/reseller/apply/{id}/review"},
		Perm{Code: "reseller:pricing", Desc: "分站定价规则（超管）", Domain: "reseller", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminResellerService/UpsertPricing", Method: "POST", Path: "/api/v1/admin/reseller/pricing"},
		Perm{Code: "reseller:read", Desc: "分站账本", Domain: "reseller",
			Op: "zcard.api.admin.v1.AdminResellerService/Ledger", Method: "GET", Path: "/api/v1/admin/reseller/ledger"},
		Perm{Code: "reseller:read", Desc: "分站余额", Domain: "reseller",
			Op: "zcard.api.admin.v1.AdminResellerService/Balance", Method: "GET", Path: "/api/v1/admin/reseller/balance"},
		Perm{Code: "reseller:site", Desc: "我的域名（分站主）", Domain: "reseller",
			Op: "zcard.api.admin.v1.AdminResellerService/MySites", Method: "GET", Path: "/api/v1/admin/reseller/my/sites"},
		Perm{Code: "reseller:site", Desc: "登记域名（分站主）", Domain: "reseller",
			Op: "zcard.api.admin.v1.AdminResellerService/AddSite", Method: "POST", Path: "/api/v1/admin/reseller/my/sites"},
		Perm{Code: "reseller:site", Desc: "验证域名（分站主）", Domain: "reseller",
			Op: "zcard.api.admin.v1.AdminResellerService/VerifySite", Method: "POST", Path: "/api/v1/admin/reseller/my/sites/{site_id}/verify"},
		Perm{Code: "reseller:site", Desc: "白标设置（分站主）", Domain: "reseller",
			Op: "zcard.api.admin.v1.AdminResellerService/SetWhitelabel", Method: "POST", Path: "/api/v1/admin/reseller/my/sites/{site_id}/whitelabel"},
		Perm{Code: "reseller:product", Desc: "自营商品上架（分站主）", Domain: "reseller",
			Op: "zcard.api.admin.v1.AdminResellerService/CreateProduct", Method: "POST", Path: "/api/v1/admin/reseller/products"},

		// ── 订阅许可证（license，P3-08）─────────────
		Perm{Code: "license:read", Desc: "许可证状态", Domain: "license",
			Op: "zcard.api.admin.v1.AdminLicenseService/GetLicenseStatus", Method: "GET", Path: "/api/v1/admin/license"},
		Perm{Code: "license:write", Desc: "安装/清除许可证（超管）", Domain: "license", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminLicenseService/InstallLicense", Method: "POST", Path: "/api/v1/admin/license"},
		Perm{Code: "license:write", Desc: "清除许可证（超管）", Domain: "license", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminLicenseService/ClearLicense", Method: "DELETE", Path: "/api/v1/admin/license"},

		// ── 素材库（media，P3-06）───────────────────
		Perm{Code: "media:read", Desc: "分类列表", Domain: "media",
			Op: "zcard.api.admin.v1.AdminMediaService/ListCategories", Method: "GET", Path: "/api/v1/admin/media/categories"},
		Perm{Code: "media:read", Desc: "素材列表", Domain: "media",
			Op: "zcard.api.admin.v1.AdminMediaService/ListMedia", Method: "GET", Path: "/api/v1/admin/media"},
		Perm{Code: "media:write", Desc: "创建分类（超管）", Domain: "media", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminMediaService/CreateCategory", Method: "POST", Path: "/api/v1/admin/media/categories"},
		Perm{Code: "media:write", Desc: "分类改名（超管）", Domain: "media", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminMediaService/RenameCategory", Method: "POST", Path: "/api/v1/admin/media/categories/{id}/rename"},
		Perm{Code: "media:write", Desc: "分类移动（超管）", Domain: "media", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminMediaService/MoveCategory", Method: "POST", Path: "/api/v1/admin/media/categories/{id}/move"},
		Perm{Code: "media:write", Desc: "删除分类（超管）", Domain: "media", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminMediaService/DeleteCategory", Method: "DELETE", Path: "/api/v1/admin/media/categories/{id}"},
		Perm{Code: "media:upload", Desc: "上传素材", Domain: "media",
			Op: "zcard.api.admin.v1.AdminMediaService/Upload", Method: "POST", Path: "/api/v1/admin/media/upload"},
		Perm{Code: "media:upload", Desc: "外链导入", Domain: "media",
			Op: "zcard.api.admin.v1.AdminMediaService/ImportFromURL", Method: "POST", Path: "/api/v1/admin/media/import"},
		Perm{Code: "media:write", Desc: "素材改名（超管）", Domain: "media", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminMediaService/RenameMedia", Method: "POST", Path: "/api/v1/admin/media/{id}/rename"},
		Perm{Code: "media:write", Desc: "素材移动（超管）", Domain: "media", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminMediaService/MoveMedia", Method: "POST", Path: "/api/v1/admin/media/move"},
		Perm{Code: "media:delete", Desc: "删除素材（引用需确认）", Domain: "media", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminMediaService/DeleteMedia", Method: "POST", Path: "/api/v1/admin/media/delete"},

		// ── 工单（ticket，P3-05）────────────────────
		Perm{Code: "ticket:read", Desc: "工单工作台", Domain: "ticket",
			Op: "zcard.api.admin.v1.AdminTicketService/ListTickets", Method: "GET", Path: "/api/v1/admin/tickets"},
		Perm{Code: "ticket:read", Desc: "工单详情（含内部备注）", Domain: "ticket",
			Op: "zcard.api.admin.v1.AdminTicketService/GetTicket", Method: "GET", Path: "/api/v1/admin/tickets/{ticket_no}"},
		Perm{Code: "ticket:write", Desc: "回复/内部备注", Domain: "ticket",
			Op: "zcard.api.admin.v1.AdminTicketService/ReplyTicket", Method: "POST", Path: "/api/v1/admin/tickets/{ticket_no}/reply"},
		Perm{Code: "ticket:write", Desc: "解决工单", Domain: "ticket",
			Op: "zcard.api.admin.v1.AdminTicketService/ResolveTicket", Method: "POST", Path: "/api/v1/admin/tickets/{ticket_no}/resolve"},
		Perm{Code: "ticket:write", Desc: "关闭工单", Domain: "ticket",
			Op: "zcard.api.admin.v1.AdminTicketService/CloseTicket", Method: "POST", Path: "/api/v1/admin/tickets/{ticket_no}/close"},

		// ── 通知（notify，P2-05）────────────────────
		Perm{Code: "notify:read", Desc: "通知模板列表", Domain: "notify",
			Op: "zcard.api.admin.v1.AdminNotifyService/ListTemplates", Method: "GET", Path: "/api/v1/admin/notify/templates"},
		Perm{Code: "notify:read", Desc: "发送日志", Domain: "notify",
			Op: "zcard.api.admin.v1.AdminNotifyService/ListLogs", Method: "GET", Path: "/api/v1/admin/notify/logs"},
		Perm{Code: "notify:write", Desc: "模板编辑（超管）", Domain: "notify", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminNotifyService/UpsertTemplate", Method: "POST", Path: "/api/v1/admin/notify/templates"},
		Perm{Code: "notify:write", Desc: "模板预览（超管）", Domain: "notify", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminNotifyService/PreviewTemplate", Method: "POST", Path: "/api/v1/admin/notify/templates/preview"},
		Perm{Code: "notify:write", Desc: "重发日志（超管）", Domain: "notify", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminNotifyService/ResendLog", Method: "POST", Path: "/api/v1/admin/notify/logs/{id}/resend"},
		Perm{Code: "notify:write", Desc: "群发预估/创建/列表/取消（超管）", Domain: "notify", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminNotifyService/EstimateBroadcast", Method: "POST", Path: "/api/v1/admin/notify/broadcasts/estimate"},
		Perm{Code: "notify:write", Desc: "创建群发（超管）", Domain: "notify", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminNotifyService/CreateBroadcast", Method: "POST", Path: "/api/v1/admin/notify/broadcasts"},
		Perm{Code: "notify:write", Desc: "群发列表（超管）", Domain: "notify", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminNotifyService/ListBroadcasts", Method: "GET", Path: "/api/v1/admin/notify/broadcasts"},
		Perm{Code: "notify:write", Desc: "取消群发（超管）", Domain: "notify", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminNotifyService/CancelBroadcast", Method: "POST", Path: "/api/v1/admin/notify/broadcasts/{id}/cancel"},

		// ── 审计与风控（audit，P2-06）───────────────
		Perm{Code: "audit:read", Desc: "操作审计", Domain: "audit",
			Op: "zcard.api.admin.v1.AdminAuditService/ListOpLogs", Method: "GET", Path: "/api/v1/admin/audit/op-logs"},
		Perm{Code: "audit:read", Desc: "安全审计", Domain: "audit",
			Op: "zcard.api.admin.v1.AdminAuditService/ListSecurityLogs", Method: "GET", Path: "/api/v1/admin/audit/security-logs"},
		Perm{Code: "audit:read", Desc: "访问统计", Domain: "audit",
			Op: "zcard.api.admin.v1.AdminAuditService/ListVisitStats", Method: "GET", Path: "/api/v1/admin/audit/visit-stats"},
		Perm{Code: "audit:read", Desc: "黑名单查看", Domain: "audit",
			Op: "zcard.api.admin.v1.AdminAuditService/GetBlacklist", Method: "GET", Path: "/api/v1/admin/audit/blacklist"},
		Perm{Code: "audit:write", Desc: "黑名单管理（超管）", Domain: "audit", AdminOnly: true,
			Op: "zcard.api.admin.v1.AdminAuditService/SetBlacklist", Method: "PUT", Path: "/api/v1/admin/audit/blacklist"},
	)
}
